/*
 * Soyogi (Edizione anziani) — content.it.js
 * Contenuti di conversazione in italiano (scritti per la cultura italiana).
 * ============================================================================
 * ★NON è una traduzione di content.ja.js. I ricordi sono legati alla cultura;
 *   questo pacchetto è scritto attorno a ricordi che un anziano in Italia può
 *   condividere volentieri (le lire, i Mondiali dell'82, la Fiat 500…). Schema
 *   uguale a ja (vedi l'intestazione di content.ja.js; spunto: cue = {open, asks[], expand, care}).
 *   Le date storiche sono verificate e citate. Verificare anche ogni aggiunta.
 * ============================================================================
 */
window.SOYOGI_WS_CONTENT = window.SOYOGI_WS_CONTENT || {};
window.SOYOGI_WS_CONTENT["it"] = {

  /* ---- Scheda 1: fiore del giorno (per mese; significati positivi) ---- */
  flowers: [
    { month:1,  name:"Bucaneve",         emoji:"🌼", photo:null, meaning:"Speranza", note:"Spunta coraggioso dalla neve nel cuore dell'inverno." },
    { month:2,  name:"Viola",            emoji:"🌸", photo:null, meaning:"Modestia e fedeltà", note:"Un piccolo fiore profumato che annuncia la primavera." },
    { month:3,  name:"Narciso",          emoji:"🌼", photo:null, meaning:"Rinascita", note:"Con il suo giallo apre la primavera." },
    { month:4,  name:"Tulipano",         emoji:"🌷", photo:null, meaning:"Amore", note:"Porta colore nei giardini e nei vasi." },
    { month:5,  name:"Mughetto",         emoji:"🌷", photo:null, meaning:"Ritorno della felicità", note:"Piccole campanelle bianche dal profumo delicato." },
    { month:6,  name:"Rosa",             emoji:"🌹", photo:null, meaning:"Amore e gratitudine", note:"Il fiore classico dell'estate." },
    { month:7,  name:"Girasole",         emoji:"🌻", photo:null, meaning:"Allegria e ammirazione", note:"Volge il volto verso il sole d'estate." },
    { month:8,  name:"Gelsomino",        emoji:"🌸", photo:null, meaning:"Dolcezza e amabilità", note:"Profuma le sere d'estate." },
    { month:9,  name:"Dalia",            emoji:"🌸", photo:null, meaning:"Dignità e gratitudine", note:"Generosa, fiorisce fino ai primi freddi." },
    { month:10, name:"Astro",            emoji:"🌸", photo:null, meaning:"Pazienza ed eleganza", note:"Una stella che porta l'estate nell'autunno." },
    { month:11, name:"Camelia",          emoji:"🌺", photo:null, meaning:"Fedeltà e ammirazione", note:"Fiorisce quando quasi tutto riposa." },
    { month:12, name:"Stella di Natale", emoji:"🌺", photo:null, meaning:"Gioia del Natale", note:"Il rosso e il verde delle feste." }
  ],

  /* ---- Scheda 1: accadde oggi (eventi lieti e verificati) ---- */
  onThisDay: [
    { month:1,  day:3,  year:1954, text:"La RAI inizia le trasmissioni televisive ufficiali in Italia.", emoji:"📺" },
    { month:6,  day:2,  year:1946, text:"L'Italia diventa una Repubblica con il referendum: nasce la Festa della Repubblica.", emoji:"🇮🇹" },
    { month:7,  day:4,  year:1957, text:"La Fiat presenta al pubblico la \"Nuova 500\", con una sfilata per le vie di Torino.", emoji:"🚗" },
    { month:7,  day:9,  year:2006, text:"L'Italia è campione del mondo di calcio, battendo la Francia ai rigori.", emoji:"⚽" },
    { month:7,  day:11, year:1982, text:"L'Italia è campione del mondo di calcio, battendo la Germania Ovest 3-1.", emoji:"⚽" },
    { month:8,  day:25, year:1960, text:"Si aprono a Roma i Giochi Olimpici estivi.", emoji:"🏅" }
  ],

  /* ---- Scheda 2: quiz dei ricordi (lo sapevi + spunto per operatori) ---- */
  quizzes: [
    {
      id:"it-warmup-01", genre:"warmup", emoji:"🍉", photo:null,
      question:"Cosa è più grande e più pesante — un'anguria o una mela?",
      choices:["L'anguria","La mela"], answerIndex:0,
      trivia:"Un'anguria grande può superare i 10 chili — un piacere d'estate da sempre.",
      cue:{
        open:"«Questa era facile, vero?» — con un sorriso, poi verso i ricordi d'estate.",
        asks:[
          "Mangiavate l'anguria d'estate?",
          "Facevate gite o scampagnate?",
          "Con chi passavate le estati?"
        ],
        expand:"Conta più il piacere del momento che la risposta giusta. Un vostro piccolo ricordo («da noi c'era sempre…») aiuta la persona ad aprirsi.",
        care:"Se esita, nessun problema — «sono buone entrambe!» mantiene tutto leggero. Un sorriso è già un successo."
      }
    },
    {
      id:"it-warmup-02", genre:"warmup", emoji:"🥔", photo:null,
      question:"Cosa pesa di più — un sacco di patate o una piuma?",
      choices:["Un sacco di patate","Una piuma"], answerIndex:0,
      trivia:"Un sacco di patate pesa in fretta diversi chili. Le patate sono state a lungo un alimento base.",
      cue:{
        open:"«Le patate, di sicuro — pesano parecchio!» Poi verso la cucina di una volta.",
        asks:[
          "Coltivavate o raccoglievate le patate?",
          "Qual era il vostro piatto preferito da bambini?",
          "Chi cucinava in casa?"
        ],
        expand:"Il cibo risveglia ricordi forti. Chiedete dei profumi e del pranzo della domenica — la scena torna viva.",
        care:"Se il cibo è un tema delicato, restate sul ricordo, non sul cibo in sé."
      }
    },
    {
      id:"it-price-01", genre:"price", emoji:"💰", photo:null,
      question:"Con quale moneta si pagava in Italia prima dell'euro?",
      choices:["La lira","L'euro","Il franco"], answerIndex:0,
      trivia:"Fino al 2002 si pagava in lire. L'euro in monete e banconote è arrivato il 1º gennaio 2002.",
      cue:{
        open:"«Ah, le vecchie lire!» — molti le ricordano con affetto.",
        asks:[
          "Ricordate bene le lire?",
          "Cosa si poteva comprare con poche lire?",
          "Come mettevate da parte la paghetta da bambini?"
        ],
        expand:"I soldi aprono la porta alla vita di una volta — i prezzi, i primi acquisti, i piccoli piaceri. Seguite il filo del ricordo.",
        care:"Alcuni hanno avuto poco. Mantenete un tono di stupore condiviso, mai di confronto."
      }
    },
    {
      id:"it-appliance-01", genre:"appliance", emoji:"📺", photo:null,
      question:"Prima dei telecomandi, come si cambiava canale alla televisione?",
      choices:["Girando la manopola dell'apparecchio","Battendo le mani","Fischiando allo schermo"], answerIndex:0,
      trivia:"Qualcuno doveva alzarsi e girare la manopola — spesso il più piccolo di casa!",
      cue:{
        open:"«Qualcuno doveva alzarsi e girare la manopola!» — con un sorriso.",
        asks:[
          "Quali programmi guardavate in famiglia?",
          "Chi decideva il canale?",
          "Ricordate il primo televisore in casa?"
        ],
        expand:"Il «primo televisore» è un ricordo lieto e facile, spesso legato a tutta la famiglia. Chiedete chi c'era nella stanza.",
        care:"Non tutte le case ebbero presto un apparecchio. Chiedete «ricordate quando arrivò?» invece di darlo per scontato."
      }
    },
    {
      id:"it-snack-01", genre:"snack", emoji:"🍭", photo:null,
      question:"Come si chiama la golosità da luna park fatta di zucchero filato tutto rosa?",
      choices:["Lo zucchero filato","Il torrone","La liquirizia"], answerIndex:0,
      trivia:"Leggero e dolcissimo, lo zucchero filato era la gioia del luna park e delle sagre di paese.",
      cue:{
        open:"«Quel dolce rosa e soffice del luna park!»",
        asks:[
          "Andavate al luna park o alla sagra del paese?",
          "Qual era la vostra golosità preferita da bambini?",
          "C'era una bottega o un negozio di dolci vicino a casa?"
        ],
        expand:"Le golosità d'infanzia sono ricordi allegri e facili da raccontare. I nomi dei luoghi e degli amici li rendono vivi.",
        care:"Per alcuni il dopoguerra fu duro. Non date nulla per scontato e andate al ritmo della persona."
      }
    },
    {
      id:"it-tool-01", genre:"tool", emoji:"⌨️", photo:null,
      question:"Prima dei computer, quale macchina da ufficio batteva l'inchiostro sulla carta?",
      choices:["La macchina da scrivere","Il registratore di cassa","La macchina da cucire"], answerIndex:0,
      trivia:"Il ticchettio dei tasti e il campanello a fine riga erano suoni di tutti i giorni in ufficio.",
      cue:{
        open:"«Quel ticchettio dei tasti — e il campanello a fine riga!»",
        asks:[
          "Che lavoro facevate?",
          "Quali strumenti o macchine usavate ogni giorno?",
          "In cosa eravate particolarmente bravi nel vostro lavoro?"
        ],
        expand:"Parlare del lavoro e delle proprie capacità rafforza l'autostima. «Sarete stati veloci!» fa sempre piacere.",
        care:"Per chi non ha lavorato fuori casa, chiedete delle capacità usate in casa."
      }
    },
    {
      id:"it-fashion-01", genre:"fashion", emoji:"👖", photo:null,
      question:"Quali pantaloni molto svasati in fondo erano di moda negli anni '70?",
      choices:["I pantaloni a zampa d'elefante","I pantaloni alla zuava","La salopette"], answerIndex:0,
      trivia:"I pantaloni «a zampa d'elefante» andavano di pari passo con la musica e lo spirito di quegli anni.",
      cue:{
        open:"«Seguivate la moda a quei tempi?» — con un sorriso.",
        asks:[
          "Quali stili andavano di moda quando eravate giovani?",
          "Avevate un capo preferito?",
          "Cosa indossavate per uscire o per un appuntamento?"
        ],
        expand:"I ricordi di moda sono quelli della gioventù splendente — spesso legati agli amori. I volti si illuminano.",
        care:"Per chi ha perso il coniuge, questi ricordi possono avere una nota di malinconia. Osservate il volto e non insistete."
      }
    },
    {
      id:"it-hobby-01", genre:"hobby", emoji:"🔢", photo:null,
      question:"A quale gioco si disegnano caselle per terra e si salta su un piede solo?",
      choices:["La campana","Le biglie","Il nascondino"], answerIndex:0,
      trivia:"La «campana» si disegnava col gesso e si saltava di casella in casella — un grande classico dei cortili.",
      cue:{
        open:"«Eravate bravi a giocare a campana?»",
        asks:[
          "A cosa giocavate da bambini?",
          "In quale gioco eravate particolarmente bravi?",
          "Dove vi trovavate con gli amici per giocare?"
        ],
        expand:"I ricordi dei giochi vanno a braccetto con gli amici e i luoghi. I giochi di movimento riportano la sensazione di essere giovani e pieni di energia.",
        care:"Alcuni preferivano stare da soli. Tenete la domanda aperta: «come vi piaceva passare il tempo?»"
      }
    },
    {
      id:"it-warmup-03", genre:"warmup", emoji:"🍋", photo:null,
      question:"Cosa è più dolce — lo zucchero o un limone?",
      choices:["Lo zucchero","Il limone"], answerIndex:0,
      trivia:"Un tempo lo zucchero era prezioso; una torta era un vero piacere dei giorni di festa.",
      cue:{
        open:"«Lo zucchero, di certo!» — con un sorriso, poi verso i dolci di una volta.",
        asks:["Si facevano spesso dolci in casa vostra?","Chi cucinava i dolci?","Qual era il dolce che preferivate?"],
        expand:"I dolci e le feste risvegliano ricordi teneri. Chiedere dei profumi — vaniglia, cannella — fa rivivere la scena.",
        care:"Anche se i dolci erano rari, riconoscetelo con calore: «erano altri tempi»."
      }
    },
    {
      id:"it-price-02", genre:"price", emoji:"🎬", photo:null,
      question:"Quanto costava circa un biglietto del cinema negli anni '60?",
      choices:["Circa 300 lire","Circa 3.000 lire","Circa 30.000 lire"], answerIndex:0,
      trivia:"Una serata al cinema era uno svago alla portata di tutti, per poche lire.",
      cue:{
        open:"«Al cinema per poche lire — bei tempi, vero?»",
        asks:["Andavate spesso al cinema?","Quali film o attori vi piacevano?","Con chi ci andavate?"],
        expand:"Non conta il prezzo esatto, ma il ricordo. Il cinegiornale, il gelato nell'intervallo, il primo appuntamento — c'è tanto da raccontare.",
        care:"In caso di incertezza, un esempio della vostra vita aiuta a far rivivere insieme quei tempi."
      }
    },
    {
      id:"it-appliance-02", genre:"appliance", emoji:"☎️", photo:null,
      question:"Come si componeva un numero sui vecchi telefoni?",
      choices:["Con il disco combinatore","Con lo schermo tattile"], answerIndex:0,
      trivia:"Si girava una cifra alla volta sul disco, con un ronzio caratteristico.",
      cue:{
        open:"«Il disco — girarlo ci metteva un po', vero?»",
        asks:["Avevate il telefono in casa già presto?","Chi chiamavate più volentieri?","Ricordate il vostro vecchio numero?"],
        expand:"Il telefono lega alla famiglia e agli amici. Il ronzio del disco riporta indietro nel tempo.",
        care:"Molti ebbero il telefono solo tardi — è normale ed è un bel motivo di conversazione."
      }
    },
    {
      id:"it-snack-02", genre:"snack", emoji:"🍬", photo:null,
      question:"Quali caramelle dall'incarto rosso e oro, col cuore morbido, sono un classico da generazioni?",
      choices:["Le Rossana","Il croccante"], answerIndex:0,
      trivia:"Le Rossana, caramelle dure con il ripieno morbido, sono amate da tantissimi da quasi un secolo.",
      cue:{
        open:"«Le Rossana — quell'incarto rosso e oro!» Con un sorriso, verso le golosità di un tempo.",
        asks:["Quali caramelle si trovavano nella bottega del paese?","Avevate la paghetta per i dolci?","Qual era la vostra golosità preferita?"],
        expand:"La bottega del quartiere e pochi spiccioli di paghetta sono bei punti d'aggancio.",
        care:"Se i dolci erano rari, onorate quei tempi frugali con gentilezza, senza giudizio."
      }
    },
    {
      id:"it-tool-02", genre:"tool", emoji:"🧺", photo:null,
      question:"Con cosa si lavavano i panni a mano, prima delle lavatrici?",
      choices:["Con l'asse per lavare","Con l'aspirapolvere"], answerIndex:0,
      trivia:"Si strofinavano i panni sull'asse, spesso al lavatoio — un vero lavoro, nel giorno del bucato.",
      cue:{
        open:"«L'asse per lavare — era proprio faticoso, vero?»",
        asks:["Il giorno del bucato era un giorno fisso da voi?","Chi si occupava del bucato?","Dove stendevate i panni ad asciugare?"],
        expand:"I lavori di casa di una volta mostrano tanta sapienza. Un «era un lavoro duro!» onora la fatica.",
        care:"Il riconoscimento fa bene: «avete portato avanti tutto voi» rende fieri e apre il dialogo."
      }
    },
    {
      id:"it-fashion-02", genre:"fashion", emoji:"👗", photo:null,
      question:"Quale gonna ampia e svasata, perfetta per ballare, era di moda negli anni '50?",
      choices:["La gonna a ruota","I pantaloni a zampa d'elefante"], answerIndex:0,
      trivia:"La gonna a ruota, larga e vaporosa, girava vorticosa nei balli degli anni '50.",
      cue:{
        open:"«La gonna a ruota — girava tutta quando si ballava!»",
        asks:["Vi piaceva andare a ballare?","Quale moda vi piaceva da giovani?","Avevate un vestito preferito o un bel completo?"],
        expand:"La moda e il ballo risvegliano la gioventù. Il primo ballo, il primo amore — belle porte da aprire.",
        care:"Ogni ricordo è prezioso — anche un sorriso senza parole è un bel risultato."
      }
    },
    {
      id:"it-hobby-02", genre:"hobby", emoji:"🔵", photo:null,
      question:"Come si chiamano le palline di vetro colorate con cui i bambini giocavano per terra?",
      choices:["Le biglie","I bottoni"], answerIndex:0,
      trivia:"Si giocava a biglie per terra; le più belle si custodivano e si scambiavano come tesori.",
      cue:{
        open:"«Le biglie — le più belle si tenevano come un tesoro, vero?»",
        asks:["Collezionavate o scambiavate le biglie?","A quali giochi giocavate all'aperto?","Con chi vi piaceva giocare?"],
        expand:"Collezionare e scambiare risvegliano i ricordi di amicizia e di vicinato.",
        care:"Se l'infanzia è stata difficile, restate con delicatezza sui bei momenti."
      }
    },
    {
      id:"it-appliance-03", genre:"appliance", emoji:"🎵", photo:null,
      question:"Come si ascoltava la musica preferita a casa una volta?",
      choices:["Su un disco in vinile","Sullo smartphone"], answerIndex:0,
      trivia:"Il disco girava sul giradischi; si appoggiava con delicatezza la puntina sul solco.",
      cue:{
        open:"«Mettere il disco e la puntina — un piccolo rito, vero?»",
        asks:["Quale musica o quali cantanti vi piacevano?","Avevate un giradischi in casa?","Su quale musica ballavate?"],
        expand:"La musica è un ancoraggio potente. Basta il titolo di una canzone e arrivano i ricordi.",
        care:"Se una canzone commuove, è prezioso — lasciate tutto lo spazio all'emozione."
      }
    }
  ],

  /* ---- Scheda 3: questo o quello? (leggero — basta una frase) ---- */
  eitherOr: [
    { id:"it-eo-01", left:{label:"Caffè", emoji:"☕"}, right:{label:"Tè", emoji:"🍵"},
      staffCue:"«Siete più da caffè o da tè? Come lo prendete?»" },
    { id:"it-eo-02", left:{label:"Mare", emoji:"🌊"}, right:{label:"Montagna", emoji:"⛰️"},
      staffCue:"«Dove andavate in vacanza — al mare o in montagna?»" },
    { id:"it-eo-03", left:{label:"Cane", emoji:"🐕"}, right:{label:"Gatto", emoji:"🐈"},
      staffCue:"«Avete mai avuto un animale? Come si chiamava?»" },
    { id:"it-eo-04", left:{label:"Dolce", emoji:"🍰"}, right:{label:"Salato", emoji:"🥨"},
      staffCue:"«Più goloso di dolce o di salato? A cosa non sapevate resistere?»" },
    { id:"it-eo-05", left:{label:"Pasta", emoji:"🍝"}, right:{label:"Pizza", emoji:"🍕"},
      staffCue:"«Meglio la pasta o la pizza? Qual era il piatto della domenica?»" },
    { id:"it-eo-06", left:{label:"Radio", emoji:"📻"}, right:{label:"Televisione", emoji:"📺"},
      staffCue:"«Radio o televisione — cosa si ascoltava di più a casa vostra?»" },
    { id:"it-eo-07", left:{label:"Città", emoji:"🏙️"}, right:{label:"Campagna", emoji:"🌾"},
      staffCue:"«Siete cresciuti più in città o in campagna?»" },
    { id:"it-eo-08", left:{label:"Primavera", emoji:"🌸"}, right:{label:"Autunno", emoji:"🍂"},
      staffCue:"«Primavera o autunno — quale stagione preferite?»" },
    { id:"it-eo-09", left:{label:"Ballare", emoji:"💃"}, right:{label:"Cantare", emoji:"🎤"},
      staffCue:"«Vi piaceva più ballare o cantare?»" },
    { id:"it-eo-10", left:{label:"Cinema", emoji:"🎬"}, right:{label:"Libro", emoji:"📖"},
      staffCue:"«Una serata al cinema o un bel libro — cosa preferivate?»" },
    { id:"it-eo-11", left:{label:"Bicicletta", emoji:"🚲"}, right:{label:"A piedi", emoji:"🚶"},
      staffCue:"«Vi spostavate molto in bicicletta o piuttosto a piedi?»" },
    { id:"it-eo-12", left:{label:"Natale", emoji:"🎄"}, right:{label:"Pasqua", emoji:"🐰"},
      staffCue:"«Natale o Pasqua — quale festa amavate di più da bambini?»" },
    { id:"it-eo-13", left:{label:"Minestra", emoji:"🍲"}, right:{label:"Arrosto", emoji:"🍖"},
      staffCue:"«Una buona minestra o un arrosto della domenica?»" },
    { id:"it-eo-14", left:{label:"Gelato", emoji:"🍨"}, right:{label:"Cioccolata", emoji:"☕"},
      staffCue:"«Un gelato d'estate o una cioccolata calda d'inverno?»" },
    { id:"it-eo-15", left:{label:"Mattiniero", emoji:"🌅"}, right:{label:"Nottambulo", emoji:"🌙"},
      staffCue:"«Eravate più mattinieri o nottambuli?»" }
  ],

  /* ---- Scheda 3: colore dell'umore (sempre positivo) ---- */
  colorTest: {
    prompt:null,
    options:[
      { key:"red",    label:"Rosso", emoji:"🔴", color:"#e0655e",
        result:"Siete calorosi e pieni di energia — come un sole che rincuora chi vi sta intorno.",
        cue:"«A cosa vi siete dedicati con tutto il cuore da giovani?»" },
      { key:"blue",   label:"Blu",   emoji:"🔵", color:"#4a86c9",
        result:"Siete calmi e premurosi — una persona di cui gli altri si fidano e su cui si appoggiano.",
        cue:"«Eravate spesso voi la persona a cui gli altri chiedevano consiglio?»" },
      { key:"yellow", label:"Giallo", emoji:"🟡", color:"#eab52f",
        result:"Siete allegri e curiosi — portate vita in ogni stanza.",
        cue:"«C'è un ricordo felice che vi fa ancora sorridere?»" },
      { key:"green",  label:"Verde", emoji:"🟢", color:"#4a9d6f",
        result:"Siete gentili e sereni — una presenza che mette gli altri a proprio agio.",
        cue:"«C'è un luogo o un panorama dove vi sentite in pace?»" },
      { key:"orange", label:"Arancione", emoji:"🟠", color:"#e8934a",
        result:"Siete cordiali e socievoli — una persona che sa unire gli altri.",
        cue:"«Gli amici e i vicini hanno sempre contato molto per voi?»" },
      { key:"purple", label:"Viola", emoji:"🟣", color:"#8a6bd0",
        result:"Siete raffinati e sensibili — di una forza tranquilla, con una ricca vita interiore.",
        cue:"«C'è una musica o un'arte che vi ha sempre commosso?»" }
    ]
  },

  /* ---- Personaggi celebri (compleanno 🎂 / anniversario 🕯️). Date verificate nel pacchetto ja. ---- */
  people: [
    { month:10, day:10, type:"birth", name:"Giuseppe Verdi",       note:"Compositore italiano. Nato nel 1813. Celebre per opere come «La traviata» e «Aida»." },
    { month:1,  day:27, type:"death", name:"Giuseppe Verdi",       note:"Compositore. Morto nel 1901. Maestro dell'opera italiana." },
    { month:12, day:22, type:"birth", name:"Giacomo Puccini",      note:"Compositore italiano. Nato nel 1858. Celebre per «Madama Butterfly» e «Tosca»." },
    { month:11, day:29, type:"death", name:"Giacomo Puccini",      note:"Compositore. Morto nel 1924. Tra i più grandi dell'opera italiana." },
    { month:3,  day:4,  type:"birth", name:"Antonio Vivaldi",      note:"Compositore italiano. Nato nel 1678. Celebre per il concerto «Le quattro stagioni»." },
    { month:7,  day:28, type:"death", name:"Antonio Vivaldi",      note:"Compositore. Morto nel 1741. Tra i grandi della musica barocca." },
    { month:2,  day:29, type:"birth", name:"Gioachino Rossini",    note:"Compositore italiano. Nato nel 1792, un 29 febbraio bisestile. Celebre per «Il barbiere di Siviglia»." },
    { month:11, day:13, type:"death", name:"Gioachino Rossini",    note:"Compositore. Morto nel 1868. Amato per le sue opere brillanti." },
    { month:3,  day:26, type:"death", name:"Ludwig van Beethoven", note:"Compositore tedesco. Nato intorno al 1770, morto nel 1827. Celebre per la Nona sinfonia." },
    { month:1,  day:27, type:"birth", name:"Wolfgang Amadeus Mozart", note:"Compositore austriaco. Nato nel 1756. Un genio musicale dalle innumerevoli opere." },
    { month:12, day:5,  type:"death", name:"Wolfgang Amadeus Mozart", note:"Compositore. Morto nel 1791. Tra i più grandi del classicismo viennese." },
    { month:7,  day:28, type:"death", name:"Johann Sebastian Bach", note:"Compositore tedesco. Nato nel 1685, morto nel 1750. Il «padre della musica», gigante del barocco." },
    { month:10, day:17, type:"death", name:"Frédéric Chopin",      note:"Compositore polacco. Nato nel 1810, morto nel 1849. È chiamato il «poeta del pianoforte»." },
    { month:5,  day:7,  type:"birth", name:"Pëtr Čajkovskij",      note:"Compositore russo. Nato nel 1840. Celebre per «Il lago dei cigni» e «Lo schiaccianoci»." },
    { month:11, day:6,  type:"death", name:"Pëtr Čajkovskij",      note:"Compositore. Morto nel 1893. Autore di splendida musica per balletto." },
    { month:11, day:14, type:"birth", name:"Claude Monet",         note:"Pittore francese. Nato nel 1840. Maestro dell'impressionismo, celebre per le «Ninfee»." },
    { month:12, day:5,  type:"death", name:"Claude Monet",         note:"Pittore. Morto nel 1926. «Impressione, levar del sole» diede il nome all'impressionismo." },
    { month:3,  day:30, type:"birth", name:"Vincent van Gogh",     note:"Pittore olandese. Nato nel 1853. Celebre per «I girasoli» e «Notte stellata»." },
    { month:7,  day:29, type:"death", name:"Vincent van Gogh",     note:"Pittore. Morto nel 1890. Maestro del postimpressionismo apprezzato dopo la morte." },
    { month:10, day:25, type:"birth", name:"Pablo Picasso",        note:"Pittore spagnolo. Nato nel 1881. Cofondatore del cubismo e gigante dell'arte moderna." },
    { month:4,  day:8,  type:"death", name:"Pablo Picasso",        note:"Pittore. Morto nel 1973. Celebre anche per «Guernica»." },
    { month:3,  day:14, type:"birth", name:"Albert Einstein",      note:"Fisico nato in Germania. Nato nel 1879. La sua teoria della relatività cambiò il mondo." },
    { month:4,  day:18, type:"death", name:"Albert Einstein",      note:"Fisico. Morto nel 1955. Tra i più grandi scienziati del XX secolo." },
    { month:5,  day:12, type:"birth", name:"Florence Nightingale", note:"Infermiera britannica. Nata nel 1820. Fondatrice dell'assistenza moderna; il 12 maggio è la Giornata degli infermieri." },
    { month:8,  day:13, type:"death", name:"Florence Nightingale", note:"Infermiera. Morta nel 1910. Nota come «la signora della lampada»." },
    { month:11, day:7,  type:"birth", name:"Marie Curie",          note:"Fisica e chimica. Nata nel 1867. La prima donna a ricevere un premio Nobel." },
    { month:7,  day:4,  type:"death", name:"Marie Curie",          note:"Scienziata. Morta nel 1934. Pioniera degli studi sulla radioattività." },
    { month:2,  day:12, type:"birth", name:"Charles Darwin",       note:"Naturalista britannico. Nato nel 1809. Autore de «L'origine delle specie» e della teoria dell'evoluzione." },
    { month:4,  day:19, type:"death", name:"Charles Darwin",       note:"Naturalista. Morto nel 1882. Ha segnato profondamente la biologia." },
    { month:2,  day:11, type:"birth", name:"Thomas Edison",        note:"Inventore americano. Nato nel 1847. Celebre per la lampadina e il fonografo." },
    { month:10, day:18, type:"death", name:"Thomas Edison",        note:"Inventore. Morto nel 1931. Era chiamato il «mago di Menlo Park»." },
    { month:12, day:27, type:"birth", name:"Louis Pasteur",        note:"Batteriologo francese. Nato nel 1822. Sviluppò i vaccini e la pastorizzazione." },
    { month:9,  day:28, type:"death", name:"Louis Pasteur",        note:"Batteriologo. Morto nel 1895. Considerato padre della microbiologia moderna." },
    { month:8,  day:6,  type:"birth", name:"Alexander Fleming",    note:"Batteriologo britannico. Nato nel 1881. Scoprì il primo antibiotico, la penicillina." },
    { month:3,  day:11, type:"death", name:"Alexander Fleming",    note:"Batteriologo. Morto nel 1955. La penicillina salvò innumerevoli vite; premio Nobel." },
    { month:4,  day:16, type:"birth", name:"Charlie Chaplin",      note:"Attore e regista inglese. Nato nel 1889. Le sue comiche mute fecero ridere il mondo." },
    { month:12, day:25, type:"death", name:"Charlie Chaplin",      note:"Il «Charlot». Morto nel 1977. Amato per film come «Tempi moderni»." },
    { month:6,  day:1,  type:"birth", name:"Marilyn Monroe",       note:"Attrice americana. Nata nel 1926. Un'icona del cinema degli anni '50." },
    { month:8,  day:4,  type:"death", name:"Marilyn Monroe",       note:"Attrice. Morta nel 1962. Una delle stelle più durature di Hollywood." },
    { month:1,  day:8,  type:"birth", name:"Elvis Presley",        note:"Cantante americano. Nato nel 1935. Noto come il «re del rock'n'roll»." },
    { month:8,  day:16, type:"death", name:"Elvis Presley",        note:"Cantante. Morto nel 1977. Diffuse il rock'n'roll in tutto il mondo." },
    { month:4,  day:2,  type:"birth", name:"Hans Christian Andersen", note:"Scrittore danese di fiabe. Nato nel 1805. Celebre per «La sirenetta» e «La piccola fiammiferaia»." },
    { month:8,  day:4,  type:"death", name:"Hans Christian Andersen", note:"Scrittore di fiabe. Morto nel 1875. Le sue fiabe sono amate in tutto il mondo." },
    { month:2,  day:26, type:"birth", name:"Victor Hugo",          note:"Scrittore francese. Nato nel 1802. Autore de «I miserabili»." },
    { month:5,  day:22, type:"death", name:"Victor Hugo",          note:"Scrittore. Morto nel 1885. Figura del romanticismo, ebbe funerali di Stato." },
    { month:6,  day:12, type:"birth", name:"Anne Frank",           note:"Autrice del «Diario di Anne Frank». Nata nel 1929. Una ragazza che scriveva, nascosta dai nazisti." },
    /* ---- Trasferimento di personalità mondiali (dati indipendenti dalla lingua) — Lotto 1 ---- */
    { month:7,  day:6,  type:"birth", name:"Frida Kahlo",           note:"Pittrice messicana. Nata nel 1907. Famosa in tutto il mondo per i suoi autoritratti dai colori vivaci." },
    { month:7,  day:6,  type:"birth", name:"Sylvester Stallone",    note:"Attore americano. Nato nel 1946. Noto per i film «Rocky» e «Rambo»." },
    { month:7,  day:6,  type:"death", name:"Louis Armstrong",       note:"Musicista jazz americano. Morto nel 1971. Amato per «What a Wonderful World»." },
    { month:7,  day:6,  type:"death", name:"Odilon Redon",          note:"Pittore francese. Morto nel 1916. Noto per il suo stile onirico." },
    { month:5,  day:4,  type:"birth", name:"Audrey Hepburn",        note:"Attrice. Nata nel 1929. Nota per «Vacanze romane»; negli ultimi anni si dedicò anche alla beneficenza." },
    { month:1,  day:20, type:"death", name:"Audrey Hepburn",        note:"Attrice. Morta nel 1993. Amata per film come «Vacanze romane»." },
    { month:10, day:9,  type:"birth", name:"John Lennon",           note:"Musicista britannico. Nato nel 1940. Noto come membro dei Beatles." },
    { month:8,  day:26, type:"birth", name:"Madre Teresa",          note:"Religiosa cattolica. Nata nel 1910. Aiutò i poveri e ricevette il Premio Nobel per la pace." },
    { month:9,  day:5,  type:"death", name:"Madre Teresa",          note:"Religiosa. Morta nel 1997. Venerata come «la madre dei poveri»." },
    { month:10, day:2,  type:"birth", name:"Mahatma Gandhi",        note:"Guida dell'indipendenza dell'India. Nato nel 1869. Guidò la resistenza nonviolenta." },
    { month:6,  day:27, type:"birth", name:"Helen Keller",          note:"Attivista americana. Nata nel 1880. Sorda e cieca, diede coraggio al mondo intero." },
    { month:6,  day:1,  type:"death", name:"Helen Keller",          note:"Attivista sociale. Morta nel 1968. Agì al di là della sua disabilità." },
    { month:2,  day:12, type:"birth", name:"Abraham Lincoln",       note:"16º presidente degli Stati Uniti. Nato nel 1809. Portò avanti l'abolizione della schiavitù." },
    { month:8,  day:29, type:"birth", name:"Michael Jackson",       note:"Cantante americano. Nato nel 1958. Era chiamato il «re del pop»." },
    { month:12, day:5,  type:"birth", name:"Walt Disney",           note:"Autore di cartoni animati e imprenditore americano. Nato nel 1901. Creatore di Topolino." },
    { month:12, day:15, type:"death", name:"Walt Disney",           note:"Autore di cartoni animati. Morto nel 1966. Fondatore di Disneyland." },
    { month:7,  day:21, type:"birth", name:"Ernest Hemingway",      note:"Romanziere americano. Nato nel 1899. Premio Nobel, noto per «Il vecchio e il mare»." },
    { month:5,  day:29, type:"birth", name:"John F. Kennedy",       note:"35º presidente degli Stati Uniti. Nato nel 1917. Divenuto presidente da giovane, affascinò la gente." },
    { month:11, day:30, type:"birth", name:"Winston Churchill",     note:"Statista britannico. Nato nel 1874. Primo ministro durante la Seconda guerra mondiale, celebre per i suoi discorsi." },
    { month:1,  day:24, type:"death", name:"Winston Churchill",     note:"Primo ministro britannico. Morto nel 1965. Ricevette anche il Premio Nobel per la letteratura." },
    { month:2,  day:6,  type:"birth", name:"Babe Ruth",             note:"Giocatore di baseball americano. Nato nel 1895. Un battitore leggendario." },
    { month:8,  day:16, type:"death", name:"Babe Ruth",             note:"Giocatore di baseball. Morto nel 1948. Un'icona del baseball americano." },
    { month:2,  day:25, type:"birth", name:"Auguste Renoir",        note:"Pittore francese. Nato nel 1841. Un maestro dell'impressionismo, pieno di luce e gioia di vivere." },
    { month:12, day:3,  type:"death", name:"Auguste Renoir",        note:"Pittore. Morto nel 1919. In vecchiaia continuò a dipingere nonostante l'artrite." },
    { month:1,  day:31, type:"birth", name:"Franz Schubert",        note:"Compositore austriaco. Nato nel 1797. «Re del lied», noto per «Il re degli elfi»." },
    { month:11, day:19, type:"death", name:"Franz Schubert",        note:"Compositore. Morto nel 1828 a soli 31 anni. Lasciò la «Sinfonia incompiuta»." },
    { month:6,  day:29, type:"birth", name:"Antoine de Saint-Exupéry", note:"Scrittore e aviatore francese. Nato nel 1900. Autore de «Il Piccolo Principe»." },
    { month:5,  day:7,  type:"birth", name:"Johannes Brahms",       note:"Compositore tedesco. Nato nel 1833. Uno dei «tre B» insieme a Bach e Beethoven." },
    { month:4,  day:3,  type:"death", name:"Johannes Brahms",       note:"Compositore. Morto nel 1897. Amato per la sua «Ninna nanna»." },
    { month:5,  day:22, type:"birth", name:"Richard Wagner",        note:"Compositore tedesco. Nato nel 1813. Celebre per i suoi grandi drammi musicali." },
    { month:2,  day:13, type:"death", name:"Richard Wagner",        note:"Compositore. Morto nel 1883. Lasciò «L'anello del Nibelungo»." },
    { month:11, day:30, type:"birth", name:"Mark Twain",            note:"Scrittore americano. Nato nel 1835. Noto per «Le avventure di Tom Sawyer»." },
    { month:4,  day:21, type:"death", name:"Mark Twain",            note:"Scrittore. Morto nel 1910. Le sue opere piene di umorismo e ironia sono ancora amate." },
    { month:12, day:31, type:"birth", name:"Henri Matisse",         note:"Pittore francese. Nato nel 1869. «Mago del colore» e maestro del fauvismo." },
    { month:11, day:3,  type:"death", name:"Henri Matisse",         note:"Pittore. Morto nel 1954. In vecchiaia esplorò anche l'arte dei ritagli di carta." },
    { month:5,  day:11, type:"birth", name:"Salvador Dalí",         note:"Pittore spagnolo. Nato nel 1904. Noto per gli orologi molli — un maestro del surrealismo." },
    { month:1,  day:23, type:"death", name:"Salvador Dalí",         note:"Pittore. Morto nel 1989. Celebre anche per i suoi baffi singolari." },
    { month:1,  day:19, type:"birth", name:"Paul Cézanne",          note:"Pittore francese. Nato nel 1839. «Padre della pittura moderna»." },
    { month:10, day:23, type:"death", name:"Paul Cézanne",          note:"Pittore. Morto nel 1906. Le sue mele e montagne influenzarono l'arte del XX secolo." },
    { month:2,  day:8,  type:"birth", name:"James Dean",            note:"Attore americano. Nato nel 1931. Noto per «La valle dell'Eden» — un idolo dei giovani." },
    { month:9,  day:8,  type:"birth", name:"Antonín Dvořák",        note:"Compositore ceco. Nato nel 1841. Noto per la sinfonia «Dal Nuovo Mondo»." },
    { month:5,  day:1,  type:"death", name:"Antonín Dvořák",        note:"Compositore. Morto nel 1904. Intessé nelle sue opere le melodie della sua terra." },
    { month:8,  day:28, type:"birth", name:"Goethe",                note:"Grande scrittore tedesco. Nato nel 1749. Noto per «Faust» e «I dolori del giovane Werther»." },
    { month:3,  day:22, type:"death", name:"Goethe",                note:"Scrittore. Morto nel 1832. Un poeta e autore simbolo della Germania." },
    { month:10, day:21, type:"birth", name:"Alfred Nobel",          note:"Inventore svedese. Nato nel 1833. Inventò la dinamite e istituì i premi Nobel." },
    { month:12, day:10, type:"death", name:"Alfred Nobel",          note:"Inventore. Morto nel 1896. Il 10 dicembre è tuttora il giorno della consegna dei Nobel." },
    { month:3,  day:3,  type:"birth", name:"Alexander Graham Bell", note:"Inventore. Nato nel 1847. Inventò il primo telefono pratico." },
    { month:8,  day:2,  type:"death", name:"Alexander Graham Bell", note:"Inventore. Morto nel 1922. Con il telefono cambiò il mondo." },
    { month:8,  day:29, type:"birth", name:"Ingrid Bergman",        note:"Attrice svedese. Nata nel 1915. Nota per «Casablanca»." },
    { month:8,  day:29, type:"death", name:"Ingrid Bergman",        note:"Attrice. Morta nel 1982, proprio nel giorno del suo compleanno, il 29 agosto." },
    { month:11, day:12, type:"birth", name:"Grace Kelly",           note:"Attrice americana. Nata nel 1929. Da attrice di Hollywood divenne principessa di Monaco." },
    { month:5,  day:26, type:"birth", name:"John Wayne",            note:"Attore americano. Nato nel 1907. Una grande star del western." },
    { month:6,  day:11, type:"death", name:"John Wayne",            note:"Attore. Morto nel 1979. Chiamato affettuosamente «Duke»." },
    { month:12, day:12, type:"birth", name:"Frank Sinatra",         note:"Cantante e attore americano. Nato nel 1915. Noto per «My Way»." },
    { month:5,  day:14, type:"death", name:"Frank Sinatra",         note:"Cantante e attore. Morto nel 1998. Un artista simbolo del XX secolo." },
    { month:6,  day:7,  type:"birth", name:"Paul Gauguin",          note:"Pittore francese. Nato nel 1848. Dipinse la gente e i paesaggi di Tahiti." },
    { month:5,  day:8,  type:"death", name:"Paul Gauguin",          note:"Pittore. Morto nel 1903. Noto anche per l'amicizia con van Gogh." },
    { month:11, day:20, type:"death", name:"Lev Tolstoj",           note:"Scrittore russo. Morto nel 1910. Noto per «Guerra e pace» e «Anna Karenina»." },
    { month:2,  day:9,  type:"death", name:"Fëdor Dostoevskij",     note:"Scrittore russo. Morto nel 1881. Noto per «Delitto e castigo» e «I fratelli Karamazov»." },
    { month:10, day:4,  type:"birth", name:"Jean-François Millet",  note:"Pittore francese. Nato nel 1814. Noto per «Le spigolatrici» e «L'Angelus»." },
    { month:1,  day:20, type:"death", name:"Jean-François Millet",  note:"Pittore. Morto nel 1875. Un maestro della pittura dei contadini della scuola di Barbizon." },
    { month:7,  day:19, type:"birth", name:"Edgar Degas",           note:"Pittore francese. Nato nel 1834. Noto per i suoi quadri di ballerine." },
    { month:9,  day:27, type:"death", name:"Edgar Degas",           note:"Pittore. Morto nel 1917. Un impressionista che colse l'attimo del movimento." },
    { month:7,  day:14, type:"birth", name:"Gustav Klimt",          note:"Pittore austriaco. Nato nel 1862. Noto per «Il bacio», impreziosito da foglia d'oro." },
    { month:2,  day:6,  type:"death", name:"Gustav Klimt",          note:"Pittore. Morto nel 1918. Guidò la Secessione viennese." },
    { month:12, day:12, type:"birth", name:"Edvard Munch",          note:"Pittore norvegese. Nato nel 1863. Famoso in tutto il mondo come autore de «L'urlo»." },
    { month:1,  day:23, type:"death", name:"Edvard Munch",          note:"Pittore. Morto nel 1944. Un espressionista che dipinse l'angoscia e la solitudine." },
    { month:2,  day:7,  type:"birth", name:"Charles Dickens",       note:"Scrittore inglese. Nato nel 1812. Noto per «Canto di Natale» e «Oliver Twist»." },
    { month:6,  day:9,  type:"death", name:"Charles Dickens",       note:"Scrittore. Morto nel 1870. Un autore nazionale attento ai più deboli." },
    /* ---- Lotto 2 ---- */
    { month:2,  day:3,  type:"birth", name:"Felix Mendelssohn",     note:"Compositore tedesco. Nato nel 1809. Noto per la «Marcia nuziale» e «Sogno di una notte di mezza estate»." },
    { month:11, day:4,  type:"death", name:"Felix Mendelssohn",     note:"Compositore. Morto nel 1847. Una grande figura del romanticismo." },
    { month:6,  day:8,  type:"birth", name:"Robert Schumann",       note:"Compositore tedesco. Nato nel 1810. Noto per brani pianistici come «Träumerei» e per i suoi lieder." },
    { month:7,  day:29, type:"death", name:"Robert Schumann",       note:"Compositore. Morto nel 1856. È chiamato il poeta della musica romantica." },
    { month:10, day:22, type:"birth", name:"Franz Liszt",           note:"Compositore ungherese. Nato nel 1811. Noto per le «Rapsodie ungheresi» — il «mago del pianoforte»." },
    { month:7,  day:31, type:"death", name:"Franz Liszt",           note:"Compositore. Morto nel 1886. Celebre anche come pianista virtuoso." },
    { month:8,  day:22, type:"birth", name:"Claude Debussy",        note:"Compositore francese. Nato nel 1862. Noto per «Chiaro di luna» e «La Mer»." },
    { month:3,  day:25, type:"death", name:"Claude Debussy",        note:"Compositore. Morto nel 1918. Un maestro della musica impressionista." },
    { month:1,  day:4,  type:"birth", name:"Louis Braille",         note:"Inventore francese della scrittura per ciechi. Nato nel 1809. Divenuto cieco, creò la scrittura a punti." },
    { month:1,  day:6,  type:"death", name:"Louis Braille",         note:"Inventore del Braille. Morto nel 1852. Portò la lettura ai ciechi di tutto il mondo." },
    { month:2,  day:4,  type:"birth", name:"Rosa Parks",            note:"Attivista americana per i diritti civili. Nata nel 1913. Il suo rifiuto di cedere il posto sull'autobus avviò un movimento." },
    { month:10, day:24, type:"death", name:"Rosa Parks",            note:"Attivista per i diritti civili. Morta nel 2005. Chiamata «la madre del movimento per i diritti civili»." },
    { month:2,  day:2,  type:"birth", name:"James Joyce",           note:"Scrittore irlandese. Nato nel 1882. Autore dell'«Ulisse», un'opera cardine del XX secolo." },
    { month:1,  day:13, type:"death", name:"James Joyce",           note:"Scrittore. Morto nel 1941. Segnò la letteratura moderna con forme nuove." },
    { month:8,  day:15, type:"birth", name:"Napoleone Bonaparte",   note:"Imperatore dei francesi. Nato nel 1769. Guidò la Francia rivoluzionaria e dominò l'Europa." },
    { month:5,  day:5,  type:"death", name:"Napoleone Bonaparte",   note:"Imperatore dei francesi. Morto nel 1821 in esilio. Noto per la frase «impossibile non è francese»." },
    { month:3,  day:24, type:"birth", name:"Harry Houdini",         note:"Artista della fuga americano. Nato nel 1874. Chiamato il «re della fuga», stupì il mondo." },
    { month:10, day:31, type:"death", name:"Harry Houdini",         note:"Illusionista. Morto nel 1926, proprio ad Halloween, il 31 ottobre." },
    { month:5,  day:31, type:"birth", name:"Clint Eastwood",        note:"Attore e regista americano. Nato nel 1930. Noto per i western e «Ispettore Callaghan»." },
    { month:8,  day:9,  type:"birth", name:"Jean Piaget",           note:"Psicologo svizzero. Nato nel 1896. Studiò lo sviluppo della mente nel bambino." },
    { month:2,  day:23, type:"birth", name:"Georg Friedrich Händel", note:"Compositore nato in Germania. Nato nel 1685. Noto per l'oratorio «Il Messia»." },
    { month:4,  day:14, type:"death", name:"Georg Friedrich Händel", note:"Compositore. Morto nel 1759. Attivo in Inghilterra, lasciò solenni opere corali." },
    { month:3,  day:31, type:"birth", name:"Joseph Haydn",          note:"Compositore austriaco. Nato nel 1732. «Padre della sinfonia», autore di innumerevoli opere." },
    { month:5,  day:31, type:"death", name:"Joseph Haydn",          note:"Compositore. Morto nel 1809. Diede forma al quartetto d'archi e alla sinfonia." },
    { month:7,  day:7,  type:"birth", name:"Gustav Mahler",         note:"Compositore e direttore d'orchestra austriaco. Nato nel 1860. Noto per le sue grandiose sinfonie." },
    { month:5,  day:18, type:"death", name:"Gustav Mahler",         note:"Compositore. Morto nel 1911. Fece da ponte tra la musica dell'Ottocento e del Novecento." },
    { month:6,  day:15, type:"birth", name:"Edvard Grieg",          note:"Compositore norvegese. Nato nel 1843. Noto per la suite «Peer Gynt»." },
    { month:9,  day:4,  type:"death", name:"Edvard Grieg",          note:"Compositore. Morto nel 1907. Portò nel mondo le melodie della Norvegia." },
    { month:12, day:8,  type:"birth", name:"Jean Sibelius",         note:"Compositore finlandese. Nato nel 1865. Noto per il poema sinfonico «Finlandia»." },
    { month:9,  day:20, type:"death", name:"Jean Sibelius",         note:"Compositore. Morto nel 1957. Il grande compositore nazionale della Finlandia." },
    { month:10, day:9,  type:"birth", name:"Camille Saint-Saëns",   note:"Compositore francese. Nato nel 1835. Noto per «Il carnevale degli animali»." },
    { month:12, day:16, type:"death", name:"Camille Saint-Saëns",   note:"Compositore. Morto nel 1921. Lasciò belle opere anche per organo e concerto." },
    { month:10, day:25, type:"birth", name:"Georges Bizet",         note:"Compositore francese. Nato nel 1838. Noto per l'opera «Carmen»." },
    { month:6,  day:3,  type:"death", name:"Georges Bizet",         note:"Compositore. Morto nel 1875. «Carmen» è ancora amata in tutto il mondo." },
    { month:4,  day:15, type:"birth", name:"Leonardo da Vinci",     note:"Artista e scienziato italiano. Nato nel 1452. Autore della «Gioconda» e dell'«Ultima Cena», un genio universale." },
    { month:5,  day:2,  type:"death", name:"Leonardo da Vinci",     note:"Genio universale. Morto nel 1519. Lasciò tracce nella pittura, nella scienza e nell'ingegneria." },
    { month:3,  day:6,  type:"birth", name:"Michelangelo",          note:"Artista italiano. Nato nel 1475. Noto per il «David» e per la volta della Cappella Sistina." },
    { month:2,  day:18, type:"death", name:"Michelangelo",          note:"Artista. Morto nel 1564. Un maestro di scultura, pittura e architettura." },
    { month:7,  day:15, type:"birth", name:"Rembrandt",             note:"Pittore olandese. Nato nel 1606. Un maestro di luce e ombra del Secolo d'oro." },
    { month:10, day:4,  type:"death", name:"Rembrandt",             note:"Pittore. Morto nel 1669. Noto anche per i suoi numerosi autoritratti." },
    { month:11, day:12, type:"birth", name:"Auguste Rodin",         note:"Scultore francese. Nato nel 1840. Noto per «Il pensatore» — padre della scultura moderna." },
    { month:11, day:17, type:"death", name:"Auguste Rodin",         note:"Scultore. Morto nel 1917. Rappresentò il corpo umano con grande vitalità." },
    { month:6,  day:25, type:"birth", name:"Antoni Gaudí",          note:"Architetto spagnolo. Nato nel 1852. Progettò la Sagrada Família." },
    { month:6,  day:10, type:"death", name:"Antoni Gaudí",          note:"Architetto. Morto nel 1926. Con edifici originali abbellì Barcellona." },
    { month:12, day:18, type:"birth", name:"Paul Klee",             note:"Pittore nato in Svizzera. Nato nel 1879. Noto per opere poetiche e ricche di colore." },
    { month:6,  day:29, type:"death", name:"Paul Klee",             note:"Pittore. Morto nel 1940. Lasciò quasi 9000 opere." },
    { month:7,  day:10, type:"birth", name:"Nikola Tesla",          note:"Inventore. Nato nel 1856. Contribuì all'uso della corrente alternata." },
    { month:1,  day:7,  type:"death", name:"Nikola Tesla",          note:"Inventore. Morto nel 1943. Pose le basi dell'elettricità moderna." },
    { month:9,  day:22, type:"birth", name:"Michael Faraday",       note:"Scienziato britannico. Nato nel 1791. Scoprì l'induzione elettromagnetica." },
    { month:8,  day:25, type:"death", name:"Michael Faraday",       note:"Scienziato. Morto nel 1867. I suoi studi su elettricità e magnetismo cambiarono il mondo." },
    { month:4,  day:25, type:"birth", name:"Guglielmo Marconi",     note:"Inventore italiano. Nato nel 1874. «Padre della radio», premio Nobel." },
    { month:7,  day:20, type:"death", name:"Guglielmo Marconi",     note:"Inventore. Morto nel 1937. Realizzò la comunicazione senza fili oltre i mari." },
    { month:3,  day:27, type:"birth", name:"Wilhelm Röntgen",       note:"Fisico tedesco. Nato nel 1845. Scoprì i raggi X e ricevette il primo Nobel per la fisica." },
    { month:2,  day:10, type:"death", name:"Wilhelm Röntgen",       note:"Fisico. Morto nel 1923. I suoi raggi sono essenziali per la medicina." },
    { month:2,  day:8,  type:"birth", name:"Jules Verne",           note:"Scrittore francese. Nato nel 1828. «Padre della fantascienza», noto per «Ventimila leghe sotto i mari»." },
    { month:3,  day:24, type:"death", name:"Jules Verne",           note:"Scrittore. Morto nel 1905. Le sue avventure entusiasmano ancora i lettori." },
    { month:12, day:16, type:"birth", name:"Jane Austen",           note:"Romanziera inglese. Nata nel 1775. Nota per «Orgoglio e pregiudizio»." },
    { month:7,  day:18, type:"death", name:"Jane Austen",           note:"Romanziera. Morta nel 1817. Dipinse con finezza la società inglese." },
    { month:4,  day:23, type:"death", name:"William Shakespeare",   note:"Drammaturgo inglese. Morto nel 1616. Scrisse «Amleto» e «Romeo e Giulietta»." },
    { month:10, day:16, type:"birth", name:"Oscar Wilde",           note:"Scrittore irlandese. Nato nel 1854. Noto per «Il principe felice»." },
    { month:11, day:30, type:"death", name:"Oscar Wilde",           note:"Scrittore. Morto nel 1900. Lasciò opere e racconti pieni di spirito." },
    { month:9,  day:15, type:"birth", name:"Agatha Christie",       note:"Scrittrice inglese. Nata nel 1890. «Regina del giallo» e creatrice di Hercule Poirot." },
    { month:1,  day:12, type:"death", name:"Agatha Christie",       note:"Scrittrice. Morta nel 1976. Una delle scrittrici di gialli più lette al mondo." },
    { month:1,  day:4,  type:"birth", name:"Jacob Grimm",           note:"Studioso tedesco. Nato nel 1785. Con il fratello raccolse le «Fiabe dei Grimm»." },
    { month:9,  day:20, type:"death", name:"Jacob Grimm",           note:"Studioso. Morto nel 1863. Importante per la linguistica e lo studio delle fiabe." },
    { month:2,  day:24, type:"birth", name:"Wilhelm Grimm",         note:"Scrittore tedesco. Nato nel 1786. Con il fratello pubblicò le «Fiabe dei Grimm»." },
    { month:12, day:16, type:"death", name:"Wilhelm Grimm",         note:"Scrittore. Morto nel 1859. «Cappuccetto Rosso» e «Biancaneve» vivono ancora oggi." },
    { month:7,  day:20, type:"birth", name:"Gregor Mendel",         note:"Monaco e scienziato austriaco. Nato nel 1822. Scoprì le leggi dell'ereditarietà con i piselli." },
    { month:1,  day:6,  type:"death", name:"Gregor Mendel",         note:"Scienziato. Morto nel 1884. Chiamato il «padre della genetica»." },
    { month:4,  day:20, type:"birth", name:"Joan Miró",             note:"Pittore spagnolo. Nato nel 1893. Noto per quadri gioiosi, cosparsi di segni e stelle." },
    { month:12, day:25, type:"death", name:"Joan Miró",             note:"Pittore. Morto nel 1983. Una grande figura del surrealismo." },
    { month:6,  day:28, type:"birth", name:"Pieter Paul Rubens",    note:"Pittore fiammingo. Nato nel 1577. Un maestro della pittura barocca piena di movimento." },
    { month:5,  day:30, type:"death", name:"Pieter Paul Rubens",    note:"Pittore. Morto nel 1640. Fu anche diplomatico." },
    { month:3,  day:30, type:"birth", name:"Francisco de Goya",     note:"Pittore spagnolo. Nato nel 1746. Pittore di corte dallo sguardo acuto sull'uomo." },
    { month:4,  day:16, type:"death", name:"Francisco de Goya",     note:"Pittore. Morto nel 1828. È considerato un precursore della pittura moderna." },
    { month:1,  day:23, type:"birth", name:"Édouard Manet",         note:"Pittore francese. Nato nel 1832. Con «Colazione sull'erba» aprì la strada all'impressionismo." },
    { month:4,  day:30, type:"death", name:"Édouard Manet",         note:"Pittore. Morto nel 1883. Uno dei padri della pittura moderna." },
    { month:11, day:24, type:"birth", name:"Henri de Toulouse-Lautrec", note:"Pittore francese. Nato nel 1864. Noto per i manifesti dei locali e delle ballerine di Parigi." },
    { month:9,  day:9,  type:"death", name:"Henri de Toulouse-Lautrec", note:"Pittore. Morto nel 1901. Segnò profondamente l'arte del manifesto." },
    { month:7,  day:12, type:"birth", name:"Amedeo Modigliani",     note:"Pittore italiano. Nato nel 1884. Noto per i ritratti dai colli allungati." },
    { month:1,  day:24, type:"death", name:"Amedeo Modigliani",     note:"Pittore. Morto nel 1920. Una figura della «Scuola di Parigi»." },
    { month:3,  day:7,  type:"birth", name:"Maurice Ravel",         note:"Compositore francese. Nato nel 1875. Noto per il «Boléro»." },
    { month:12, day:28, type:"death", name:"Maurice Ravel",         note:"Compositore. Morto nel 1937. Noto per la sua orchestrazione fine e colorata." },
    { month:9,  day:26, type:"birth", name:"George Gershwin",       note:"Compositore americano. Nato nel 1898. Noto per «Rhapsody in Blue»." },
    { month:7,  day:11, type:"death", name:"George Gershwin",       note:"Compositore. Morto nel 1937. Unì la musica classica e il jazz." },
    { month:11, day:6,  type:"birth", name:"John Philip Sousa",     note:"Compositore americano. Nato nel 1854. «Re della marcia», noto per «The Stars and Stripes Forever»." },
    { month:3,  day:6,  type:"death", name:"John Philip Sousa",     note:"Compositore. Morto nel 1932. Lasciò molte celebri marce." },
    { month:6,  day:2,  type:"birth", name:"Edward Elgar",          note:"Compositore inglese. Nato nel 1857. Noto per «Pomp and Circumstance»." },
    { month:2,  day:23, type:"death", name:"Edward Elgar",          note:"Compositore. Morto nel 1934. Una figura di spicco della musica inglese." },
    { month:1,  day:27, type:"birth", name:"Lewis Carroll",         note:"Scrittore e matematico inglese. Nato nel 1832. Noto per «Alice nel Paese delle Meraviglie»." },
    { month:1,  day:14, type:"death", name:"Lewis Carroll",         note:"Scrittore. Morto nel 1898. Fu anche matematico e fotografo." },
    { month:5,  day:22, type:"birth", name:"Arthur Conan Doyle",    note:"Scrittore britannico. Nato nel 1859. Creatore del detective Sherlock Holmes." },
    { month:7,  day:7,  type:"death", name:"Arthur Conan Doyle",    note:"Scrittore. Morto nel 1930. Era anche medico." },
    /* ---- Lotto 3 ---- */
    { month:2,  day:18, type:"birth", name:"Alessandro Volta",      note:"Fisico italiano. Nato nel 1745. Inventò la pila; l'unità volt prende nome da lui." },
    { month:3,  day:5,  type:"death", name:"Alessandro Volta",      note:"Fisico. Morto nel 1827. Un pioniere dello studio dell'elettricità." },
    { month:1,  day:20, type:"birth", name:"André-Marie Ampère",    note:"Fisico francese. Nato nel 1775. Noto per gli studi sulla corrente; l'unità ampere prende nome da lui." },
    { month:6,  day:10, type:"death", name:"André-Marie Ampère",    note:"Fisico. Morto nel 1836. Fondò l'elettrodinamica." },
    { month:3,  day:16, type:"birth", name:"Georg Ohm",             note:"Fisico tedesco. Nato nel 1789. Noto per la «legge di Ohm» sulla resistenza elettrica." },
    { month:7,  day:6,  type:"death", name:"Georg Ohm",             note:"Fisico. Morto nel 1854. L'unità ohm prende nome da lui." },
    { month:10, day:7,  type:"birth", name:"Niels Bohr",            note:"Fisico danese. Nato nel 1885. Spiegò la struttura dell'atomo e ricevette il Nobel." },
    { month:11, day:18, type:"death", name:"Niels Bohr",            note:"Fisico. Morto nel 1962. Uno dei più grandi fisici del XX secolo." },
    { month:4,  day:23, type:"birth", name:"Max Planck",            note:"Fisico tedesco. Nato nel 1858. Fondatore della teoria dei quanti e premio Nobel." },
    { month:10, day:4,  type:"death", name:"Max Planck",            note:"Fisico. Morto nel 1947. Pose le basi della fisica moderna." },
    { month:1,  day:19, type:"birth", name:"Edgar Allan Poe",       note:"Scrittore americano. Nato nel 1809. Precursore del romanzo giallo e maestro del fantastico." },
    { month:10, day:7,  type:"death", name:"Edgar Allan Poe",       note:"Scrittore. Morto nel 1849. Noto anche come poeta e critico." },
    { month:8,  day:1,  type:"birth", name:"Herman Melville",       note:"Scrittore americano. Nato nel 1819. Noto per «Moby Dick»." },
    { month:9,  day:28, type:"death", name:"Herman Melville",       note:"Scrittore. Morto nel 1891. «Moby Dick» fu apprezzato molto più tardi." },
    { month:4,  day:21, type:"birth", name:"Charlotte Brontë",      note:"Scrittrice inglese. Nata nel 1816. Nota per «Jane Eyre»." },
    { month:3,  day:31, type:"death", name:"Charlotte Brontë",      note:"Scrittrice. Morta nel 1855. La maggiore delle tre sorelle Brontë." },
    { month:11, day:13, type:"birth", name:"Robert Louis Stevenson", note:"Scrittore britannico. Nato nel 1850. Noto per «L'isola del tesoro» e «Lo strano caso del dottor Jekyll»." },
    { month:12, day:3,  type:"death", name:"Robert Louis Stevenson", note:"Scrittore. Morto nel 1894. Trascorse gli ultimi anni alle Samoa, nel Pacifico." },
    { month:5,  day:20, type:"birth", name:"Honoré de Balzac",      note:"Scrittore francese. Nato nel 1799. Noto per il ciclo «La Commedia umana»." },
    { month:8,  day:18, type:"death", name:"Honoré de Balzac",      note:"Scrittore. Morto nel 1850. Dipinse l'uomo e la società con acume." },
    { month:7,  day:24, type:"birth", name:"Alexandre Dumas",       note:"Scrittore francese. Nato nel 1802. Noto per «I tre moschettieri» e «Il conte di Montecristo»." },
    { month:12, day:5,  type:"death", name:"Alexandre Dumas",       note:"Scrittore. Morto nel 1870. I suoi romanzi d'avventura sono amati in tutto il mondo." },
    { month:4,  day:2,  type:"birth", name:"Émile Zola",            note:"Scrittore francese. Nato nel 1840. Una grande figura del romanzo naturalista." },
    { month:9,  day:29, type:"death", name:"Émile Zola",            note:"Scrittore. Morto nel 1902. Noto anche per l'articolo «J'accuse»." },
    { month:12, day:30, type:"birth", name:"Rudyard Kipling",       note:"Scrittore britannico. Nato nel 1865. Noto per «Il libro della giungla»." },
    { month:1,  day:18, type:"death", name:"Rudyard Kipling",       note:"Scrittore. Morto nel 1936. Stimato anche come poeta e narratore." },
    { month:1,  day:12, type:"birth", name:"Jack London",           note:"Scrittore americano. Nato nel 1876. Noto per «Il richiamo della foresta» e «Zanna Bianca»." },
    { month:11, day:22, type:"death", name:"Jack London",           note:"Scrittore. Morto nel 1916. Condusse una vita movimentata e avventurosa." },
    { month:5,  day:7,  type:"birth", name:"Rabindranath Tagore",   note:"Poeta indiano. Nato nel 1861. Primo asiatico a ricevere il Nobel per la letteratura." },
    { month:8,  day:7,  type:"death", name:"Rabindranath Tagore",   note:"Poeta. Morto nel 1941. Scrisse gli inni nazionali di India e Bangladesh." },
    { month:9,  day:4,  type:"birth", name:"Anton Bruckner",        note:"Compositore austriaco. Nato nel 1824. Noto per le sue grandiose sinfonie e opere sacre." },
    { month:10, day:11, type:"death", name:"Anton Bruckner",        note:"Compositore. Morto nel 1896. Stimato anche come organista." },
    { month:6,  day:20, type:"birth", name:"Jacques Offenbach",     note:"Compositore francese. Nato nel 1819. Rallegrò il pubblico con le sue operette." },
    { month:10, day:5,  type:"death", name:"Jacques Offenbach",     note:"Compositore. Morto nel 1880. Noto per «Orfeo all'inferno»." },
    { month:5,  day:12, type:"birth", name:"Gabriel Fauré",         note:"Compositore francese. Nato nel 1845. Noto per il suo «Requiem» e la «Siciliana»." },
    { month:11, day:4,  type:"death", name:"Gabriel Fauré",         note:"Compositore. Morto nel 1924. Una figura di spicco della musica francese moderna." },
    { month:10, day:27, type:"birth", name:"Niccolò Paganini",      note:"Musicista italiano. Nato nel 1782. Un violinista leggendario di virtuosismo straordinario." },
    { month:5,  day:27, type:"death", name:"Niccolò Paganini",      note:"Musicista. Morto nel 1840. Noto per i «24 Capricci»." },
    { month:12, day:2,  type:"birth", name:"Georges Seurat",        note:"Pittore francese. Nato nel 1859. Sviluppò il puntinismo, la pittura per piccoli punti." },
    { month:3,  day:29, type:"death", name:"Georges Seurat",        note:"Pittore. Morto nel 1891 a 31 anni. Noto per «Una domenica pomeriggio all'isola della Grande-Jatte»." },
    { month:7,  day:10, type:"birth", name:"Camille Pissarro",      note:"Pittore francese. Nato nel 1830. Il più anziano e fedele degli impressionisti." },
    { month:11, day:13, type:"death", name:"Camille Pissarro",      note:"Pittore. Morto nel 1903. L'unico ad aver partecipato a tutte le mostre impressioniste." },
    { month:2,  day:19, type:"birth", name:"Niccolò Copernico",     note:"Astronomo polacco. Nato nel 1473. Propose il sistema eliocentrico." },
    { month:5,  day:24, type:"death", name:"Niccolò Copernico",     note:"Astronomo. Morto nel 1543. Cambiò profondamente la visione del mondo." },
    { month:12, day:27, type:"birth", name:"Keplero",               note:"Astronomo tedesco. Nato nel 1571. Scoprì le leggi del moto dei pianeti." },
    { month:11, day:15, type:"death", name:"Keplero",               note:"Astronomo. Morto nel 1630. Uno dei fondatori dell'astronomia moderna." },
    { month:6,  day:13, type:"birth", name:"James Clerk Maxwell",   note:"Fisico britannico. Nato nel 1831. Unificò elettricità e magnetismo e mostrò che la luce è un'onda elettromagnetica." },
    { month:11, day:5,  type:"death", name:"James Clerk Maxwell",   note:"Fisico. Morto nel 1879. È citato accanto a Newton ed Einstein." },
    { month:4,  day:27, type:"birth", name:"Samuel Morse",          note:"Inventore americano. Nato nel 1791. Creò il telegrafo e l'«alfabeto Morse»." },
    { month:4,  day:2,  type:"death", name:"Samuel Morse",          note:"Inventore. Morto nel 1872. In origine era anche pittore." },
    { month:12, day:12, type:"birth", name:"Gustave Flaubert",      note:"Scrittore francese. Nato nel 1821. Noto per «Madame Bovary»." },
    { month:5,  day:8,  type:"death", name:"Gustave Flaubert",      note:"Scrittore. Morto nel 1880. Celebre per il suo stile cesellato all'estremo." },
    { month:8,  day:5,  type:"birth", name:"Guy de Maupassant",     note:"Scrittore francese. Nato nel 1850. Noto per «La collana» e «Una vita»." },
    { month:7,  day:6,  type:"death", name:"Guy de Maupassant",     note:"Scrittore. Morto nel 1893. Un maestro della novella moderna." },
    { month:11, day:29, type:"birth", name:"Gaetano Donizetti",     note:"Compositore italiano. Nato nel 1797. Noto per opere belcantistiche come «L'elisir d'amore»." },
    { month:4,  day:8,  type:"death", name:"Gaetano Donizetti",     note:"Compositore. Morto nel 1848. Lasciò oltre 70 opere." },
    { month:11, day:3,  type:"birth", name:"Vincenzo Bellini",      note:"Compositore italiano. Nato nel 1801. Noto per opere dalle belle melodie come «Norma»." },
    { month:9,  day:23, type:"death", name:"Vincenzo Bellini",      note:"Compositore. Morto nel 1835 a soli 33 anni. Una figura del belcanto." },
    { month:6,  day:5,  type:"death", name:"Carl Maria von Weber",  note:"Compositore tedesco. Morto nel 1826. Con l'opera «Il franco cacciatore» aprì l'opera romantica tedesca." },
    { month:6,  day:17, type:"birth", name:"M. C. Escher",          note:"Incisore olandese. Nato nel 1898. Noto per immagini enigmatiche, come illusioni ottiche." },
    { month:3,  day:27, type:"death", name:"M. C. Escher",          note:"Incisore. Morto nel 1972. Le sue opere d'ispirazione matematica stupirono il mondo." },
    { month:7,  day:22, type:"birth", name:"Edward Hopper",         note:"Pittore americano. Nato nel 1882. Noto per «Nighthawks», che mostra il silenzio della città." },
    { month:5,  day:15, type:"death", name:"Edward Hopper",         note:"Pittore. Morto nel 1967. Un grande pittore realista del XX secolo." },
    { month:2,  day:3,  type:"birth", name:"Norman Rockwell",       note:"Pittore americano. Nato nel 1894. Amato per le calde scene di vita quotidiana sulle copertine dei giornali." },
    { month:11, day:8,  type:"death", name:"Norman Rockwell",       note:"Pittore e illustratore. Morto nel 1978. Dipinse la vita americana." },
    { month:12, day:11, type:"birth", name:"Robert Koch",           note:"Batteriologo tedesco. Nato nel 1843. Scoprì i batteri della tubercolosi e del colera; premio Nobel." },
    { month:5,  day:27, type:"death", name:"Robert Koch",           note:"Batteriologo. Morto nel 1910. Un padre della batteriologia moderna." },
    { month:11, day:25, type:"birth", name:"Carl Benz",             note:"Ingegnere tedesco. Nato nel 1844. Costruì la prima automobile a benzina pratica." },
    { month:4,  day:4,  type:"death", name:"Carl Benz",             note:"Ingegnere. Morto nel 1929. Chiamato il «padre dell'automobile»." },
    { month:7,  day:30, type:"birth", name:"Henry Ford",            note:"Imprenditore americano. Nato nel 1863. Rese l'automobile accessibile con la produzione di massa." },
    { month:4,  day:7,  type:"death", name:"Henry Ford",            note:"Imprenditore. Morto nel 1947. Fondatore della Ford Motor Company." },
    { month:11, day:30, type:"birth", name:"Jonathan Swift",        note:"Scrittore irlandese. Nato nel 1667. Noto per «I viaggi di Gulliver»." },
    { month:10, day:19, type:"death", name:"Jonathan Swift",        note:"Scrittore. Morto nel 1745. Un maestro della letteratura satirica." },
    { month:2,  day:27, type:"birth", name:"John Steinbeck",        note:"Scrittore americano. Nato nel 1902. Ricevette il Nobel per «Furore»." },
    { month:12, day:20, type:"death", name:"John Steinbeck",        note:"Scrittore. Morto nel 1968. Dipinse con forza la vita della gente comune." },
    { month:9,  day:24, type:"birth", name:"F. Scott Fitzgerald",   note:"Scrittore americano. Nato nel 1896. Noto per «Il grande Gatsby»." },
    { month:12, day:21, type:"death", name:"F. Scott Fitzgerald",   note:"Scrittore. Morto nel 1940. Dipinse con vivezza l'America degli anni Venti." },
    { month:5,  day:17, type:"birth", name:"Erik Satie",            note:"Compositore francese. Nato nel 1866. Noto per le «Gymnopédies», dallo stile molto personale." },
    { month:7,  day:1,  type:"death", name:"Erik Satie",            note:"Compositore. Morto nel 1925. Influenzò molto la musica successiva." },
    { month:6,  day:9,  type:"birth", name:"Cole Porter",           note:"Compositore americano. Nato nel 1891. Scrisse canzoni per musical piene di eleganza e spirito." },
    { month:10, day:15, type:"death", name:"Cole Porter",           note:"Compositore. Morto nel 1964. Noto per «Night and Day»." },
    { month:3,  day:7,  type:"birth", name:"Piet Mondrian",         note:"Pittore olandese. Nato nel 1872. Noto per quadri astratti di rosso, blu, giallo e linee nere." },
    { month:2,  day:1,  type:"death", name:"Piet Mondrian",         note:"Pittore. Morto nel 1944. Un pioniere dell'arte astratta del XX secolo." },
    { month:11, day:15, type:"birth", name:"Georgia O'Keeffe",      note:"Pittrice americana. Nata nel 1887. «Madre dell'arte moderna americana», nota per grandi fiori e paesaggi desertici." },
    { month:3,  day:6,  type:"death", name:"Georgia O'Keeffe",      note:"Pittrice. Morta nel 1986 a 98 anni. Seguì una strada tutta sua." },
    { month:8,  day:6,  type:"birth", name:"Andy Warhol",           note:"Artista americano. Nato nel 1928. Noto per la pop art, con lattine e star." },
    { month:2,  day:22, type:"death", name:"Andy Warhol",           note:"Artista. Morto nel 1987. Una figura dell'arte della seconda metà del XX secolo." }
  ]
};
