/*
 * Soyogi (Elder Edition) — content.en.js
 * English (Western/US-leaning) conversation content. Expanded 2026-07-06 to
 * match the Japanese depth (staff should never run out of material):
 * quizzes 38 / either-or 24 / on-this-day 14 (verified history + year:null customs)
 * / flowers 24 (two per month) / color 6.
 * ============================================================================
 * ★NOT a translation of content.ja.js — re-authored around Western elders'
 *   memories. Schema in content.ja.js. Historical dates are well-established;
 *   annual customs use year:null. Expand with fact-checking.
 * ============================================================================
 */
window.SOYOGI_WS_CONTENT = window.SOYOGI_WS_CONTENT || {};
window.SOYOGI_WS_CONTENT["en"] = {

  /* ---- Tab 1: flower of the day (two per month; positive meanings) ---- */
  flowers: [
    { month:1,  name:"Carnation",          emoji:"💐", photo:null, meaning:"Love & admiration", note:"A hardy winter bloom that brightens the coldest month." },
    { month:1,  name:"Snowdrop",           emoji:"🌼", photo:null, meaning:"Hope", note:"Peeks bravely through the snow in midwinter." },
    { month:2,  name:"Violet",             emoji:"🌸", photo:null, meaning:"Faithfulness & modesty", note:"A small, sweet flower of early spring." },
    { month:2,  name:"Primrose",           emoji:"🌸", photo:null, meaning:"Young love", note:"One of the first pale blooms of the year." },
    { month:3,  name:"Daffodil",           emoji:"🌼", photo:null, meaning:"New beginnings", note:"Announces that spring has arrived." },
    { month:3,  name:"Crocus",             emoji:"🌷", photo:null, meaning:"Cheerfulness", note:"Bright cups that open in the first warm sun." },
    { month:4,  name:"Daisy",              emoji:"🌼", photo:null, meaning:"Innocence & cheer", note:"A simple, happy flower loved in fields and bouquets." },
    { month:4,  name:"Sweet Pea",          emoji:"🌸", photo:null, meaning:"Blissful pleasure", note:"Delicate, fragrant blooms on climbing vines." },
    { month:5,  name:"Lily of the Valley", emoji:"🌷", photo:null, meaning:"Return of happiness", note:"Tiny white bells with a lovely fragrance." },
    { month:5,  name:"Tulip",              emoji:"🌷", photo:null, meaning:"Perfect love", note:"Brings bold color to spring gardens." },
    { month:6,  name:"Rose",               emoji:"🌹", photo:null, meaning:"Love & gratitude", note:"The classic flower of June weddings." },
    { month:6,  name:"Peony",              emoji:"🌸", photo:null, meaning:"A happy life", note:"Full, lush blooms of early summer." },
    { month:7,  name:"Water Lily",         emoji:"🌸", photo:null, meaning:"Purity & peace", note:"Floating calmly on summer ponds." },
    { month:7,  name:"Larkspur",           emoji:"🌸", photo:null, meaning:"Open heart", note:"Tall spires of summer color." },
    { month:8,  name:"Sunflower",          emoji:"🌻", photo:null, meaning:"Adoration & warmth", note:"Turns to follow the summer sun." },
    { month:8,  name:"Gladiolus",          emoji:"🌷", photo:null, meaning:"Strength of character", note:"Tall, striking spikes of late summer." },
    { month:9,  name:"Aster",              emoji:"🌸", photo:null, meaning:"Wisdom & patience", note:"Star-shaped blooms carrying summer into fall." },
    { month:9,  name:"Morning Glory",      emoji:"🌺", photo:null, meaning:"Affection", note:"Opens fresh with each summer morning." },
    { month:10, name:"Marigold",           emoji:"🌼", photo:null, meaning:"Warmth & creativity", note:"Golden autumn color through the cooling days." },
    { month:10, name:"Cosmos",             emoji:"🌸", photo:null, meaning:"Harmony", note:"Sways gently in the autumn breeze." },
    { month:11, name:"Chrysanthemum",      emoji:"🌼", photo:null, meaning:"Friendship & joy", note:"A cheerful, long-lasting flower of late autumn." },
    { month:11, name:"Dahlia",             emoji:"🌸", photo:null, meaning:"Dignity & grace", note:"Blooms generously until the first frost." },
    { month:12, name:"Narcissus",          emoji:"🌼", photo:null, meaning:"Good wishes & hope", note:"A bright bloom to close the year with hope." },
    { month:12, name:"Poinsettia",         emoji:"🌺", photo:null, meaning:"Good cheer", note:"The red and green of the holiday season." }
  ],

  /* ---- Tab 1: on this day (verified history + year:null annual customs) ---- */
  onThisDay: [
    { month:1,  day:1,  year:null, text:"Today is New Year's Day — a fresh start to the year.", emoji:"🎉" },
    { month:2,  day:9,  year:1964, text:"The Beatles made their U.S. debut on The Ed Sullivan Show.", emoji:"🎸" },
    { month:2,  day:14, year:null, text:"Today is Valentine's Day — a day for sweethearts and kind words.", emoji:"💝" },
    { month:3,  day:17, year:null, text:"Today is St. Patrick's Day — a day of green, parades, and good cheer.", emoji:"☘️" },
    { month:4,  day:12, year:1961, text:"Yuri Gagarin became the first human to travel into space.", emoji:"🚀" },
    { month:5,  day:29, year:1953, text:"Edmund Hillary and Tenzing Norgay reached the summit of Mount Everest.", emoji:"🏔️" },
    { month:7,  day:4,  year:null, text:"Today is Independence Day — fireworks, parades, and summer picnics.", emoji:"🎆" },
    { month:7,  day:17, year:1955, text:"Disneyland opened its gates in California.", emoji:"🏰" },
    { month:7,  day:20, year:1969, text:"Apollo 11 landed and humans walked on the Moon for the first time.", emoji:"🌕" },
    { month:8,  day:15, year:1969, text:"The Woodstock music festival began.", emoji:"🎶" },
    { month:10, day:4,  year:1957, text:"Sputnik 1, the first artificial satellite, was launched.", emoji:"🛰️" },
    { month:10, day:31, year:null, text:"Today is Halloween — costumes, jack-o'-lanterns, and trick-or-treating.", emoji:"🎃" },
    { month:12, day:25, year:null, text:"Today is Christmas — a time of family, gifts, and good will.", emoji:"🎄" },
    { month:12, day:31, year:null, text:"Today is New Year's Eve — counting down to a brand-new year.", emoji:"🎆" }
  ],

  /* ---- Tab 2: reminiscence quizzes (38) — trivia + structured staff cue ---- */
  quizzes: [
    /* warm-up */
    { id:"en-warmup-01", genre:"warmup", emoji:"🍉", photo:null,
      question:"Which is bigger and heavier — a watermelon or an apple?", choices:["Watermelon","Apple"], answerIndex:0,
      trivia:"A big watermelon can weigh over 20 pounds — a summer picnic favorite for generations.",
      cue:{ open:"\"That one was easy!\" — with a smile, then turn to summer memories.",
        asks:["Did your family have watermelon in the summer?","Any picnics or trips to the lake you remember?","Who did you spend those summer days with?"],
        expand:"Let them enjoy the moment more than the 'right' answer. A small memory of your own (\"my family always…\") helps them open up.",
        care:"Never mind if they hesitate — \"they're both delicious!\" keeps it warm. A smile is the real goal." } },
    { id:"en-warmup-02", genre:"warmup", emoji:"🍡", photo:null,
      question:"Which is softer — a marshmallow or a cracker?", choices:["Marshmallow","Cracker"], answerIndex:0,
      trivia:"Roasting marshmallows over a fire is a memory many people share.",
      cue:{ open:"\"Marshmallows, of course — nice and soft.\" Then head toward campfire memories.",
        asks:["Did you ever go camping or sit around a bonfire?","Who taught you to roast marshmallows?","What did family gatherings look like for you?"],
        expand:"Food and firelight are strong sensory memories. Asking about smells and sounds brings the scene to life.",
        care:"If eating is a sensitive subject, keep it about the memory, not the food itself." } },
    { id:"en-warmup-03", genre:"warmup", emoji:"🥔", photo:null,
      question:"Which weighs more — a sack of potatoes or a feather?", choices:["A sack of potatoes","A feather"], answerIndex:0,
      trivia:"A sack of potatoes adds up to many pounds. The humble potato fed families through hard times.",
      cue:{ open:"\"The potatoes, of course — they're heavy!\" Then move to home cooking.",
        asks:["Did your family grow a vegetable garden?","What was your favorite meal as a child?","Who did the cooking at home?"],
        expand:"Food memories are vivid. Ask about Sunday dinners and kitchen smells to bring the scene back.",
        care:"If food is a tender subject, stay with the memory rather than the food itself." } },
    { id:"en-warmup-04", genre:"warmup", emoji:"🏖️", photo:null,
      question:"Which is bigger — a beach ball or a baseball?", choices:["Beach ball","Baseball"], answerIndex:0,
      trivia:"Beach balls meant summer at the shore — sand, sun, and cool water.",
      cue:{ open:"\"The beach ball, of course!\" Then turn to summer at the shore.",
        asks:["Did you go to the beach or a lake in summer?","Who did you go with?","What did you like to do there?"],
        expand:"Summer-outing memories come with people and places. Follow whoever they mention.",
        care:"If travel wasn't possible for them, ask how they liked to cool off close to home." } },
    { id:"en-warmup-05", genre:"warmup", emoji:"🍭", photo:null,
      question:"Which is sweeter — a lollipop or a lemon?", choices:["Lollipop","Lemon"], answerIndex:0,
      trivia:"A lollipop was a small, happy reward — often from the barber, doctor, or corner store.",
      cue:{ open:"\"The lollipop, naturally!\" Then move to childhood treats.",
        asks:["What was your favorite candy as a child?","Was there a corner store nearby?","Who used to give you a little treat?"],
        expand:"Childhood-treat memories are cheerful and easy to tell. Names of shops and people make them vivid.",
        care:"For those who grew up with little, keep a tone of shared delight, never comparison." } },

    /* prices */
    { id:"en-price-01", genre:"price", emoji:"🥤", photo:null,
      question:"In the 1950s, about how much did a bottle of Coca-Cola from a machine cost?", choices:["A nickel (5 cents)","A quarter (25 cents)","A dollar"], answerIndex:0,
      trivia:"The 'nickel Coke' held its price for decades — a small everyday treat.",
      cue:{ open:"\"A nickel! Hard to imagine now, isn't it?\"",
        asks:["What was your favorite treat as a child?","Was there a soda fountain or corner store nearby?","How did you earn or save your pocket money?"],
        expand:"Prices open the door to everyday life back then — chores, first jobs, small joys.",
        care:"Some grew up with very little. Keep the tone one of shared wonder, never comparison." } },
    { id:"en-price-02", genre:"price", emoji:"📮", photo:null,
      question:"In the 1950s, about how much did it cost to mail a first-class letter in the U.S.?", choices:["3 cents","30 cents","A dollar"], answerIndex:0,
      trivia:"A first-class stamp was 3 cents for many years. Letters kept far-off family close.",
      cue:{ open:"\"Three cents to send a letter — those were the days.\"",
        asks:["Did you write letters often? To whom?","Did you have a pen pal?","Do you remember waiting for a special letter?"],
        expand:"Letters are memories of the people we loved. Follow whoever they wrote to.",
        care:"If a letter memory brings up someone they've lost, slow down and listen gently." } },
    { id:"en-price-03", genre:"price", emoji:"🍬", photo:null,
      question:"At the corner store, small candies were famously sold for how much each?", choices:["A penny","A dollar","A quarter"], answerIndex:0,
      trivia:"'Penny candy' filled the jars at the corner store — a whole handful for just a few coins.",
      cue:{ open:"\"Penny candy — remember picking it out of the jars?\"",
        asks:["What did you always choose?","Was there a shop you loved to visit?","Did you save your pennies for something special?"],
        expand:"The corner store is a warm, easy memory tied to friends and neighborhood.",
        care:"Keep it light and shared; never dwell on who had more or less." } },

    /* appliances */
    { id:"en-appliance-01", genre:"appliance", emoji:"📺", photo:null,
      question:"Before remote controls, how did people change the TV channel?", choices:["Got up and turned a dial by hand","Clapped their hands","Whistled at the set"], answerIndex:0,
      trivia:"Someone — often the youngest — had to walk over and turn the knob!",
      cue:{ open:"\"Someone always had to get up and turn the knob!\" — say it with a smile.",
        asks:["What shows did your family gather around to watch?","Who usually controlled the TV?","Do you remember the first television in your home?"],
        expand:"The 'first TV' is a happy memory tied to the whole family. Ask who was in the room.",
        care:"Not every home had a set early on. Ask \"do you remember when TV arrived?\" rather than assuming." } },
    { id:"en-appliance-02", genre:"appliance", emoji:"🥛", photo:null,
      question:"Who delivered fresh milk to the doorstep each morning?", choices:["The milkman","The mailman","The fireman"], answerIndex:0,
      trivia:"Glass bottles left on the step, swapped for empties — the milkman was part of daily life.",
      cue:{ open:"\"The milkman — bottles clinking on the step at dawn.\"",
        asks:["Did the milkman come to your home?","What else was delivered — bread, ice, the newspaper?","Do you remember the neighborhood you grew up in?"],
        expand:"Doorstep-delivery memories bring back the whole neighborhood and its rhythms.",
        care:"Let them lead to the people and places they remember most fondly." } },
    { id:"en-appliance-03", genre:"appliance", emoji:"🧊", photo:null,
      question:"Before electric refrigerators were common, food was kept cold in a what?", choices:["An icebox","A microwave","A toaster"], answerIndex:0,
      trivia:"An 'iceman' delivered blocks of ice for the icebox that kept food cool.",
      cue:{ open:"\"The old icebox — and the iceman with his big blocks of ice.\"",
        asks:["Do you remember the iceman coming around?","How did you keep food fresh in summer?","Did your family make ice cream by hand?"],
        expand:"'Before it was easy' memories lead to the clever ways people managed day to day.",
        care:"People valued not wasting food. Receive that thriftiness warmly." } },
    { id:"en-appliance-04", genre:"appliance", emoji:"☎️", photo:null,
      question:"What was the telephone called that you dialed by spinning a numbered wheel?", choices:["A rotary phone","A cell phone","A smart phone"], answerIndex:0,
      trivia:"The whir of the rotary dial — and often a 'party line' shared with the neighbors.",
      cue:{ open:"\"That whir of the rotary dial — remember it?\"",
        asks:["Do you remember your first telephone at home?","Did you share a 'party line' with neighbors?","Who did you love to call?"],
        expand:"The telephone is a memory of staying close to loved ones. Ask who they called most.",
        care:"If reaching people was hard back then, be gentle with any loneliness that surfaces." } },
    { id:"en-appliance-05", genre:"appliance", emoji:"🎵", photo:null,
      question:"Records were played by lowering a needle onto them, on a what?", choices:["A record player","A radio","A typewriter"], answerIndex:0,
      trivia:"Drop the needle and the music played — families gathered around the living-room set.",
      cue:{ open:"\"Drop the needle and there's the music — lovely, wasn't it?\"",
        asks:["Who were your favorite singers or bands?","What music did your family play at home?","Is there a song that still means a lot to you?"],
        expand:"Music is tied tightly to feeling. If a song comes up, hum a little of it together.",
        care:"A treasured song may carry sadness too. Watch their face and follow gently." } },
    { id:"en-appliance-06", genre:"appliance", emoji:"🧺", photo:null,
      question:"Old washing machines had two rollers to squeeze water from the clothes. What was that called?", choices:["A wringer","A dryer","A freezer"], answerIndex:0,
      trivia:"You fed the wet laundry between the rollers of the 'wringer washer' by hand — careful of fingers!",
      cue:{ open:"\"Laundry was hard work back then, wasn't it?\" — start with a bit of appreciation.",
        asks:["How did you do the washing before machines were common?","What was the hardest household chore?","Do you remember hanging laundry out to dry?"],
        expand:"Hearing 'it got easier / it was hard work' opens up the whole story of a life well lived.",
        care:"Meet stories of hard work with \"you worked so hard\" before anything else." } },
    { id:"en-appliance-07", genre:"appliance", emoji:"☕", photo:null,
      question:"On the stove, coffee was brewed in a bubbling pot called a what?", choices:["A percolator","A toaster","A blender"], answerIndex:0,
      trivia:"The percolator bubbled and gurgled on the stove — its smell meant morning had come.",
      cue:{ open:"\"That percolator bubbling away — you can almost smell it.\"",
        asks:["How did your family make coffee?","What did mornings look like at your house?","Did you gather for coffee with neighbors or family?"],
        expand:"Morning-routine memories bring back the whole household and its comforts.",
        care:"Keep it about the ritual and the people, not whether they still drink coffee." } },

    /* snacks */
    { id:"en-snack-01", genre:"snack", emoji:"🍦", photo:null,
      question:"What frozen treat was sold from a truck playing music down the street?", choices:["Ice cream","Popcorn","Pretzels"], answerIndex:0,
      trivia:"The ice cream truck's jingle sent children running with coins in hand.",
      cue:{ open:"\"That ice cream truck jingle — off you'd run!\"",
        asks:["Did you chase the ice cream truck as a child?","What flavor did you always pick?","Who did you play with on your street?"],
        expand:"The sound and the rush are a joyful, easy memory tied to childhood friends.",
        care:"Keep it about the fun; go at the person's pace." } },
    { id:"en-snack-02", genre:"snack", emoji:"🍭", photo:null,
      question:"What fluffy fair treat is spun from sugar?", choices:["Cotton candy","Caramel","Taffy"], answerIndex:0,
      trivia:"Spun sugar on a paper cone — the sweet, sticky joy of the fair and the carnival.",
      cue:{ open:"\"Cotton candy — sticky fingers and all!\"",
        asks:["Did you go to the fair or the carnival?","What did you love to do there?","Who took you, or who did you go with?"],
        expand:"Fair memories bring back family outings, rides, and games. Follow the excitement.",
        care:"If they couldn't go often, ask what treats they enjoyed closer to home." } },
    { id:"en-snack-03", genre:"snack", emoji:"🍬", photo:null,
      question:"What chewy candy, pulled and stretched, was famous at the seaside?", choices:["Saltwater taffy","Chocolate","Licorice"], answerIndex:0,
      trivia:"Saltwater taffy in bright wrappers was the taste of a trip to the shore.",
      cue:{ open:"\"Saltwater taffy — a taste of the boardwalk.\"",
        asks:["Did you take trips to the seaside?","What do you remember about the boardwalk or pier?","Who did you go with?"],
        expand:"Seaside memories are full of sights, sounds, and family. Let them paint the scene.",
        care:"If seaside trips weren't part of life, pivot gently to a favorite summer place." } },
    { id:"en-snack-04", genre:"snack", emoji:"🥤", photo:null,
      question:"At the soda fountain, ice cream dropped into soda made a tall drink called a what?", choices:["A float","A sandwich","A pie"], answerIndex:0,
      trivia:"A root beer float at the soda fountain — a favorite spot for a treat with friends.",
      cue:{ open:"\"A root beer float at the soda fountain — remember those?\"",
        asks:["Did you have a favorite soda fountain or diner?","Who did you go with after school?","What did you like to order?"],
        expand:"The soda fountain is a warm memory of youth and friendship. Ask who they went with.",
        care:"Keep it light and social; follow the friends and places they mention." } },
    { id:"en-snack-05", genre:"snack", emoji:"🔥", photo:null,
      question:"Roasted marshmallow and chocolate between graham crackers make a what?", choices:["A s'more","A pancake","A donut"], answerIndex:0,
      trivia:"S'mores by the campfire — a gooey treat that meant summer nights outdoors.",
      cue:{ open:"\"S'mores by the fire — 'some more,' please!\"",
        asks:["Did you go camping or sit around a fire?","What did evenings outdoors look like?","Who was there with you?"],
        expand:"Campfire memories bring back family, friends, and the outdoors. Follow the warmth.",
        care:"If camping wasn't part of life, ask about summer evenings at home instead." } },
    { id:"en-snack-06", genre:"snack", emoji:"🎈", photo:null,
      question:"What candy could you chew and blow into bubbles?", choices:["Bubble gum","A cracker","A pickle"], answerIndex:0,
      trivia:"Blowing the biggest bubble was a small childhood triumph — and a sticky pop!",
      cue:{ open:"\"Could you blow a big bubble with bubble gum?\"",
        asks:["What sweets did you love as a child?","Did you have contests with friends?","Was there a shop where you spent your pennies?"],
        expand:"Small childhood contests spark laughter and easy stories among friends.",
        care:"A light, playful topic — enjoy the smiles it brings." } },

    /* tools */
    { id:"en-tool-01", genre:"tool", emoji:"⌨️", photo:null,
      question:"Before computers, which office machine struck ink onto paper?", choices:["A typewriter","A cash register","A sewing machine"], answerIndex:0,
      trivia:"The clack of typewriter keys and the 'ding' at the end of a line were everyday office sounds.",
      cue:{ open:"\"That clack-clack — and the little bell at the end of the line!\"",
        asks:["What kind of work did you do?","What tools or machines did you use every day?","What were you especially good at in your job?"],
        expand:"Talking about work and skill supports a person's pride. \"You must have been quick!\" goes far.",
        care:"If someone didn't work outside the home, ask about the skills they used at home." } },
    { id:"en-tool-02", genre:"tool", emoji:"📝", photo:null,
      question:"Before copy machines, how did offices make a second copy of a letter?", choices:["Carbon paper","A camera","A stapler"], answerIndex:0,
      trivia:"A sheet of carbon paper underneath copied every word onto the page below.",
      cue:{ open:"\"Carbon paper — and inky fingertips!\"",
        asks:["What kind of work did you do?","What was a typical day at work like?","What were you proud of in your work?"],
        expand:"Work-tool memories connect to pride in a working life. Honor the effort.",
        care:"For homemakers, ask about the skills and routines they ran at home." } },
    { id:"en-tool-03", genre:"tool", emoji:"🌾", photo:null,
      question:"By hand, farmers once cut wheat and grass with a curved blade called a what?", choices:["A scythe","A hammer","A spoon"], answerIndex:0,
      trivia:"Swinging a scythe through the fields was hard, rhythmic work at harvest time.",
      cue:{ open:"\"Harvest was hard work in those days, wasn't it?\"",
        asks:["Did your family farm or keep a garden?","What was harvest time like?","What did you enjoy about working the land?"],
        expand:"Land and harvest memories bring back the seasons and family teamwork.",
        care:"If farming wasn't part of life, ask if they enjoyed gardening or the outdoors." } },
    { id:"en-tool-04", genre:"tool", emoji:"🧵", photo:null,
      question:"At home, sewing was done on a machine worked by a foot pedal — a what?", choices:["A treadle sewing machine","A knitting loom","A spinning wheel"], answerIndex:0,
      trivia:"The rhythmic tap of the treadle machine made and mended the family's clothes.",
      cue:{ open:"\"That foot-pedal sewing machine — remember the rhythm of it?\"",
        asks:["Did you sew, knit, or mend?","Did you make clothes for your children?","What were you proud to have made?"],
        expand:"Handwork is a memory of caring for family. Ask what they made and for whom.",
        care:"Sewing skews to some; for others, ask about fixing, building, or tinkering." } },
    { id:"en-tool-05", genre:"tool", emoji:"🧰", photo:null,
      question:"At the store, the machine that rang up sales with a 'cha-ching' was a what?", choices:["A cash register","A typewriter","A radio"], answerIndex:0,
      trivia:"The heavy keys and the 'cha-ching' of the register were the sound of a busy shop.",
      cue:{ open:"\"That 'cha-ching' of the old cash register!\"",
        asks:["Did you ever work in a shop or business?","What was the busiest time of day?","What did you enjoy about the work?"],
        expand:"Workplace sounds bring back whole days and the people in them.",
        care:"Follow the pride and the people; let them set the pace." } },

    /* fashion */
    { id:"en-fashion-01", genre:"fashion", emoji:"👖", photo:null,
      question:"In the 1970s, young people loved trousers that flared widely at the ankle. What were they called?", choices:["Bell-bottoms","Overalls","Knickerbockers"], answerIndex:0,
      trivia:"Bell-bottoms went hand in hand with the music and style of the era.",
      cue:{ open:"\"Did you follow the fashions back then?\" — asked with a grin.",
        asks:["What styles were popular when you were young?","Did you have a favorite outfit?","What did you wear for a night out or a date?"],
        expand:"Fashion memories are 'young and shining' memories — often leading to romance and good times.",
        care:"For someone who has lost a partner, these can carry sadness. Watch and don't push." } },
    { id:"en-fashion-02", genre:"fashion", emoji:"👗", photo:null,
      question:"In the 1950s, girls wore wide, swirling skirts often called a what?", choices:["A poodle skirt","A raincoat","A uniform"], answerIndex:0,
      trivia:"Poodle skirts twirled at the sock hop — the look of 1950s dances.",
      cue:{ open:"\"Poodle skirts and sock hops — did you love to dance?\"",
        asks:["Did you go to dances when you were young?","What did you wear to look your best?","What music did you dance to?"],
        expand:"Dance memories are joyful and full of youth. Ask about the music and the dance halls.",
        care:"If dancing wasn't for them, ask how young people dressed up and gathered." } },
    { id:"en-fashion-03", genre:"fashion", emoji:"🎩", photo:null,
      question:"Men often finished an outfit with a soft felt hat called a what?", choices:["A fedora","A helmet","A crown"], answerIndex:0,
      trivia:"A well-worn fedora was a mark of the well-dressed man of the mid-century.",
      cue:{ open:"\"A sharp fedora finished the look, didn't it?\"",
        asks:["How did people dress up to go out back then?","Did the men in your family wear hats?","What did you wear for special occasions?"],
        expand:"Dressing-up memories bring back weddings, dances, and Sunday best.",
        care:"Follow the occasions and people; keep the tone warm and admiring." } },
    { id:"en-fashion-04", genre:"fashion", emoji:"👟", photo:null,
      question:"Students loved two-tone lace-up shoes called a what?", choices:["Saddle shoes","Rain boots","Slippers"], answerIndex:0,
      trivia:"Black-and-white saddle shoes were the classroom classic of the era.",
      cue:{ open:"\"Saddle shoes — the school look, weren't they?\"",
        asks:["What did you wear to school?","What were your school days like?","Did you have a favorite teacher or subject?"],
        expand:"School memories are rich — friends, teachers, and the walk to school.",
        care:"School years can hold hard memories too. Follow the person's lead gently." } },
    { id:"en-fashion-05", genre:"fashion", emoji:"🧦", photo:null,
      question:"Sheer leg coverings women wore, once quite precious, were called what?", choices:["Nylons (stockings)","Mittens","Scarves"], answerIndex:0,
      trivia:"Nylons were a prized treat — carefully saved and mended to make them last.",
      cue:{ open:"\"Nylons — you took good care of those, didn't you?\"",
        asks:["What did you wear for a special occasion?","Did you save certain clothes for 'best'?","How did you make things last back then?"],
        expand:"Making things last is a memory of thrift and care. Receive it warmly.",
        care:"Keep it about resourcefulness and pride, never about going without." } },

    /* hobbies */
    { id:"en-hobby-01", genre:"hobby", emoji:"🪀", photo:null,
      question:"Children spun this round toy up and down on a string, even to 'walk the dog'. What is it?", choices:["A yo-yo","A kite","A marble"], answerIndex:0,
      trivia:"The yo-yo has entertained children for generations, with tricks traded friend to friend.",
      cue:{ open:"\"Could you 'walk the dog' with a yo-yo?\"",
        asks:["What did you play with as a child?","Any games you were really good at?","Where did you and your friends gather to play?"],
        expand:"Play memories come with friends and places. Physical games bring back youthful energy.",
        care:"Some spent more time alone. Keep it open: \"how did you like to spend your time?\"" } },
    { id:"en-hobby-02", genre:"hobby", emoji:"🔵", photo:null,
      question:"What game had children flicking small glass balls across the ground?", choices:["Marbles","Chess","Bowling"], answerIndex:0,
      trivia:"A bag of marbles — 'shooters' and 'cat's eyes' — was a prized childhood treasure.",
      cue:{ open:"\"Were you a good shot at marbles?\"",
        asks:["What games did you play outdoors?","Did you have a lucky marble or a favorite toy?","Who did you play with?"],
        expand:"Games of skill bring out pride and the friends who shared them.",
        care:"If they preferred watching or quieter play, welcome that just as warmly." } },
    { id:"en-hobby-03", genre:"hobby", emoji:"🪢", photo:null,
      question:"Children jumped over a swinging rope while chanting rhymes. What is this?", choices:["Jump rope","Fishing","Sailing"], answerIndex:0,
      trivia:"Jump-rope rhymes echoed across schoolyards and sidewalks for generations.",
      cue:{ open:"\"Did you jump rope — and know all the rhymes?\"",
        asks:["What rhymes or games did you play?","Where did you play after school?","Who were your closest playmates?"],
        expand:"Rhyme games can bring back the actual words — chant one together and watch faces light up.",
        care:"If the rhymes don't come, that's fine — \"what a memory\" is enough." } },
    { id:"en-hobby-04", genre:"hobby", emoji:"🔢", photo:null,
      question:"What game has you hopping through numbered squares drawn on the ground?", choices:["Hopscotch","Checkers","Darts"], answerIndex:0,
      trivia:"Chalk squares on the sidewalk, a tossed stone, and hop, hop, hop — a schoolyard classic.",
      cue:{ open:"\"Were you good at hopscotch?\"",
        asks:["What did you play at recess?","Where did you draw your hopscotch?","Who did you play with most?"],
        expand:"Schoolyard games come bundled with friends and places from childhood.",
        care:"Keep the question open for those who spent recess in quieter ways." } },
    { id:"en-hobby-05", genre:"hobby", emoji:"🏃", photo:null,
      question:"In which game does one child, who is 'it', chase and tag the others?", choices:["Tag","Golf","Cards"], answerIndex:0,
      trivia:"\"You're it!\" — games of tag ran until the streetlights came on.",
      cue:{ open:"\"Games of tag until the streetlights came on — remember?\"",
        asks:["What did you play outside until dark?","Were you called in for supper?","What was your neighborhood like?"],
        expand:"'Until dark' play is a memory of freedom and the old neighborhood.",
        care:"If they feel wistful about not moving as freely now, share the fond memory gently." } },
    { id:"en-hobby-06", genre:"hobby", emoji:"⚾", photo:null,
      question:"Children collected and traded cards featuring their favorite players — called what?", choices:["Baseball cards","Playing cards","Postcards"], answerIndex:0,
      trivia:"Trading baseball cards — and clipping one to the bike spokes — was a boyhood ritual.",
      cue:{ open:"\"Did you collect baseball cards?\"",
        asks:["Who was your favorite player or team?","Did you go to any ballgames?","Did you play a sport growing up?"],
        expand:"Sports memories bring back heroes, teams, and days at the ballpark.",
        care:"If sports weren't their thing, ask what they did collect or cheer for." } },
    { id:"en-hobby-07", genre:"hobby", emoji:"🛼", photo:null,
      question:"Metal skates that clamped onto your shoes with a key were called what?", choices:["Roller skates","Ice skates","Snowshoes"], answerIndex:0,
      trivia:"You wore the skate key on a string around your neck — clamp on, and off you rolled.",
      cue:{ open:"\"Roller skates with a key on a string — remember those?\"",
        asks:["Did you skate as a child?","Where did you like to go — the sidewalk, the rink?","Who did you go with?"],
        expand:"Skating memories are full of motion and friends. Follow the fun and the places.",
        care:"If they couldn't skate, ask what they loved to do to get outdoors." } }
  ],

  /* ---- Tab 3: this or that? (24) ---- */
  eitherOr: [
    { id:"en-eo-01", left:{label:"Coffee", emoji:"☕"}, right:{label:"Tea", emoji:"🍵"}, staffCue:"\"Are you a coffee or tea person? How do you take it?\"" },
    { id:"en-eo-02", left:{label:"Cats", emoji:"🐈"}, right:{label:"Dogs", emoji:"🐕"}, staffCue:"\"Did you ever have a pet? What was its name?\"" },
    { id:"en-eo-03", left:{label:"Beach", emoji:"🏖️"}, right:{label:"Mountains", emoji:"⛰️"}, staffCue:"\"Where did you like to go on holiday — the seaside or the hills?\"" },
    { id:"en-eo-04", left:{label:"Sweet", emoji:"🍰"}, right:{label:"Salty", emoji:"🥨"}, staffCue:"\"Sweet tooth or savory? What snack could you never resist?\"" },
    { id:"en-eo-05", left:{label:"Radio", emoji:"📻"}, right:{label:"Records", emoji:"🎵"}, staffCue:"\"What music did you love? Radio or records?\"" },
    { id:"en-eo-06", left:{label:"Summer", emoji:"🌻"}, right:{label:"Winter", emoji:"⛄"}, staffCue:"\"Which season suits you best? What did you love about it?\"" },
    { id:"en-eo-07", left:{label:"Spring", emoji:"🌷"}, right:{label:"Autumn", emoji:"🍁"}, staffCue:"\"Spring blossoms or autumn leaves — which do you prefer?\"" },
    { id:"en-eo-08", left:{label:"City", emoji:"🏙️"}, right:{label:"Country", emoji:"🌾"}, staffCue:"\"Did you grow up in the city or the country? Which did you like?\"" },
    { id:"en-eo-09", left:{label:"Movies", emoji:"🎬"}, right:{label:"Theater", emoji:"🎭"}, staffCue:"\"Did you go to the pictures or the theater? A favorite star?\"" },
    { id:"en-eo-10", left:{label:"Books", emoji:"📖"}, right:{label:"Walks", emoji:"🚶"}, staffCue:"\"A quiet read or a good walk — which do you enjoy more?\"" },
    { id:"en-eo-11", left:{label:"Singing", emoji:"🎤"}, right:{label:"Dancing", emoji:"💃"}, staffCue:"\"Did you like to sing or to dance? Any favorite song?\"" },
    { id:"en-eo-12", left:{label:"Cake", emoji:"🍰"}, right:{label:"Pie", emoji:"🥧"}, staffCue:"\"Cake or pie? What was the family favorite dessert?\"" },
    { id:"en-eo-13", left:{label:"Rock 'n' roll", emoji:"🎸"}, right:{label:"Jazz", emoji:"🎷"}, staffCue:"\"What music got you moving when you were young?\"" },
    { id:"en-eo-14", left:{label:"Baseball", emoji:"⚾"}, right:{label:"Football", emoji:"🏈"}, staffCue:"\"Did you follow a team? Ever go to a game?\"" },
    { id:"en-eo-15", left:{label:"Sunrise", emoji:"🌅"}, right:{label:"Sunset", emoji:"🌇"}, staffCue:"\"Early riser or one for the evening? How were your mornings?\"" },
    { id:"en-eo-16", left:{label:"Letters", emoji:"✉️"}, right:{label:"Phone calls", emoji:"☎️"}, staffCue:"\"Did you keep in touch by letter or by phone?\"" },
    { id:"en-eo-17", left:{label:"Ocean", emoji:"🌊"}, right:{label:"Lake", emoji:"🏞️"}, staffCue:"\"The ocean or a quiet lake — where did you like to be?\"" },
    { id:"en-eo-18", left:{label:"Chocolate", emoji:"🍫"}, right:{label:"Vanilla", emoji:"🍦"}, staffCue:"\"Chocolate or vanilla? What was your go-to ice cream?\"" },
    { id:"en-eo-19", left:{label:"Pancakes", emoji:"🥞"}, right:{label:"Waffles", emoji:"🧇"}, staffCue:"\"What did a special breakfast look like at your house?\"" },
    { id:"en-eo-20", left:{label:"Early bird", emoji:"🐦"}, right:{label:"Night owl", emoji:"🦉"}, staffCue:"\"Were you up with the sun or a night owl?\"" },
    { id:"en-eo-21", left:{label:"Train", emoji:"🚂"}, right:{label:"Car", emoji:"🚗"}, staffCue:"\"Did you travel by train or by car? Any memorable trips?\"" },
    { id:"en-eo-22", left:{label:"Comedy", emoji:"😄"}, right:{label:"Drama", emoji:"🎭"}, staffCue:"\"Did you like a good laugh or a gripping story?\"" },
    { id:"en-eo-23", left:{label:"Roses", emoji:"🌹"}, right:{label:"Sunflowers", emoji:"🌻"}, staffCue:"\"Did you keep a garden? What did you like to grow?\"" },
    { id:"en-eo-24", left:{label:"Home cooking", emoji:"🍲"}, right:{label:"Dining out", emoji:"🍽️"}, staffCue:"\"A home-cooked meal or a night out — which did you prefer?\"" }
  ],

  /* ---- Tab 3: color mood (always positive; 6) ---- */
  colorTest: {
    prompt:null,
    options:[
      { key:"red",    label:"Red",    emoji:"🔴", color:"#e0655e",
        result:"You're warm and full of energy — like sunshine that lifts the people around you.",
        cue:"\"What's something you threw your whole heart into when you were younger?\"" },
      { key:"blue",   label:"Blue",   emoji:"🔵", color:"#4a86c9",
        result:"You're calm and caring — the kind of person others trust and lean on.",
        cue:"\"Were you often the one people came to for help or advice?\"" },
      { key:"yellow", label:"Yellow", emoji:"🟡", color:"#eab52f",
        result:"You're bright and curious — the one who makes any room more fun.",
        cue:"\"What's a happy memory or a good laugh that still makes you smile?\"" },
      { key:"green",  label:"Green",  emoji:"🟢", color:"#4a9d6f",
        result:"You're gentle and steady — a calming presence that puts people at ease.",
        cue:"\"Is there a place or a view that always helps you feel at peace?\"" },
      { key:"orange", label:"Orange", emoji:"🟠", color:"#e8934a",
        result:"You're warm and easy to be around — someone who brings people together.",
        cue:"\"Have you always valued your friends and neighbors?\"" },
      { key:"purple", label:"Purple", emoji:"🟣", color:"#8a6bd0",
        result:"You're graceful and thoughtful — quietly strong, with a rich inner world.",
        cue:"\"Is there music or art that has always moved you?\"" }
    ]
  },

  /* ---- Notable people (birthdays 🎂 / anniversaries 🕯️). Dates fact-checked in the ja pack. ---- */
  people: [
    { month:3,  day:14, type:"birth", name:"Albert Einstein",       note:"German-born physicist. Born in 1879. His theory of relativity changed how we see the universe." },
    { month:4,  day:18, type:"death", name:"Albert Einstein",       note:"Physicist. Died in 1955. One of the greatest scientists of the 20th century." },
    { month:4,  day:16, type:"birth", name:"Charlie Chaplin",       note:"English actor and director. Born in 1889. His silent comedies made the whole world laugh." },
    { month:12, day:25, type:"death", name:"Charlie Chaplin",       note:"The 'Little Tramp'. Died in 1977. Beloved for films like 'Modern Times' and 'The Kid'." },
    { month:6,  day:1,  type:"birth", name:"Marilyn Monroe",        note:"American actress. Born in 1926. A screen icon of the 1950s." },
    { month:8,  day:4,  type:"death", name:"Marilyn Monroe",        note:"Actress. Died in 1962. One of Hollywood's most enduring stars." },
    { month:5,  day:4,  type:"birth", name:"Audrey Hepburn",        note:"Actress. Born in 1929. Famous for 'Roman Holiday'; later devoted herself to charity." },
    { month:1,  day:20, type:"death", name:"Audrey Hepburn",        note:"Actress. Died in 1993. Loved for her grace on screen and her humanitarian work." },
    { month:10, day:9,  type:"birth", name:"John Lennon",           note:"English musician. Born in 1940. A member of the Beatles." },
    { month:12, day:8,  type:"death", name:"John Lennon",           note:"Musician. Died in 1980. He sang of peace in songs like 'Imagine'." },
    { month:1,  day:8,  type:"birth", name:"Elvis Presley",         note:"American singer. Born in 1935. Known as the 'King of Rock and Roll'." },
    { month:8,  day:16, type:"death", name:"Elvis Presley",         note:"Singer. Died in 1977. He brought rock and roll to the world." },
    { month:8,  day:29, type:"birth", name:"Michael Jackson",       note:"American singer. Born in 1958. Known as the 'King of Pop'." },
    { month:6,  day:25, type:"death", name:"Michael Jackson",       note:"Singer. Died in 2009. A global star behind 'Thriller'." },
    { month:12, day:5,  type:"birth", name:"Walt Disney",           note:"American animator and businessman. Born in 1901. He created Mickey Mouse." },
    { month:12, day:15, type:"death", name:"Walt Disney",           note:"Animator and businessman. Died in 1966. The founder of Disneyland." },
    { month:2,  day:12, type:"birth", name:"Abraham Lincoln",       note:"16th U.S. President. Born in 1809. He led the country and moved to end slavery." },
    { month:4,  day:15, type:"death", name:"Abraham Lincoln",       note:"U.S. President. Died in 1865. Remembered for the Gettysburg Address." },
    { month:2,  day:11, type:"birth", name:"Thomas Edison",         note:"American inventor. Born in 1847. Known for the light bulb and the phonograph." },
    { month:10, day:18, type:"death", name:"Thomas Edison",         note:"Inventor. Died in 1931. Often called the 'Wizard of Menlo Park'." },
    { month:11, day:7,  type:"birth", name:"Marie Curie",           note:"Physicist and chemist. Born in 1867. The first woman to win a Nobel Prize." },
    { month:7,  day:4,  type:"death", name:"Marie Curie",           note:"Scientist. Died in 1934. A pioneer in the study of radioactivity." },
    { month:5,  day:12, type:"birth", name:"Florence Nightingale",  note:"English nurse. Born in 1820. The founder of modern nursing; May 12 is Nurses Day." },
    { month:8,  day:13, type:"death", name:"Florence Nightingale",  note:"Nurse. Died in 1910. Known as 'The Lady with the Lamp'." },
    { month:6,  day:27, type:"birth", name:"Helen Keller",          note:"American author and activist. Born in 1880. Deaf and blind, she inspired the world." },
    { month:6,  day:1,  type:"death", name:"Helen Keller",          note:"Author and activist. Died in 1968. She overcame great obstacles to help others." },
    { month:10, day:2,  type:"birth", name:"Mahatma Gandhi",        note:"Leader of Indian independence. Born in 1869. He led a movement of non-violence." },
    { month:1,  day:30, type:"death", name:"Mahatma Gandhi",        note:"Father of Indian independence. Died in 1948. He stood for peace to the end." },
    { month:8,  day:26, type:"birth", name:"Mother Teresa",         note:"Catholic nun. Born in 1910. She served the poor and won the Nobel Peace Prize." },
    { month:9,  day:5,  type:"death", name:"Mother Teresa",         note:"Nun. Died in 1997. Beloved for her devotion to those in need." },
    { month:1,  day:27, type:"birth", name:"Wolfgang Amadeus Mozart", note:"Austrian composer. Born in 1756. A musical genius who wrote countless masterpieces." },
    { month:12, day:5,  type:"death", name:"Wolfgang Amadeus Mozart", note:"Composer. Died in 1791. Known for works like 'The Magic Flute'." },
    { month:3,  day:30, type:"birth", name:"Vincent van Gogh",      note:"Dutch painter. Born in 1853. Famous for 'Sunflowers' and 'The Starry Night'." },
    { month:7,  day:29, type:"death", name:"Vincent van Gogh",      note:"Painter. Died in 1890. A post-Impressionist master celebrated after his death." },
    { month:10, day:25, type:"birth", name:"Pablo Picasso",         note:"Spanish painter. Born in 1881. A founder of Cubism and a giant of modern art." },
    { month:4,  day:8,  type:"death", name:"Pablo Picasso",         note:"Painter. Died in 1973. Known for works like 'Guernica'." },
    { month:11, day:14, type:"birth", name:"Claude Monet",          note:"French painter. Born in 1840. A leader of Impressionism, famous for 'Water Lilies'." },
    { month:12, day:5,  type:"death", name:"Claude Monet",          note:"Painter. Died in 1926. His 'Impression, Sunrise' gave Impressionism its name." },
    { month:3,  day:26, type:"death", name:"Ludwig van Beethoven",  note:"German composer. Born around 1770, died in 1827. A master known for his Ninth Symphony." },
    { month:7,  day:6,  type:"death", name:"Louis Armstrong",       note:"American jazz musician. Died in 1971. Beloved for 'What a Wonderful World'." },
    { month:7,  day:6,  type:"birth", name:"Frida Kahlo",           note:"Mexican painter. Born in 1907. Known worldwide for her vivid self-portraits." }
  ]
};
