/*
 * Soyogi (Édition seniors) — content.fr.js
 * Contenus de conversation en français (écrits pour la culture française).
 * ============================================================================
 * ★PAS une traduction de content.ja.js. Les souvenirs sont propres à chaque
 *   culture ; ce paquet est écrit autour de souvenirs qu'une personne âgée en
 *   France est susceptible de partager (le franc, la Coupe du monde 98, le
 *   muguet du 1er mai…). Schéma identique à ja (voir l'en-tête de content.ja.js ;
 *   astuce conversation : cue = {open, asks[], expand, care}).
 *   Les dates historiques sont vérifiées et sourcées. Vérifier aussi tout ajout.
 * ============================================================================
 */
window.SOYOGI_WS_CONTENT = window.SOYOGI_WS_CONTENT || {};
window.SOYOGI_WS_CONTENT["fr"] = {

  /* ---- Onglet 1 : fleur du jour (par mois ; significations positives) ---- */
  flowers: [
    { month:1,  name:"Perce-neige",      emoji:"🌼", photo:null, meaning:"Espoir & consolation", note:"Ose sortir de la neige au cœur de l'hiver." },
    { month:2,  name:"Violette",         emoji:"🌸", photo:null, meaning:"Modestie & fidélité", note:"Une petite fleur parfumée qui annonce le printemps." },
    { month:3,  name:"Jonquille",        emoji:"🌼", photo:null, meaning:"Renouveau", note:"Son jaune éclatant ouvre le printemps." },
    { month:4,  name:"Tulipe",           emoji:"🌷", photo:null, meaning:"Amour tendre", note:"Met de la couleur dans les jardins et les vases." },
    { month:5,  name:"Muguet",           emoji:"🌷", photo:null, meaning:"Retour du bonheur", note:"On s'en offre un brin le 1er mai, pour porter chance." },
    { month:6,  name:"Rose",             emoji:"🌹", photo:null, meaning:"Amour & reconnaissance", note:"La fleur classique de l'été." },
    { month:7,  name:"Lavande",          emoji:"🪻", photo:null, meaning:"Calme & sérénité", note:"Le parfum bleu-violet de l'été en Provence." },
    { month:8,  name:"Tournesol",        emoji:"🌻", photo:null, meaning:"Admiration & chaleur", note:"Tourne son visage vers le soleil d'été." },
    { month:9,  name:"Dahlia",           emoji:"🌸", photo:null, meaning:"Dignité & gratitude", note:"Généreux, il fleurit jusqu'aux premiers frimas." },
    { month:10, name:"Aster",            emoji:"🌸", photo:null, meaning:"Patience & élégance", note:"Une étoile qui prolonge l'été dans l'automne." },
    { month:11, name:"Camélia",          emoji:"🌺", photo:null, meaning:"Fidélité & admiration", note:"Fleurit quand presque tout se repose." },
    { month:12, name:"Étoile de Noël",   emoji:"🌺", photo:null, meaning:"Joie de Noël", note:"Le rouge et le vert des fêtes de fin d'année." }
  ],

  /* ---- Onglet 1 : ce jour-là (événements joyeux et vérifiés) ---- */
  onThisDay: [
    { month:3,  day:2,  year:1969, text:"Le Concorde effectue son tout premier vol, à Toulouse.", emoji:"✈️" },
    { month:6,  day:24, year:1982, text:"Jean-Loup Chrétien devient le premier Français dans l'espace.", emoji:"🚀" },
    { month:7,  day:12, year:1998, text:"La France devient championne du monde de football (3-0 contre le Brésil).", emoji:"⚽" },
    { month:9,  day:20, year:1946, text:"La toute première édition du Festival de Cannes s'ouvre.", emoji:"🎬" },
    { month:9,  day:27, year:1981, text:"Le TGV entre en service commercial entre Paris et Lyon.", emoji:"🚄" },
    { month:10, day:6,  year:1955, text:"La Citroën DS est dévoilée au Salon de l'automobile de Paris.", emoji:"🚗" }
  ],

  /* ---- Onglet 2 : quiz souvenirs (le saviez-vous + astuce conversation) ---- */
  quizzes: [
    {
      id:"fr-warmup-01", genre:"warmup", emoji:"🍉", photo:null,
      question:"Qu'est-ce qui est plus gros et plus lourd — une pastèque ou une pomme ?",
      choices:["Une pastèque","Une pomme"], answerIndex:0,
      trivia:"Une grosse pastèque peut peser plus de 10 kilos — un plaisir d'été depuis toujours.",
      cue:{
        open:"« C'était facile, n'est-ce pas ? » — avec le sourire, puis vers les souvenirs d'été.",
        asks:[
          "Mangiez-vous de la pastèque l'été ?",
          "Faisiez-vous des pique-niques ou des sorties ?",
          "Avec qui passiez-vous vos étés ?"
        ],
        expand:"L'important est de profiter du moment plutôt que de la bonne réponse. Partager un petit souvenir à vous (« chez nous, il y avait toujours… ») aide la personne à se confier.",
        care:"Une hésitation n'est pas grave — « les deux sont délicieuses ! » garde l'ambiance légère. Un sourire, c'est déjà réussi."
      }
    },
    {
      id:"fr-warmup-02", genre:"warmup", emoji:"🥖", photo:null,
      question:"Qu'est-ce qui est le plus long — une baguette ou un petit pain ?",
      choices:["Une baguette","Un petit pain"], answerIndex:0,
      trivia:"La baguette accompagne les repas français depuis des générations, achetée fraîche chaque jour.",
      cue:{
        open:"« La baguette, bien sûr ! » Puis on parle du pain et des repas d'autrefois.",
        asks:[
          "Alliez-vous chercher le pain à la boulangerie ?",
          "Quel plat de votre enfance préfériez-vous ?",
          "Qui cuisinait à la maison ?"
        ],
        expand:"La nourriture réveille des souvenirs puissants. Demandez les odeurs, le repas du dimanche — la scène reprend vie.",
        care:"Si manger est un sujet délicat pour la personne, restez sur le souvenir, pas sur la nourriture elle-même."
      }
    },
    {
      id:"fr-price-01", genre:"price", emoji:"💰", photo:null,
      question:"Avec quelle monnaie payait-on en France avant l'euro ?",
      choices:["Le franc","L'euro","Le mark"], answerIndex:0,
      trivia:"Jusqu'en 2002, on payait en francs. L'euro en pièces et billets est arrivé le 1er janvier 2002.",
      cue:{
        open:"« Ah, le bon vieux franc ! » — beaucoup s'en souviennent avec tendresse.",
        asks:[
          "Vous souvenez-vous bien des francs ?",
          "Que pouvait-on acheter pour quelques francs ?",
          "Comment économisiez-vous votre argent de poche, enfant ?"
        ],
        expand:"L'argent ouvre la porte à la vie d'autrefois — les prix, les premiers achats, les petits plaisirs. Suivez le fil du souvenir.",
        care:"Certains ont eu peu. Gardez un ton d'émerveillement partagé, jamais de comparaison."
      }
    },
    {
      id:"fr-appliance-01", genre:"appliance", emoji:"📺", photo:null,
      question:"Avant les télécommandes, comment changeait-on de chaîne à la télévision ?",
      choices:["En tournant le bouton de l'appareil","En tapant dans les mains","En sifflant devant l'écran"], answerIndex:0,
      trivia:"Quelqu'un devait se lever pour tourner le bouton — souvent le plus jeune de la famille !",
      cue:{
        open:"« Quelqu'un devait se lever pour tourner le bouton ! » — avec un sourire.",
        asks:[
          "Quelles émissions regardiez-vous en famille ?",
          "Qui réglait la télévision ?",
          "Vous souvenez-vous de la première télévision à la maison ?"
        ],
        expand:"La « première télé » est un souvenir joyeux et facile, souvent lié à toute la famille. Demandez qui était dans la pièce.",
        care:"Toutes les maisons n'ont pas eu la télé tôt. Demandez « vous souvenez-vous de son arrivée ? » plutôt que de le supposer."
      }
    },
    {
      id:"fr-snack-01", genre:"snack", emoji:"🍭", photo:null,
      question:"Comment appelle-t-on la gourmandise de fête foraine, faite de sucre filé tout rose ?",
      choices:["La barbe à papa","La guimauve","Le nougat"], answerIndex:0,
      trivia:"Toute légère et sucrée, la barbe à papa était le plaisir des fêtes foraines et des kermesses.",
      cue:{
        open:"« Cette gourmandise toute rose et sucrée ! »",
        asks:[
          "Alliez-vous à la fête foraine ?",
          "Quelle friandise préfériez-vous, enfant ?",
          "Y avait-il une épicerie ou une confiserie près de chez vous ?"
        ],
        expand:"Les gourmandises d'enfance sont des souvenirs gais et faciles à raconter. Les noms des lieux et des amis les rendent vivants.",
        care:"Pour certains, l'après-guerre a été rude. Ne présumez de rien et avancez au rythme de la personne."
      }
    },
    {
      id:"fr-tool-01", genre:"tool", emoji:"⌨️", photo:null,
      question:"Avant les ordinateurs, quelle machine de bureau frappait l'encre sur le papier ?",
      choices:["La machine à écrire","La caisse enregistreuse","La machine à coudre"], answerIndex:0,
      trivia:"Le cliquetis des touches et le petit tintement en fin de ligne rythmaient les bureaux.",
      cue:{
        open:"« Ce cliquetis des touches — et le petit tintement en fin de ligne ! »",
        asks:[
          "Quel métier avez-vous exercé ?",
          "Quels outils ou machines utilisiez-vous chaque jour ?",
          "En quoi étiez-vous particulièrement doué(e) dans votre travail ?"
        ],
        expand:"Parler du travail et du savoir-faire nourrit la fierté. « Vous deviez être rapide ! » fait toujours plaisir.",
        care:"Pour qui n'a pas travaillé à l'extérieur, demandez plutôt les savoir-faire utilisés à la maison."
      }
    },
    {
      id:"fr-fashion-01", genre:"fashion", emoji:"👖", photo:null,
      question:"Quel pantalon très évasé vers le bas était à la mode dans les années 1970 ?",
      choices:["Le pantalon pattes d'éléphant","Le pantacourt","La salopette"], answerIndex:0,
      trivia:"Le « pattes d'eph' » accompagnait la musique et l'air du temps de ces années-là.",
      cue:{
        open:"« Suiviez-vous la mode à l'époque ? » — avec un clin d'œil.",
        asks:[
          "Quels styles étaient à la mode quand vous étiez jeune ?",
          "Aviez-vous une tenue préférée ?",
          "Que portiez-vous pour sortir ou pour un rendez-vous ?"
        ],
        expand:"Les souvenirs de mode sont ceux de la jeunesse rayonnante — souvent liés aux amours. Les visages s'illuminent.",
        care:"Pour qui a perdu son conjoint, ces souvenirs peuvent être teintés de tristesse. Observez le visage et n'insistez pas."
      }
    },
    {
      id:"fr-hobby-01", genre:"hobby", emoji:"🔢", photo:null,
      question:"À quel jeu dessine-t-on des cases par terre pour sauter à cloche-pied ?",
      choices:["La marelle","Les billes","La corde à sauter"], answerIndex:0,
      trivia:"On dessinait la marelle à la craie et on poussait un palet de case en case — un grand classique des cours de récré.",
      cue:{
        open:"« Étiez-vous fort(e) à la marelle ? »",
        asks:[
          "À quoi jouiez-vous, enfant ?",
          "À quel jeu étiez-vous particulièrement doué(e) ?",
          "Où retrouviez-vous vos amis pour jouer ?"
        ],
        expand:"Les souvenirs de jeux vont de pair avec les amis et les lieux. Les jeux actifs raniment la sensation d'être jeune et plein d'énergie.",
        care:"Certains étaient plutôt solitaires. Gardez la question ouverte : « comment aimiez-vous passer votre temps ? »"
      }
    },
    {
      id:"fr-warmup-03", genre:"warmup", emoji:"🍋", photo:null,
      question:"Qu'est-ce qui est plus sucré — le sucre ou un citron ?",
      choices:["Le sucre","Le citron"], answerIndex:0,
      trivia:"Le sucre était précieux autrefois ; un gâteau, c'était un vrai plaisir des jours de fête.",
      cue:{
        open:"« Le sucre, bien sûr ! » — avec un sourire, puis vers les douceurs d'autrefois.",
        asks:["Faisait-on souvent des gâteaux chez vous ?","Qui pâtissait à la maison ?","Quel gâteau préfériez-vous ?"],
        expand:"La pâtisserie et les fêtes réveillent des souvenirs tendres. Demander les parfums — vanille, fleur d'oranger — fait revivre la scène.",
        care:"Même si les douceurs étaient rares, saluez cela avec chaleur : « c'était une autre époque »."
      }
    },
    {
      id:"fr-price-02", genre:"price", emoji:"🎬", photo:null,
      question:"Combien coûtait environ une place de cinéma dans les années 1960 ?",
      choices:["Environ 3 francs","Environ 30 francs","Environ 300 francs"], answerIndex:0,
      trivia:"Une sortie au cinéma était un plaisir accessible, pour quelques francs.",
      cue:{
        open:"« Une place pour quelques francs — quelle belle époque, n'est-ce pas ? »",
        asks:["Alliez-vous souvent au cinéma ?","Quels films ou quelles vedettes aimiez-vous ?","Avec qui y alliez-vous ?"],
        expand:"Ce n'est pas le prix exact qui compte, mais le souvenir. Les actualités, l'entracte, le premier rendez-vous — tout cela fait parler.",
        care:"En cas d'hésitation, un exemple de votre propre vie aide à faire renaître l'époque ensemble."
      }
    },
    {
      id:"fr-appliance-02", genre:"appliance", emoji:"☎️", photo:null,
      question:"Comment composait-on un numéro sur les anciens téléphones ?",
      choices:["Avec un cadran rotatif","Avec un écran tactile"], answerIndex:0,
      trivia:"On tournait chaque chiffre sur le cadran, avec un petit ronronnement caractéristique.",
      cue:{
        open:"« Le cadran — c'était long à faire tourner, n'est-ce pas ? »",
        asks:["Aviez-vous le téléphone à la maison de bonne heure ?","Qui appeliez-vous le plus volontiers ?","Vous souvenez-vous de votre ancien numéro ?"],
        expand:"Le téléphone relie à la famille et aux amis. Le ronronnement du cadran ramène l'époque.",
        care:"Beaucoup n'ont eu le téléphone que tard — c'est normal et cela fait un bon sujet."
      }
    },
    {
      id:"fr-snack-02", genre:"snack", emoji:"🍬", photo:null,
      question:"Quelle friandise se léchait au fond d'un petit coquillage en plastique ?",
      choices:["Le roudoudou","Le nougat"], answerIndex:0,
      trivia:"Le roudoudou, ce bonbon dur au fond d'une coquille, faisait le bonheur des enfants pour quelques centimes.",
      cue:{
        open:"« Le roudoudou — on le léchait jusqu'au bout ! » Avec un sourire, vers les bonbons d'antan.",
        asks:["Quels bonbons trouvait-on à l'épicerie du coin ?","Aviez-vous de l'argent de poche pour les friandises ?","Quelle était votre gourmandise préférée ?"],
        expand:"L'épicerie du quartier et quelques sous de poche sont de jolis points d'ancrage.",
        care:"Si les douceurs étaient rares, honorez cette époque frugale avec bienveillance, sans jugement."
      }
    },
    {
      id:"fr-tool-02", genre:"tool", emoji:"🧺", photo:null,
      question:"Avec quoi lavait-on le linge à la main, avant les machines à laver ?",
      choices:["Avec une planche à laver","Avec un aspirateur"], answerIndex:0,
      trivia:"On frottait le linge sur la planche, souvent au lavoir — un vrai travail, le jour de lessive.",
      cue:{
        open:"« La planche à laver — c'était bien fatigant, n'est-ce pas ? »",
        asks:["Le jour de lessive était-il un jour fixe chez vous ?","Qui s'occupait du linge ?","Où faisiez-vous sécher le linge ?"],
        expand:"Les tâches d'autrefois montrent beaucoup de savoir-faire. Un « c'était un travail difficile ! » honore la peine.",
        care:"La reconnaissance fait du bien : « vous avez tout tenu à bout de bras » rend fier et ouvre la parole."
      }
    },
    {
      id:"fr-fashion-02", genre:"fashion", emoji:"👗", photo:null,
      question:"Quelle silhouette à taille fine et jupe ample, lancée par Dior, a marqué l'après-guerre ?",
      choices:["Le New Look","Le pantalon pattes d'éléphant"], answerIndex:0,
      trivia:"Le « New Look » de Christian Dior, présenté en 1947, a redonné de l'élégance et de l'ampleur aux robes.",
      cue:{
        open:"« Le New Look — ces jupes qui tournoyaient à la danse ! »",
        asks:["Aimiez-vous aller danser ?","Quelle mode aimiez-vous, jeune ?","Aviez-vous une robe préférée ou un beau costume ?"],
        expand:"La mode et la danse réveillent la jeunesse. Le premier bal, le premier amour — de belles portes à ouvrir.",
        care:"Chaque souvenir compte — même un sourire sans mots est un joli résultat."
      }
    },
    {
      id:"fr-hobby-02", genre:"hobby", emoji:"🔵", photo:null,
      question:"Comment appelle-t-on les petites boules de verre colorées avec lesquelles jouaient les enfants par terre ?",
      choices:["Les billes","Les boutons"], answerIndex:0,
      trivia:"On jouait aux billes par terre ; les plus belles se gardaient et s'échangeaient comme des trésors.",
      cue:{
        open:"« Les billes — on gardait les plus belles comme un trésor, n'est-ce pas ? »",
        asks:["Collectionniez-vous ou échangiez-vous des billes ?","À quels jeux jouiez-vous dehors ?","Avec qui aimiez-vous jouer ?"],
        expand:"Collectionner et échanger réveillent les souvenirs d'amitié et de voisinage.",
        care:"Si l'enfance a été difficile, restez tout en douceur sur les beaux moments."
      }
    },
    {
      id:"fr-appliance-03", genre:"appliance", emoji:"🎵", photo:null,
      question:"Comment écoutait-on sa musique préférée à la maison autrefois ?",
      choices:["Sur un disque vinyle","Sur un smartphone"], answerIndex:0,
      trivia:"Le disque tournait sur l'électrophone ; on posait délicatement le saphir sur le sillon.",
      cue:{
        open:"« Poser le disque et l'aiguille — un vrai petit rituel, n'est-ce pas ? »",
        asks:["Quelle musique ou quels chanteurs aimiez-vous ?","Aviez-vous un tourne-disque à la maison ?","Sur quelle musique dansiez-vous ?"],
        expand:"La musique est un ancrage puissant. Un titre de chanson suffit souvent à faire venir les histoires.",
        care:"Si une chanson émeut, c'est précieux — laissez toute sa place à l'émotion."
      }
    }
  ],

  /* ---- Onglet 3 : ceci ou cela ? (léger — une phrase suffit) ---- */
  eitherOr: [
    { id:"fr-eo-01", left:{label:"Café", emoji:"☕"}, right:{label:"Thé", emoji:"🍵"},
      staffCue:"« Êtes-vous plutôt café ou thé ? Comment le prenez-vous ? »" },
    { id:"fr-eo-02", left:{label:"Mer", emoji:"🌊"}, right:{label:"Montagne", emoji:"⛰️"},
      staffCue:"« Où partiez-vous en vacances — à la mer ou à la montagne ? »" },
    { id:"fr-eo-03", left:{label:"Chien", emoji:"🐕"}, right:{label:"Chat", emoji:"🐈"},
      staffCue:"« Avez-vous eu un animal ? Comment s'appelait-il ? »" },
    { id:"fr-eo-04", left:{label:"Sucré", emoji:"🍰"}, right:{label:"Salé", emoji:"🥨"},
      staffCue:"« Plutôt bec sucré ou salé ? Quelle gourmandise ne pouviez-vous pas refuser ? »" },
    { id:"fr-eo-05", left:{label:"Baguette", emoji:"🥖"}, right:{label:"Croissant", emoji:"🥐"},
      staffCue:"« Baguette ou croissant au petit-déjeuner ? Où achetiez-vous votre pain ? »" },
    { id:"fr-eo-06", left:{label:"Radio", emoji:"📻"}, right:{label:"Télévision", emoji:"📺"},
      staffCue:"« Radio ou télévision — qu'écoutait-on le plus chez vous ? »" },
    { id:"fr-eo-07", left:{label:"Ville", emoji:"🏙️"}, right:{label:"Campagne", emoji:"🌾"},
      staffCue:"« Avez-vous plutôt grandi en ville ou à la campagne ? »" },
    { id:"fr-eo-08", left:{label:"Printemps", emoji:"🌸"}, right:{label:"Automne", emoji:"🍂"},
      staffCue:"« Printemps ou automne — quelle saison préférez-vous ? »" },
    { id:"fr-eo-09", left:{label:"Danser", emoji:"💃"}, right:{label:"Chanter", emoji:"🎤"},
      staffCue:"« Aimiez-vous plutôt danser ou chanter ? »" },
    { id:"fr-eo-10", left:{label:"Cinéma", emoji:"🎬"}, right:{label:"Lecture", emoji:"📖"},
      staffCue:"« Une séance de cinéma ou un bon livre — que préfériez-vous ? »" },
    { id:"fr-eo-11", left:{label:"Vélo", emoji:"🚲"}, right:{label:"À pied", emoji:"🚶"},
      staffCue:"« Vous déplaciez-vous beaucoup à vélo ou plutôt à pied ? »" },
    { id:"fr-eo-12", left:{label:"Noël", emoji:"🎄"}, right:{label:"Pâques", emoji:"🐰"},
      staffCue:"« Noël ou Pâques — quelle fête aimiez-vous le plus, enfant ? »" },
    { id:"fr-eo-13", left:{label:"Soupe", emoji:"🍲"}, right:{label:"Rôti", emoji:"🍖"},
      staffCue:"« Une bonne soupe ou un rôti du dimanche ? »" },
    { id:"fr-eo-14", left:{label:"Fromage", emoji:"🧀"}, right:{label:"Dessert", emoji:"🍮"},
      staffCue:"« En fin de repas, plutôt fromage ou dessert ? »" },
    { id:"fr-eo-15", left:{label:"Lève-tôt", emoji:"🌅"}, right:{label:"Couche-tard", emoji:"🌙"},
      staffCue:"« Étiez-vous plutôt lève-tôt ou couche-tard ? »" }
  ],

  /* ---- Onglet 3 : couleur du moment (toujours positif) ---- */
  colorTest: {
    prompt:null,
    options:[
      { key:"red",    label:"Rouge", emoji:"🔴", color:"#e0655e",
        result:"Vous êtes chaleureux(se) et plein(e) d'énergie — comme un soleil qui réconforte les autres.",
        cue:"« À quoi vous êtes-vous consacré(e) de tout cœur dans votre jeunesse ? »" },
      { key:"blue",   label:"Bleu",  emoji:"🔵", color:"#4a86c9",
        result:"Vous êtes calme et bienveillant(e) — quelqu'un à qui l'on fait confiance et sur qui l'on s'appuie.",
        cue:"« Étiez-vous souvent la personne vers qui on venait chercher conseil ? »" },
      { key:"yellow", label:"Jaune", emoji:"🟡", color:"#eab52f",
        result:"Vous êtes gai(e) et curieux(se) — vous mettez de la vie dans chaque pièce.",
        cue:"« Avez-vous un souvenir joyeux qui vous fait encore sourire ? »" },
      { key:"green",  label:"Vert",  emoji:"🟢", color:"#4a9d6f",
        result:"Vous êtes doux(ce) et posé(e) — une présence apaisante qui fait du bien.",
        cue:"« Y a-t-il un lieu ou un paysage où vous vous sentez en paix ? »" },
      { key:"orange", label:"Orange", emoji:"🟠", color:"#e8934a",
        result:"Vous êtes chaleureux(se) et sociable — quelqu'un qui rassemble les gens autour de lui.",
        cue:"« Vos amis et vos voisins ont-ils toujours beaucoup compté pour vous ? »" },
      { key:"purple", label:"Violet", emoji:"🟣", color:"#8a6bd0",
        result:"Vous êtes raffiné(e) et sensible — d'une force tranquille, avec une riche vie intérieure.",
        cue:"« Y a-t-il une musique ou un art qui vous a toujours touché(e) ? »" }
    ]
  },

  /* ---- Personnalités célèbres (anniversaire 🎂 / date de décès 🕯️). Dates vérifiées dans le pack ja. ---- */
  people: [
    { month:11, day:14, type:"birth", name:"Claude Monet",          note:"Peintre français. Né en 1840. Maître de l'impressionnisme, célèbre pour ses « Nymphéas »." },
    { month:12, day:5,  type:"death", name:"Claude Monet",          note:"Peintre. Mort en 1926. Son tableau « Impression, soleil levant » a donné son nom à l'impressionnisme." },
    { month:2,  day:25, type:"birth", name:"Auguste Renoir",        note:"Peintre français. Né en 1841. Maître de l'impressionnisme au style plein de lumière et de bonheur." },
    { month:12, day:3,  type:"death", name:"Auguste Renoir",        note:"Peintre. Mort en 1919. Il a peint jusqu'au bout malgré les rhumatismes." },
    { month:1,  day:19, type:"birth", name:"Paul Cézanne",          note:"Peintre français. Né en 1839. Surnommé le « père de la peinture moderne »." },
    { month:10, day:23, type:"death", name:"Paul Cézanne",          note:"Peintre. Mort en 1906. Ses pommes et ses montagnes ont marqué l'art du XXe siècle." },
    { month:7,  day:19, type:"birth", name:"Edgar Degas",           note:"Peintre français. Né en 1834. Connu pour ses danseuses de ballet." },
    { month:9,  day:27, type:"death", name:"Edgar Degas",           note:"Peintre. Mort en 1917. Il saisissait l'instant avec un art rare." },
    { month:10, day:4,  type:"birth", name:"Jean-François Millet",  note:"Peintre français. Né en 1814. Célèbre pour « Des glaneuses » et « L'Angélus »." },
    { month:1,  day:20, type:"death", name:"Jean-François Millet",  note:"Peintre. Mort en 1875. Figure de l'école de Barbizon, il a peint la vie paysanne." },
    { month:6,  day:7,  type:"birth", name:"Paul Gauguin",          note:"Peintre français. Né en 1848. Célèbre pour ses scènes de Tahiti, figure du postimpressionnisme." },
    { month:5,  day:8,  type:"death", name:"Paul Gauguin",          note:"Peintre. Mort en 1903. Connu aussi pour son amitié avec Van Gogh." },
    { month:12, day:31, type:"birth", name:"Henri Matisse",         note:"Peintre français. Né en 1869. Le « magicien de la couleur », chef de file du fauvisme." },
    { month:11, day:3,  type:"death", name:"Henri Matisse",         note:"Peintre. Mort en 1954. Dans ses dernières années, il a innové avec ses gouaches découpées." },
    { month:2,  day:26, type:"birth", name:"Victor Hugo",           note:"Écrivain français. Né en 1802. Auteur des « Misérables »." },
    { month:5,  day:22, type:"death", name:"Victor Hugo",           note:"Écrivain. Mort en 1885. Figure du romantisme, il eut des funérailles nationales." },
    { month:12, day:27, type:"birth", name:"Louis Pasteur",         note:"Bactériologiste français. Né en 1822. Inventeur des vaccins et de la pasteurisation." },
    { month:9,  day:28, type:"death", name:"Louis Pasteur",         note:"Bactériologiste. Mort en 1895. Considéré comme le père de la microbiologie moderne." },
    { month:11, day:7,  type:"birth", name:"Marie Curie",           note:"Physicienne et chimiste. Née en 1867. La première femme à recevoir un prix Nobel." },
    { month:7,  day:4,  type:"death", name:"Marie Curie",           note:"Scientifique. Morte en 1934. Pionnière de l'étude de la radioactivité." },
    { month:8,  day:15, type:"birth", name:"Napoléon Bonaparte",    note:"Empereur des Français. Né en 1769. Il a dirigé la France révolutionnaire et dominé l'Europe." },
    { month:5,  day:5,  type:"death", name:"Napoléon Bonaparte",    note:"Empereur. Mort en 1821 en exil sur une île. « Impossible n'est pas français », disait-il." },
    { month:6,  day:29, type:"birth", name:"Saint-Exupéry",         note:"Écrivain et aviateur français. Né en 1900. Auteur du « Petit Prince »." },
    { month:7,  day:31, type:"death", name:"Saint-Exupéry",         note:"Écrivain et aviateur. Disparu en 1944 lors d'un vol de reconnaissance." },
    { month:10, day:17, type:"death", name:"Frédéric Chopin",       note:"Compositeur polonais. Né en 1810, mort en 1849 à Paris. On l'appelle le « poète du piano »." },
    { month:3,  day:26, type:"death", name:"Ludwig van Beethoven",  note:"Compositeur allemand. Né vers 1770, mort en 1827. Maître connu pour sa 9e symphonie." },
    { month:1,  day:27, type:"birth", name:"Wolfgang Amadeus Mozart", note:"Compositeur autrichien. Né en 1756. Un génie musical aux innombrables chefs-d'œuvre." },
    { month:12, day:5,  type:"death", name:"Wolfgang Amadeus Mozart", note:"Compositeur. Mort en 1791. L'un des plus grands du classicisme viennois." },
    { month:7,  day:28, type:"death", name:"Jean-Sébastien Bach",   note:"Compositeur allemand. Né en 1685, mort en 1750. Le « père de la musique », géant du baroque." },
    { month:3,  day:14, type:"birth", name:"Albert Einstein",       note:"Physicien né en Allemagne. Né en 1879. Sa théorie de la relativité a changé le monde." },
    { month:4,  day:18, type:"death", name:"Albert Einstein",       note:"Physicien. Mort en 1955. L'un des plus grands savants du XXe siècle." },
    { month:5,  day:12, type:"birth", name:"Florence Nightingale",  note:"Infirmière britannique. Née en 1820. Fondatrice des soins modernes ; le 12 mai est la Journée des infirmières." },
    { month:8,  day:13, type:"death", name:"Florence Nightingale",  note:"Infirmière. Morte en 1910. Surnommée « la dame à la lampe »." },
    { month:2,  day:12, type:"birth", name:"Charles Darwin",        note:"Naturaliste britannique. Né en 1809. Auteur de « L'Origine des espèces » et de la théorie de l'évolution." },
    { month:4,  day:19, type:"death", name:"Charles Darwin",        note:"Naturaliste. Mort en 1882. Il a profondément marqué la biologie." },
    { month:2,  day:11, type:"birth", name:"Thomas Edison",         note:"Inventeur américain. Né en 1847. Connu pour l'ampoule et le phonographe." },
    { month:10, day:18, type:"death", name:"Thomas Edison",         note:"Inventeur. Mort en 1931. On l'appelait le « magicien de Menlo Park »." },
    { month:8,  day:6,  type:"birth", name:"Alexander Fleming",     note:"Bactériologiste britannique. Né en 1881. Il a découvert le premier antibiotique, la pénicilline." },
    { month:3,  day:11, type:"death", name:"Alexander Fleming",     note:"Bactériologiste. Mort en 1955. La pénicilline a sauvé d'innombrables vies ; prix Nobel." },
    { month:3,  day:30, type:"birth", name:"Vincent van Gogh",      note:"Peintre néerlandais. Né en 1853. Célèbre pour « Les Tournesols » et « La Nuit étoilée »." },
    { month:7,  day:29, type:"death", name:"Vincent van Gogh",      note:"Peintre. Mort en 1890. Maître du postimpressionnisme reconnu après sa mort." },
    { month:10, day:25, type:"birth", name:"Pablo Picasso",         note:"Peintre espagnol. Né en 1881. Cofondateur du cubisme et géant de l'art moderne." },
    { month:4,  day:8,  type:"death", name:"Pablo Picasso",         note:"Peintre. Mort en 1973. Connu notamment pour « Guernica »." },
    { month:4,  day:16, type:"birth", name:"Charlie Chaplin",       note:"Acteur et réalisateur anglais. Né en 1889. Ses comédies muettes ont fait rire le monde entier." },
    { month:12, day:25, type:"death", name:"Charlie Chaplin",       note:"Le « Charlot ». Mort en 1977. Aimé pour des films comme « Les Temps modernes »." },
    { month:6,  day:1,  type:"birth", name:"Marilyn Monroe",        note:"Actrice américaine. Née en 1926. Une icône du cinéma des années 1950." },
    { month:8,  day:4,  type:"death", name:"Marilyn Monroe",        note:"Actrice. Morte en 1962. L'une des stars les plus durables d'Hollywood." },
    { month:1,  day:8,  type:"birth", name:"Elvis Presley",         note:"Chanteur américain. Né en 1935. Surnommé le « roi du rock'n'roll »." },
    { month:8,  day:16, type:"death", name:"Elvis Presley",         note:"Chanteur. Mort en 1977. Il a fait connaître le rock'n'roll au monde entier." },
    { month:4,  day:2,  type:"birth", name:"Hans Christian Andersen", note:"Conteur danois. Né en 1805. Célèbre pour « La Petite Sirène » et « La Petite Fille aux allumettes »." },
    { month:8,  day:4,  type:"death", name:"Hans Christian Andersen", note:"Conteur. Mort en 1875. Ses contes sont aimés dans le monde entier." },
    { month:6,  day:12, type:"birth", name:"Anne Frank",            note:"Auteure du « Journal d'Anne Frank ». Née en 1929. Une jeune fille qui écrivait, cachée des nazis." },
    /* ---- Transfert de personnalités mondiales (données indépendantes de la langue) — Lot 1 ---- */
    { month:7,  day:6,  type:"birth", name:"Frida Kahlo",           note:"Peintre mexicaine. Née en 1907. Célèbre dans le monde entier pour ses autoportraits aux couleurs vives." },
    { month:7,  day:6,  type:"birth", name:"Sylvester Stallone",    note:"Acteur américain. Né en 1946. Connu pour les films « Rocky » et « Rambo »." },
    { month:7,  day:6,  type:"death", name:"Louis Armstrong",       note:"Musicien de jazz américain. Mort en 1971. Aimé pour « What a Wonderful World »." },
    { month:7,  day:6,  type:"death", name:"Odilon Redon",          note:"Peintre français. Mort en 1916. Connu pour son style onirique." },
    { month:5,  day:4,  type:"birth", name:"Audrey Hepburn",        note:"Actrice. Née en 1929. Connue pour « Vacances romaines » ; elle s'est aussi consacrée à des œuvres humanitaires." },
    { month:1,  day:20, type:"death", name:"Audrey Hepburn",        note:"Actrice. Morte en 1993. Aimée pour des films comme « Vacances romaines »." },
    { month:10, day:9,  type:"birth", name:"John Lennon",           note:"Musicien britannique. Né en 1940. Connu comme membre des Beatles." },
    { month:8,  day:26, type:"birth", name:"Mère Teresa",           note:"Religieuse catholique. Née en 1910. Elle a aidé les pauvres et reçu le prix Nobel de la paix." },
    { month:9,  day:5,  type:"death", name:"Mère Teresa",           note:"Religieuse. Morte en 1997. Vénérée comme « la mère des pauvres »." },
    { month:10, day:2,  type:"birth", name:"Mahatma Gandhi",        note:"Guide de l'indépendance de l'Inde. Né en 1869. Il a mené la résistance non-violente." },
    { month:6,  day:27, type:"birth", name:"Helen Keller",          note:"Militante américaine. Née en 1880. Sourde et aveugle, elle a inspiré le monde entier." },
    { month:6,  day:1,  type:"death", name:"Helen Keller",          note:"Militante sociale. Morte en 1968. Elle a agi par-delà son handicap." },
    { month:2,  day:12, type:"birth", name:"Abraham Lincoln",       note:"16e président des États-Unis. Né en 1809. Il a fait avancer l'abolition de l'esclavage." },
    { month:8,  day:29, type:"birth", name:"Michael Jackson",       note:"Chanteur américain. Né en 1958. On l'appelait le « roi de la pop »." },
    { month:12, day:5,  type:"birth", name:"Walt Disney",           note:"Créateur de dessins animés et entrepreneur américain. Né en 1901. Créateur de Mickey Mouse." },
    { month:12, day:15, type:"death", name:"Walt Disney",           note:"Créateur de dessins animés. Mort en 1966. Fondateur de Disneyland." },
    { month:7,  day:21, type:"birth", name:"Ernest Hemingway",      note:"Romancier américain. Né en 1899. Prix Nobel, connu pour « Le Vieil Homme et la Mer »." },
    { month:5,  day:29, type:"birth", name:"John F. Kennedy",       note:"35e président des États-Unis. Né en 1917. Devenu président jeune, il a séduit les foules." },
    { month:11, day:30, type:"birth", name:"Winston Churchill",     note:"Homme d'État britannique. Né en 1874. Premier ministre durant la Seconde Guerre mondiale, célèbre pour ses discours." },
    { month:1,  day:24, type:"death", name:"Winston Churchill",     note:"Premier ministre britannique. Mort en 1965. Il a aussi reçu le prix Nobel de littérature." },
    { month:5,  day:7,  type:"birth", name:"Piotr Tchaïkovski",     note:"Compositeur russe. Né en 1840. Connu pour « Le Lac des cygnes » et « Casse-Noisette »." },
    { month:11, day:6,  type:"death", name:"Piotr Tchaïkovski",     note:"Compositeur. Mort en 1893. Il a laissé de superbes musiques de ballet." },
    { month:2,  day:6,  type:"birth", name:"Babe Ruth",             note:"Joueur de baseball américain. Né en 1895. Un frappeur de légende." },
    { month:8,  day:16, type:"death", name:"Babe Ruth",             note:"Joueur de baseball. Mort en 1948. Une icône du baseball américain." },
    { month:1,  day:31, type:"birth", name:"Franz Schubert",        note:"Compositeur autrichien. Né en 1797. « Roi du lied », connu pour « Le Roi des aulnes »." },
    { month:11, day:19, type:"death", name:"Franz Schubert",        note:"Compositeur. Mort en 1828 à seulement 31 ans. Il a laissé la « Symphonie inachevée »." },
    { month:5,  day:7,  type:"birth", name:"Johannes Brahms",       note:"Compositeur allemand. Né en 1833. L'un des « trois B » avec Bach et Beethoven." },
    { month:4,  day:3,  type:"death", name:"Johannes Brahms",       note:"Compositeur. Mort en 1897. Aimé pour sa « Berceuse »." },
    { month:5,  day:22, type:"birth", name:"Richard Wagner",        note:"Compositeur allemand. Né en 1813. Célèbre pour ses grands drames lyriques." },
    { month:2,  day:13, type:"death", name:"Richard Wagner",        note:"Compositeur. Mort en 1883. Il a laissé « L'Anneau du Nibelung »." },
    { month:10, day:10, type:"birth", name:"Giuseppe Verdi",        note:"Compositeur italien. Né en 1813. Connu pour des opéras comme « La Traviata » et « Aïda »." },
    { month:1,  day:27, type:"death", name:"Giuseppe Verdi",        note:"Compositeur. Mort en 1901. Un maître de l'opéra italien." },
    { month:11, day:30, type:"birth", name:"Mark Twain",            note:"Écrivain américain. Né en 1835. Connu pour « Les Aventures de Tom Sawyer »." },
    { month:4,  day:21, type:"death", name:"Mark Twain",            note:"Écrivain. Mort en 1910. Ses œuvres pleines d'humour et d'ironie sont toujours appréciées." },
    { month:5,  day:11, type:"birth", name:"Salvador Dalí",         note:"Peintre espagnol. Né en 1904. Connu pour ses montres molles — un maître du surréalisme." },
    { month:1,  day:23, type:"death", name:"Salvador Dalí",         note:"Peintre. Mort en 1989. Célèbre aussi pour sa moustache singulière." },
    { month:2,  day:8,  type:"birth", name:"James Dean",            note:"Acteur américain. Né en 1931. Connu pour « À l'est d'Éden » — une idole de la jeunesse." },
    { month:12, day:22, type:"birth", name:"Giacomo Puccini",       note:"Compositeur italien. Né en 1858. Connu pour des opéras comme « Madame Butterfly » et « Tosca »." },
    { month:11, day:29, type:"death", name:"Giacomo Puccini",       note:"Compositeur. Mort en 1924. Une grande figure de l'opéra italien." },
    { month:9,  day:8,  type:"birth", name:"Antonín Dvořák",        note:"Compositeur tchèque. Né en 1841. Connu pour la symphonie « Du Nouveau Monde »." },
    { month:5,  day:1,  type:"death", name:"Antonín Dvořák",        note:"Compositeur. Mort en 1904. Il a tissé les mélodies de son pays dans ses œuvres." },
    { month:3,  day:4,  type:"birth", name:"Antonio Vivaldi",       note:"Compositeur italien. Né en 1678. Connu pour les concertos « Les Quatre Saisons »." },
    { month:7,  day:28, type:"death", name:"Antonio Vivaldi",       note:"Compositeur. Mort en 1741. L'un des grands maîtres du baroque." },
    { month:8,  day:28, type:"birth", name:"Goethe",                note:"Grand écrivain allemand. Né en 1749. Connu pour « Faust » et « Les Souffrances du jeune Werther »." },
    { month:3,  day:22, type:"death", name:"Goethe",                note:"Écrivain. Mort en 1832. Un poète et auteur emblématique de l'Allemagne." },
    { month:10, day:21, type:"birth", name:"Alfred Nobel",          note:"Inventeur suédois. Né en 1833. Il a inventé la dynamite et fondé les prix Nobel." },
    { month:12, day:10, type:"death", name:"Alfred Nobel",          note:"Inventeur. Mort en 1896. Le 10 décembre reste le jour de la remise des prix Nobel." },
    { month:3,  day:3,  type:"birth", name:"Alexander Graham Bell", note:"Inventeur. Né en 1847. Il a inventé le premier téléphone pratique." },
    { month:8,  day:2,  type:"death", name:"Alexander Graham Bell", note:"Inventeur. Mort en 1922. Avec le téléphone, il a changé le monde." },
    { month:8,  day:29, type:"birth", name:"Ingrid Bergman",        note:"Actrice suédoise. Née en 1915. Connue pour « Casablanca »." },
    { month:8,  day:29, type:"death", name:"Ingrid Bergman",        note:"Actrice. Morte en 1982, le jour même de son anniversaire, le 29 août." },
    { month:11, day:12, type:"birth", name:"Grace Kelly",           note:"Actrice américaine. Née en 1929. D'actrice hollywoodienne, elle devint princesse de Monaco." },
    { month:5,  day:26, type:"birth", name:"John Wayne",            note:"Acteur américain. Né en 1907. Une grande star du western." },
    { month:6,  day:11, type:"death", name:"John Wayne",            note:"Acteur. Mort en 1979. Surnommé affectueusement « Duke »." },
    { month:12, day:12, type:"birth", name:"Frank Sinatra",         note:"Chanteur et acteur américain. Né en 1915. Connu pour « My Way »." },
    { month:5,  day:14, type:"death", name:"Frank Sinatra",         note:"Chanteur et acteur. Mort en 1998. Un artiste emblématique du XXe siècle." },
    { month:11, day:20, type:"death", name:"Léon Tolstoï",          note:"Écrivain russe. Mort en 1910. Connu pour « Guerre et Paix » et « Anna Karénine »." },
    { month:2,  day:9,  type:"death", name:"Fiodor Dostoïevski",    note:"Écrivain russe. Mort en 1881. Connu pour « Crime et Châtiment » et « Les Frères Karamazov »." },
    { month:7,  day:14, type:"birth", name:"Gustav Klimt",          note:"Peintre autrichien. Né en 1862. Connu pour « Le Baiser », rehaussé de feuilles d'or." },
    { month:2,  day:6,  type:"death", name:"Gustav Klimt",          note:"Peintre. Mort en 1918. Il a mené la Sécession viennoise." },
    { month:12, day:12, type:"birth", name:"Edvard Munch",          note:"Peintre norvégien. Né en 1863. Mondialement connu comme auteur du « Cri »." },
    { month:1,  day:23, type:"death", name:"Edvard Munch",          note:"Peintre. Mort en 1944. Un expressionniste qui a peint l'angoisse et la solitude." },
    { month:2,  day:7,  type:"birth", name:"Charles Dickens",       note:"Écrivain anglais. Né en 1812. Connu pour « Un chant de Noël » et « Oliver Twist »." },
    { month:6,  day:9,  type:"death", name:"Charles Dickens",       note:"Écrivain. Mort en 1870. Un auteur national attentif aux plus faibles." },
    { month:2,  day:3,  type:"birth", name:"Felix Mendelssohn",     note:"Compositeur allemand. Né en 1809. Connu pour la « Marche nuptiale » et « Le Songe d'une nuit d'été »." },
    { month:11, day:4,  type:"death", name:"Felix Mendelssohn",     note:"Compositeur. Mort en 1847. Une grande figure du romantisme." },
    { month:6,  day:8,  type:"birth", name:"Robert Schumann",       note:"Compositeur allemand. Né en 1810. Connu pour des pièces pour piano comme « Rêverie » et pour ses lieder." },
    { month:7,  day:29, type:"death", name:"Robert Schumann",       note:"Compositeur. Mort en 1856. On l'appelle le poète de la musique romantique." },
    { month:10, day:22, type:"birth", name:"Franz Liszt",           note:"Compositeur hongrois. Né en 1811. Connu pour ses « Rhapsodies hongroises » — le « magicien du piano »." },
    { month:7,  day:31, type:"death", name:"Franz Liszt",           note:"Compositeur. Mort en 1886. Célèbre aussi comme pianiste virtuose." },
    { month:8,  day:22, type:"birth", name:"Claude Debussy",        note:"Compositeur français. Né en 1862. Connu pour « Clair de lune » et « La Mer »." },
    { month:3,  day:25, type:"death", name:"Claude Debussy",        note:"Compositeur. Mort en 1918. Un maître de la musique impressionniste." },
    { month:1,  day:4,  type:"birth", name:"Louis Braille",         note:"Inventeur français de l'écriture pour aveugles. Né en 1809. Devenu aveugle lui-même, il créa l'écriture en points." },
    { month:1,  day:6,  type:"death", name:"Louis Braille",         note:"Inventeur du braille. Mort en 1852. Il a apporté la lecture aux aveugles du monde entier." },
    { month:2,  day:4,  type:"birth", name:"Rosa Parks",            note:"Militante américaine des droits civiques. Née en 1913. Son refus de céder sa place dans un bus a lancé un mouvement." },
    { month:10, day:24, type:"death", name:"Rosa Parks",            note:"Militante des droits civiques. Morte en 2005. Surnommée « la mère du mouvement des droits civiques »." },
    { month:2,  day:2,  type:"birth", name:"James Joyce",           note:"Écrivain irlandais. Né en 1882. Auteur d'« Ulysse », une œuvre majeure du XXe siècle." },
    { month:1,  day:13, type:"death", name:"James Joyce",           note:"Écrivain. Mort en 1941. Il a marqué la littérature moderne par des formes nouvelles." },
    { month:2,  day:29, type:"birth", name:"Gioachino Rossini",     note:"Compositeur italien. Né en 1792, un jour bissextile. Connu pour « Le Barbier de Séville »." },
    { month:11, day:13, type:"death", name:"Gioachino Rossini",     note:"Compositeur. Mort en 1868. Apprécié pour ses opéras enjoués." },
    { month:3,  day:24, type:"birth", name:"Harry Houdini",         note:"Artiste d'évasion américain. Né en 1874. Surnommé le « roi de l'évasion », il a étonné le monde." },
    { month:10, day:31, type:"death", name:"Harry Houdini",         note:"Magicien. Mort en 1926, justement le jour d'Halloween, le 31 octobre." },
    { month:5,  day:31, type:"birth", name:"Clint Eastwood",        note:"Acteur et réalisateur américain. Né en 1930. Connu pour les westerns et « L'Inspecteur Harry »." },
    { month:8,  day:9,  type:"birth", name:"Jean Piaget",           note:"Psychologue suisse. Né en 1896. Il a étudié le développement de l'esprit chez l'enfant." },
    { month:2,  day:23, type:"birth", name:"Georg Friedrich Haendel", note:"Compositeur né en Allemagne. Né en 1685. Connu pour l'oratorio « Le Messie »." },
    { month:4,  day:14, type:"death", name:"Georg Friedrich Haendel", note:"Compositeur. Mort en 1759. Actif en Angleterre, il a laissé de solennelles œuvres chorales." },
    { month:3,  day:31, type:"birth", name:"Joseph Haydn",          note:"Compositeur autrichien. Né en 1732. « Père de la symphonie », auteur d'innombrables œuvres." },
    { month:5,  day:31, type:"death", name:"Joseph Haydn",          note:"Compositeur. Mort en 1809. Il a façonné le quatuor à cordes et la symphonie." },
    /* ---- Lot 2 ---- */
    { month:7,  day:7,  type:"birth", name:"Gustav Mahler",         note:"Compositeur et chef d'orchestre autrichien. Né en 1860. Connu pour ses vastes symphonies." },
    { month:5,  day:18, type:"death", name:"Gustav Mahler",         note:"Compositeur. Mort en 1911. Il a fait le lien entre la musique du XIXe et du XXe siècle." },
    { month:6,  day:15, type:"birth", name:"Edvard Grieg",          note:"Compositeur norvégien. Né en 1843. Connu pour la suite « Peer Gynt »." },
    { month:9,  day:4,  type:"death", name:"Edvard Grieg",          note:"Compositeur. Mort en 1907. Il a porté les mélodies de Norvège dans le monde." },
    { month:12, day:8,  type:"birth", name:"Jean Sibelius",         note:"Compositeur finlandais. Né en 1865. Connu pour le poème symphonique « Finlandia »." },
    { month:9,  day:20, type:"death", name:"Jean Sibelius",         note:"Compositeur. Mort en 1957. Le grand compositeur national de la Finlande." },
    { month:10, day:9,  type:"birth", name:"Camille Saint-Saëns",   note:"Compositeur français. Né en 1835. Connu pour « Le Carnaval des animaux »." },
    { month:12, day:16, type:"death", name:"Camille Saint-Saëns",   note:"Compositeur. Mort en 1921. Il a aussi laissé de belles œuvres pour orgue et concerto." },
    { month:10, day:25, type:"birth", name:"Georges Bizet",         note:"Compositeur français. Né en 1838. Connu pour l'opéra « Carmen »." },
    { month:6,  day:3,  type:"death", name:"Georges Bizet",         note:"Compositeur. Mort en 1875. « Carmen » est toujours aimé dans le monde entier." },
    { month:4,  day:15, type:"birth", name:"Léonard de Vinci",      note:"Artiste et savant italien. Né en 1452. Auteur de « La Joconde » et de « La Cène », un génie universel." },
    { month:5,  day:2,  type:"death", name:"Léonard de Vinci",      note:"Génie universel. Mort en 1519. Il a marqué la peinture, la science et la technique." },
    { month:3,  day:6,  type:"birth", name:"Michel-Ange",           note:"Artiste italien. Né en 1475. Connu pour le « David » et le plafond de la chapelle Sixtine." },
    { month:2,  day:18, type:"death", name:"Michel-Ange",           note:"Artiste. Mort en 1564. Un maître de la sculpture, de la peinture et de l'architecture." },
    { month:7,  day:15, type:"birth", name:"Rembrandt",             note:"Peintre néerlandais. Né en 1606. Un maître de la lumière et de l'ombre du Siècle d'or." },
    { month:10, day:4,  type:"death", name:"Rembrandt",             note:"Peintre. Mort en 1669. Connu aussi pour ses nombreux autoportraits." },
    { month:11, day:12, type:"birth", name:"Auguste Rodin",         note:"Sculpteur français. Né en 1840. Connu pour « Le Penseur » — père de la sculpture moderne." },
    { month:11, day:17, type:"death", name:"Auguste Rodin",         note:"Sculpteur. Mort en 1917. Il a représenté le corps humain avec vie." },
    { month:6,  day:25, type:"birth", name:"Antoni Gaudí",          note:"Architecte espagnol. Né en 1852. Il a conçu la Sagrada Família." },
    { month:6,  day:10, type:"death", name:"Antoni Gaudí",          note:"Architecte. Mort en 1926. Ses bâtiments singuliers ornent Barcelone." },
    { month:12, day:18, type:"birth", name:"Paul Klee",             note:"Peintre né en Suisse. Né en 1879. Connu pour des œuvres poétiques et colorées." },
    { month:6,  day:29, type:"death", name:"Paul Klee",             note:"Peintre. Mort en 1940. Il a laissé près de 9000 œuvres." },
    { month:7,  day:10, type:"birth", name:"Nikola Tesla",          note:"Inventeur. Né en 1856. Il a contribué à l'usage du courant alternatif." },
    { month:1,  day:7,  type:"death", name:"Nikola Tesla",          note:"Inventeur. Mort en 1943. Il a posé les bases de l'électricité moderne." },
    { month:9,  day:22, type:"birth", name:"Michael Faraday",       note:"Savant britannique. Né en 1791. Il a découvert l'induction électromagnétique." },
    { month:8,  day:25, type:"death", name:"Michael Faraday",       note:"Savant. Mort en 1867. Ses travaux sur l'électricité et le magnétisme ont changé le monde." },
    { month:4,  day:25, type:"birth", name:"Guglielmo Marconi",     note:"Inventeur italien. Né en 1874. « Père de la radio », prix Nobel." },
    { month:7,  day:20, type:"death", name:"Guglielmo Marconi",     note:"Inventeur. Mort en 1937. Il a réalisé la communication sans fil par-delà les mers." },
    { month:3,  day:27, type:"birth", name:"Wilhelm Röntgen",       note:"Physicien allemand. Né en 1845. Il a découvert les rayons X et reçu le premier prix Nobel de physique." },
    { month:2,  day:10, type:"death", name:"Wilhelm Röntgen",       note:"Physicien. Mort en 1923. Ses rayons sont essentiels à la médecine." },
    { month:2,  day:8,  type:"birth", name:"Jules Verne",           note:"Écrivain français. Né en 1828. « Père de la science-fiction », connu pour « Vingt mille lieues sous les mers »." },
    { month:3,  day:24, type:"death", name:"Jules Verne",           note:"Écrivain. Mort en 1905. Ses aventures fascinent encore les lecteurs." },
    { month:12, day:16, type:"birth", name:"Jane Austen",           note:"Romancière anglaise. Née en 1775. Connue pour « Orgueil et Préjugés »." },
    { month:7,  day:18, type:"death", name:"Jane Austen",           note:"Romancière. Morte en 1817. Elle a dépeint finement la société anglaise." },
    { month:4,  day:23, type:"death", name:"William Shakespeare",   note:"Dramaturge anglais. Mort en 1616. Il a écrit « Hamlet » et « Roméo et Juliette »." },
    { month:10, day:16, type:"birth", name:"Oscar Wilde",           note:"Écrivain irlandais. Né en 1854. Connu pour « Le Prince heureux »." },
    { month:11, day:30, type:"death", name:"Oscar Wilde",           note:"Écrivain. Mort en 1900. Il a laissé des pièces et des contes pleins d'esprit." },
    { month:9,  day:15, type:"birth", name:"Agatha Christie",       note:"Écrivaine anglaise. Née en 1890. « Reine du crime » et créatrice d'Hercule Poirot." },
    { month:1,  day:12, type:"death", name:"Agatha Christie",       note:"Écrivaine. Morte en 1976. L'une des romancières policières les plus lues au monde." },
    { month:1,  day:4,  type:"birth", name:"Jacob Grimm",           note:"Érudit allemand. Né en 1785. Avec son frère, il a réuni les « Contes de Grimm »." },
    { month:9,  day:20, type:"death", name:"Jacob Grimm",           note:"Érudit. Mort en 1863. Important pour la linguistique et l'étude des contes." },
    { month:2,  day:24, type:"birth", name:"Wilhelm Grimm",         note:"Écrivain allemand. Né en 1786. Avec son frère, il a publié les « Contes de Grimm »." },
    { month:12, day:16, type:"death", name:"Wilhelm Grimm",         note:"Écrivain. Mort en 1859. « Le Petit Chaperon rouge » et « Blanche-Neige » vivent encore." },
    { month:7,  day:20, type:"birth", name:"Gregor Mendel",         note:"Moine et savant autrichien. Né en 1822. Il a découvert les lois de l'hérédité avec des pois." },
    { month:1,  day:6,  type:"death", name:"Gregor Mendel",         note:"Savant. Mort en 1884. Surnommé le « père de la génétique »." },
    { month:4,  day:20, type:"birth", name:"Joan Miró",             note:"Peintre espagnol. Né en 1893. Connu pour des tableaux gais, parsemés de signes et d'étoiles." },
    { month:12, day:25, type:"death", name:"Joan Miró",             note:"Peintre. Mort en 1983. Une grande figure du surréalisme." },
    { month:6,  day:28, type:"birth", name:"Pierre Paul Rubens",    note:"Peintre flamand. Né en 1577. Un maître de la peinture baroque pleine de mouvement." },
    { month:5,  day:30, type:"death", name:"Pierre Paul Rubens",    note:"Peintre. Mort en 1640. Il fut aussi diplomate." },
    { month:3,  day:30, type:"birth", name:"Francisco de Goya",     note:"Peintre espagnol. Né en 1746. Peintre de cour au regard perçant sur l'humain." },
    { month:4,  day:16, type:"death", name:"Francisco de Goya",     note:"Peintre. Mort en 1828. On le considère comme un précurseur de la peinture moderne." },
    { month:1,  day:23, type:"birth", name:"Édouard Manet",         note:"Peintre français. Né en 1832. Avec « Le Déjeuner sur l'herbe », il a ouvert la voie à l'impressionnisme." },
    { month:4,  day:30, type:"death", name:"Édouard Manet",         note:"Peintre. Mort en 1883. L'un des pères de la peinture moderne." },
    { month:11, day:24, type:"birth", name:"Henri de Toulouse-Lautrec", note:"Peintre français. Né en 1864. Connu pour ses affiches des cabarets et danseuses de Paris." },
    { month:9,  day:9,  type:"death", name:"Henri de Toulouse-Lautrec", note:"Peintre. Mort en 1901. Il a profondément marqué l'art de l'affiche." },
    { month:7,  day:12, type:"birth", name:"Amedeo Modigliani",     note:"Peintre italien. Né en 1884. Connu pour ses portraits aux cous allongés." },
    { month:1,  day:24, type:"death", name:"Amedeo Modigliani",     note:"Peintre. Mort en 1920. Une figure de l'« École de Paris »." },
    { month:3,  day:7,  type:"birth", name:"Maurice Ravel",         note:"Compositeur français. Né en 1875. Connu pour le « Boléro »." },
    { month:12, day:28, type:"death", name:"Maurice Ravel",         note:"Compositeur. Mort en 1937. Connu pour son orchestration fine et colorée." },
    { month:9,  day:26, type:"birth", name:"George Gershwin",       note:"Compositeur américain. Né en 1898. Connu pour « Rhapsody in Blue »." },
    { month:7,  day:11, type:"death", name:"George Gershwin",       note:"Compositeur. Mort en 1937. Il a uni la musique classique et le jazz." },
    { month:11, day:6,  type:"birth", name:"John Philip Sousa",     note:"Compositeur américain. Né en 1854. « Roi de la marche », connu pour « The Stars and Stripes Forever »." },
    { month:3,  day:6,  type:"death", name:"John Philip Sousa",     note:"Compositeur. Mort en 1932. Il a laissé de nombreuses marches célèbres." },
    { month:6,  day:2,  type:"birth", name:"Edward Elgar",          note:"Compositeur anglais. Né en 1857. Connu pour « Pomp and Circumstance »." },
    { month:2,  day:23, type:"death", name:"Edward Elgar",          note:"Compositeur. Mort en 1934. Une figure majeure de la musique anglaise." },
    { month:1,  day:27, type:"birth", name:"Lewis Carroll",         note:"Écrivain et mathématicien anglais. Né en 1832. Connu pour « Alice au pays des merveilles »." },
    { month:1,  day:14, type:"death", name:"Lewis Carroll",         note:"Écrivain. Mort en 1898. Il fut aussi mathématicien et photographe." },
    { month:5,  day:22, type:"birth", name:"Arthur Conan Doyle",    note:"Écrivain britannique. Né en 1859. Créateur du détective Sherlock Holmes." },
    { month:7,  day:7,  type:"death", name:"Arthur Conan Doyle",    note:"Écrivain. Mort en 1930. Il était aussi médecin." },
    { month:2,  day:18, type:"birth", name:"Alessandro Volta",      note:"Physicien italien. Né en 1745. Il a inventé la pile ; l'unité volt porte son nom." },
    { month:3,  day:5,  type:"death", name:"Alessandro Volta",      note:"Physicien. Mort en 1827. Un pionnier de l'étude de l'électricité." },
    { month:1,  day:20, type:"birth", name:"André-Marie Ampère",    note:"Physicien français. Né en 1775. Connu pour ses travaux sur le courant ; l'unité ampère porte son nom." },
    { month:6,  day:10, type:"death", name:"André-Marie Ampère",    note:"Physicien. Mort en 1836. Il a fondé l'électrodynamique." },
    { month:3,  day:16, type:"birth", name:"Georg Ohm",             note:"Physicien allemand. Né en 1789. Connu pour la « loi d'Ohm » sur la résistance électrique." },
    { month:7,  day:6,  type:"death", name:"Georg Ohm",             note:"Physicien. Mort en 1854. L'unité ohm porte son nom." },
    { month:10, day:7,  type:"birth", name:"Niels Bohr",            note:"Physicien danois. Né en 1885. Il a expliqué la structure de l'atome et reçu le prix Nobel." },
    { month:11, day:18, type:"death", name:"Niels Bohr",            note:"Physicien. Mort en 1962. L'un des plus grands physiciens du XXe siècle." },
    { month:4,  day:23, type:"birth", name:"Max Planck",            note:"Physicien allemand. Né en 1858. Fondateur de la théorie des quanta et prix Nobel." },
    { month:10, day:4,  type:"death", name:"Max Planck",            note:"Physicien. Mort en 1947. Il a posé les bases de la physique moderne." },
    { month:1,  day:19, type:"birth", name:"Edgar Allan Poe",       note:"Écrivain américain. Né en 1809. Pionnier du roman policier et maître du fantastique." },
    { month:10, day:7,  type:"death", name:"Edgar Allan Poe",       note:"Écrivain. Mort en 1849. Connu aussi comme poète et critique." },
    { month:8,  day:1,  type:"birth", name:"Herman Melville",       note:"Écrivain américain. Né en 1819. Connu pour « Moby Dick »." },
    { month:9,  day:28, type:"death", name:"Herman Melville",       note:"Écrivain. Mort en 1891. « Moby Dick » fut reconnu bien plus tard." },
    { month:4,  day:21, type:"birth", name:"Charlotte Brontë",      note:"Écrivaine anglaise. Née en 1816. Connue pour « Jane Eyre »." },
    { month:3,  day:31, type:"death", name:"Charlotte Brontë",      note:"Écrivaine. Morte en 1855. L'aînée des trois sœurs Brontë." },
    { month:11, day:13, type:"birth", name:"Robert Louis Stevenson", note:"Écrivain britannique. Né en 1850. Connu pour « L'Île au trésor » et « Docteur Jekyll et M. Hyde »." },
    { month:12, day:3,  type:"death", name:"Robert Louis Stevenson", note:"Écrivain. Mort en 1894. Il a passé ses dernières années aux Samoa, dans le Pacifique." },
    { month:5,  day:20, type:"birth", name:"Honoré de Balzac",      note:"Écrivain français. Né en 1799. Connu pour le cycle « La Comédie humaine »." },
    { month:8,  day:18, type:"death", name:"Honoré de Balzac",      note:"Écrivain. Mort en 1850. Il a dépeint l'homme et la société avec acuité." },
    { month:7,  day:24, type:"birth", name:"Alexandre Dumas",       note:"Écrivain français. Né en 1802. Connu pour « Les Trois Mousquetaires » et « Le Comte de Monte-Cristo »." },
    { month:12, day:5,  type:"death", name:"Alexandre Dumas",       note:"Écrivain. Mort en 1870. Ses romans d'aventures sont aimés dans le monde entier." },
    { month:4,  day:2,  type:"birth", name:"Émile Zola",            note:"Écrivain français. Né en 1840. Une grande figure du roman naturaliste." },
    { month:9,  day:29, type:"death", name:"Émile Zola",            note:"Écrivain. Mort en 1902. Connu aussi pour son article « J'accuse »." },
    { month:12, day:30, type:"birth", name:"Rudyard Kipling",       note:"Écrivain britannique. Né en 1865. Connu pour « Le Livre de la jungle »." },
    { month:1,  day:18, type:"death", name:"Rudyard Kipling",       note:"Écrivain. Mort en 1936. Estimé aussi comme poète et conteur." },
    { month:1,  day:12, type:"birth", name:"Jack London",           note:"Écrivain américain. Né en 1876. Connu pour « L'Appel de la forêt » et « Croc-Blanc »." },
    { month:11, day:22, type:"death", name:"Jack London",           note:"Écrivain. Mort en 1916. Il a mené une vie mouvementée et aventureuse." },
    /* ---- Lot 3 ---- */
    { month:5,  day:7,  type:"birth", name:"Rabindranath Tagore",   note:"Poète indien. Né en 1861. Premier Asiatique à recevoir le prix Nobel de littérature." },
    { month:8,  day:7,  type:"death", name:"Rabindranath Tagore",   note:"Poète. Mort en 1941. Il a composé les hymnes de l'Inde et du Bangladesh." },
    { month:9,  day:4,  type:"birth", name:"Anton Bruckner",        note:"Compositeur autrichien. Né en 1824. Connu pour ses vastes symphonies et ses œuvres sacrées." },
    { month:10, day:11, type:"death", name:"Anton Bruckner",        note:"Compositeur. Mort en 1896. Estimé aussi comme organiste." },
    { month:6,  day:20, type:"birth", name:"Jacques Offenbach",     note:"Compositeur français. Né en 1819. Il a réjoui le public avec ses opérettes." },
    { month:10, day:5,  type:"death", name:"Jacques Offenbach",     note:"Compositeur. Mort en 1880. Connu pour « Orphée aux Enfers »." },
    { month:5,  day:12, type:"birth", name:"Gabriel Fauré",         note:"Compositeur français. Né en 1845. Connu pour son « Requiem » et sa « Sicilienne »." },
    { month:11, day:4,  type:"death", name:"Gabriel Fauré",         note:"Compositeur. Mort en 1924. Une figure majeure de la musique française moderne." },
    { month:10, day:27, type:"birth", name:"Niccolò Paganini",      note:"Musicien italien. Né en 1782. Un violoniste de légende d'une virtuosité inouïe." },
    { month:5,  day:27, type:"death", name:"Niccolò Paganini",      note:"Musicien. Mort en 1840. Connu pour ses « 24 Caprices »." },
    { month:12, day:2,  type:"birth", name:"Georges Seurat",        note:"Peintre français. Né en 1859. Il a inventé le pointillisme, la peinture par petits points." },
    { month:3,  day:29, type:"death", name:"Georges Seurat",        note:"Peintre. Mort en 1891 à 31 ans. Connu pour « Un dimanche après-midi à l'île de la Grande Jatte »." },
    { month:7,  day:10, type:"birth", name:"Camille Pissarro",      note:"Peintre français. Né en 1830. Le plus âgé et le plus fidèle des impressionnistes." },
    { month:11, day:13, type:"death", name:"Camille Pissarro",      note:"Peintre. Mort en 1903. Le seul à avoir participé à toutes les expositions impressionnistes." },
    { month:2,  day:19, type:"birth", name:"Nicolas Copernic",      note:"Astronome polonais. Né en 1473. Il a proposé le système héliocentrique." },
    { month:5,  day:24, type:"death", name:"Nicolas Copernic",      note:"Astronome. Mort en 1543. Il a profondément changé la vision du monde." },
    { month:12, day:27, type:"birth", name:"Johannes Kepler",       note:"Astronome allemand. Né en 1571. Il a découvert les lois du mouvement des planètes." },
    { month:11, day:15, type:"death", name:"Johannes Kepler",       note:"Astronome. Mort en 1630. L'un des fondateurs de l'astronomie moderne." },
    { month:6,  day:13, type:"birth", name:"James Clerk Maxwell",   note:"Physicien britannique. Né en 1831. Il a unifié l'électricité et le magnétisme et montré que la lumière est une onde électromagnétique." },
    { month:11, day:5,  type:"death", name:"James Clerk Maxwell",   note:"Physicien. Mort en 1879. On le cite aux côtés de Newton et d'Einstein." },
    { month:4,  day:27, type:"birth", name:"Samuel Morse",          note:"Inventeur américain. Né en 1791. Il a créé le télégraphe et le « code Morse »." },
    { month:4,  day:2,  type:"death", name:"Samuel Morse",          note:"Inventeur. Mort en 1872. Il était aussi peintre à l'origine." },
    { month:12, day:12, type:"birth", name:"Gustave Flaubert",      note:"Écrivain français. Né en 1821. Connu pour « Madame Bovary »." },
    { month:5,  day:8,  type:"death", name:"Gustave Flaubert",      note:"Écrivain. Mort en 1880. Célèbre pour son style ciselé à l'extrême." },
    { month:8,  day:5,  type:"birth", name:"Guy de Maupassant",     note:"Écrivain français. Né en 1850. Connu pour « La Parure » et « Une vie »." },
    { month:7,  day:6,  type:"death", name:"Guy de Maupassant",     note:"Écrivain. Mort en 1893. Un maître de la nouvelle moderne." },
    { month:11, day:29, type:"birth", name:"Gaetano Donizetti",     note:"Compositeur italien. Né en 1797. Connu pour des opéras bel canto comme « L'Élixir d'amour »." },
    { month:4,  day:8,  type:"death", name:"Gaetano Donizetti",     note:"Compositeur. Mort en 1848. Il a laissé plus de 70 opéras." },
    { month:11, day:3,  type:"birth", name:"Vincenzo Bellini",      note:"Compositeur italien. Né en 1801. Connu pour des opéras aux belles mélodies comme « Norma »." },
    { month:9,  day:23, type:"death", name:"Vincenzo Bellini",      note:"Compositeur. Mort en 1835 à 33 ans. Une figure du bel canto." },
    { month:6,  day:5,  type:"death", name:"Carl Maria von Weber",  note:"Compositeur allemand. Mort en 1826. Avec l'opéra « Le Freischütz », il a ouvert l'opéra romantique allemand." },
    { month:6,  day:17, type:"birth", name:"M. C. Escher",          note:"Graveur néerlandais. Né en 1898. Connu pour des images étranges, comme des illusions d'optique." },
    { month:3,  day:27, type:"death", name:"M. C. Escher",          note:"Graveur. Mort en 1972. Ses œuvres d'inspiration mathématique ont étonné le monde." },
    { month:7,  day:22, type:"birth", name:"Edward Hopper",         note:"Peintre américain. Né en 1882. Connu pour « Nighthawks », qui montre le silence de la ville." },
    { month:5,  day:15, type:"death", name:"Edward Hopper",         note:"Peintre. Mort en 1967. Un grand peintre réaliste du XXe siècle." },
    { month:2,  day:3,  type:"birth", name:"Norman Rockwell",       note:"Peintre américain. Né en 1894. Aimé pour ses scènes chaleureuses du quotidien en couverture de magazines." },
    { month:11, day:8,  type:"death", name:"Norman Rockwell",       note:"Peintre et illustrateur. Mort en 1978. Il a peint la vie américaine." },
    { month:12, day:11, type:"birth", name:"Robert Koch",           note:"Bactériologiste allemand. Né en 1843. Il a découvert les bacilles de la tuberculose et du choléra ; prix Nobel." },
    { month:5,  day:27, type:"death", name:"Robert Koch",           note:"Bactériologiste. Mort en 1910. Un père de la bactériologie moderne." },
    { month:11, day:25, type:"birth", name:"Carl Benz",             note:"Ingénieur allemand. Né en 1844. Il a construit la première automobile à essence pratique." },
    { month:4,  day:4,  type:"death", name:"Carl Benz",             note:"Ingénieur. Mort en 1929. Surnommé le « père de l'automobile »." },
    { month:7,  day:30, type:"birth", name:"Henry Ford",            note:"Entrepreneur américain. Né en 1863. Il a rendu l'automobile abordable grâce à la production de masse." },
    { month:4,  day:7,  type:"death", name:"Henry Ford",            note:"Entrepreneur. Mort en 1947. Fondateur de la Ford Motor Company." },
    { month:11, day:30, type:"birth", name:"Jonathan Swift",        note:"Écrivain irlandais. Né en 1667. Connu pour « Les Voyages de Gulliver »." },
    { month:10, day:19, type:"death", name:"Jonathan Swift",        note:"Écrivain. Mort en 1745. Un maître de la littérature satirique." },
    { month:2,  day:27, type:"birth", name:"John Steinbeck",        note:"Écrivain américain. Né en 1902. Il a reçu le prix Nobel pour « Les Raisins de la colère »." },
    { month:12, day:20, type:"death", name:"John Steinbeck",        note:"Écrivain. Mort en 1968. Il a dépeint avec force la vie des gens simples." },
    { month:9,  day:24, type:"birth", name:"F. Scott Fitzgerald",   note:"Écrivain américain. Né en 1896. Connu pour « Gatsby le Magnifique »." },
    { month:12, day:21, type:"death", name:"F. Scott Fitzgerald",   note:"Écrivain. Mort en 1940. Il a dépeint avec éclat l'Amérique des années 1920." },
    { month:5,  day:17, type:"birth", name:"Erik Satie",            note:"Compositeur français. Né en 1866. Connu pour les « Gymnopédies », au style très personnel." },
    { month:7,  day:1,  type:"death", name:"Erik Satie",            note:"Compositeur. Mort en 1925. Il a beaucoup influencé la musique qui a suivi." },
    { month:6,  day:9,  type:"birth", name:"Cole Porter",           note:"Compositeur américain. Né en 1891. Il a écrit des chansons de comédie musicale pleines d'esprit." },
    { month:10, day:15, type:"death", name:"Cole Porter",           note:"Compositeur. Mort en 1964. Connu pour « Night and Day »." },
    { month:3,  day:7,  type:"birth", name:"Piet Mondrian",         note:"Peintre néerlandais. Né en 1872. Connu pour des tableaux abstraits de rouge, bleu, jaune et lignes noires." },
    { month:2,  day:1,  type:"death", name:"Piet Mondrian",         note:"Peintre. Mort en 1944. Un pionnier de l'art abstrait du XXe siècle." },
    { month:11, day:15, type:"birth", name:"Georgia O'Keeffe",      note:"Peintre américaine. Née en 1887. « Mère de l'art moderne américain », connue pour ses grandes fleurs et ses déserts." },
    { month:3,  day:6,  type:"death", name:"Georgia O'Keeffe",      note:"Peintre. Morte en 1986 à 98 ans. Elle a suivi son propre chemin." },
    { month:8,  day:6,  type:"birth", name:"Andy Warhol",           note:"Artiste américain. Né en 1928. Connu pour le pop art, avec ses boîtes de conserve et ses stars." },
    { month:2,  day:22, type:"death", name:"Andy Warhol",           note:"Artiste. Mort en 1987. Une figure de l'art de la seconde moitié du XXe siècle." },
    { month:9,  day:21, type:"birth", name:"Gustav Holst",          note:"Compositeur anglais. Né en 1874. Connu pour la suite « Les Planètes »." },
    { month:5,  day:25, type:"death", name:"Gustav Holst",          note:"Compositeur. Mort en 1934. La mélodie de « Jupiter » est toujours aimée." },
    { month:5,  day:17, type:"birth", name:"Edward Jenner",         note:"Médecin britannique. Né en 1749. Il a mis au point le premier vaccin (contre la variole)." },
    { month:1,  day:26, type:"death", name:"Edward Jenner",         note:"Médecin. Mort en 1823. Avec la vaccination, il a sauvé d'innombrables vies." },
    { month:2,  day:22, type:"birth", name:"Heinrich Hertz",        note:"Physicien allemand. Né en 1857. Il a prouvé l'existence des ondes électromagnétiques ; l'unité hertz porte son nom." },
    { month:1,  day:1,  type:"death", name:"Heinrich Hertz",        note:"Physicien. Mort en 1894 à 36 ans. Il a posé les bases de la radio." },
    { month:4,  day:16, type:"birth", name:"Wilbur Wright",         note:"Inventeur américain. Né en 1867. Avec son frère Orville, il a fait voler le premier avion." },
    { month:5,  day:30, type:"death", name:"Wilbur Wright",         note:"Inventeur. Mort en 1912. L'aîné des frères Wright." },
    { month:8,  day:19, type:"birth", name:"Orville Wright",        note:"Inventeur américain. Né en 1871. En 1903, avec son frère, il a réussi le premier vol motorisé." },
    { month:1,  day:30, type:"death", name:"Orville Wright",        note:"Inventeur. Mort en 1948. Il a réalisé le rêve de voler." },
    { month:7,  day:26, type:"birth", name:"George Bernard Shaw",   note:"Dramaturge irlandais. Né en 1856. Connu pour « Pygmalion » et prix Nobel de littérature." },
    { month:11, day:2,  type:"death", name:"George Bernard Shaw",   note:"Dramaturge. Mort en 1950 à 94 ans. Connu pour ses œuvres pleines d'esprit." },
    { month:9,  day:21, type:"birth", name:"H. G. Wells",           note:"Écrivain britannique. Né en 1866. « Père de la science-fiction », connu pour « La Machine à explorer le temps »." },
    { month:8,  day:13, type:"death", name:"H. G. Wells",           note:"Écrivain. Mort en 1946. Connu pour son imagination visionnaire." },
    { month:11, day:23, type:"birth", name:"Manuel de Falla",       note:"Compositeur espagnol. Né en 1876. Il a mis la passion de l'Espagne en musique, dans « L'Amour sorcier »." },
    { month:11, day:14, type:"death", name:"Manuel de Falla",       note:"Compositeur. Mort en 1946. Un grand compositeur espagnol du XXe siècle." },
    { month:5,  day:29, type:"birth", name:"Isaac Albéniz",         note:"Compositeur espagnol. Né en 1860. Connu pour la suite pour piano « Iberia »." },
    { month:5,  day:18, type:"death", name:"Isaac Albéniz",         note:"Compositeur. Mort en 1909. Il a laissé des œuvres aux riches couleurs espagnoles." },
    { month:7,  day:27, type:"birth", name:"Enrique Granados",      note:"Compositeur espagnol. Né en 1867. Connu pour la suite pour piano « Goyescas »." },
    { month:3,  day:24, type:"death", name:"Enrique Granados",      note:"Compositeur. Mort en 1916. Il a porté le charme de la musique espagnole dans le monde." },
    { month:3,  day:25, type:"birth", name:"Béla Bartók",           note:"Compositeur hongrois. Né en 1881. Il a étudié les chants populaires et créé une musique du XXe siècle." },
    { month:9,  day:26, type:"death", name:"Béla Bartók",           note:"Compositeur. Mort en 1945. Connu pour son « Concerto pour orchestre »." },
    { month:4,  day:29, type:"birth", name:"Duke Ellington",        note:"Musicien de jazz américain. Né en 1899. Compositeur et chef d'orchestre, il a marqué une époque." },
    { month:5,  day:24, type:"death", name:"Duke Ellington",        note:"Musicien de jazz. Mort en 1974. Il a laissé plus de 1000 morceaux." },
    { month:8,  day:25, type:"birth", name:"Leonard Bernstein",     note:"Compositeur et chef d'orchestre américain. Né en 1918. Connu pour la comédie musicale « West Side Story »." },
    { month:10, day:14, type:"death", name:"Leonard Bernstein",     note:"Compositeur et chef d'orchestre. Mort en 1990. Un chef d'orchestre de renommée mondiale." },
    { month:12, day:8,  type:"birth", name:"Diego Rivera",          note:"Peintre mexicain. Né en 1886. Un maître de la peinture murale mexicaine du XXe siècle." },
    { month:11, day:24, type:"death", name:"Diego Rivera",          note:"Peintre. Mort en 1957. Son épouse était la peintre Frida Kahlo." },
    { month:4,  day:26, type:"birth", name:"Eugène Delacroix",      note:"Peintre français. Né en 1798. Connu pour « La Liberté guidant le peuple » — un maître du romantisme." },
    { month:8,  day:13, type:"death", name:"Eugène Delacroix",      note:"Peintre. Mort en 1863. Ses couleurs vives ont influencé les peintres suivants." },
    { month:6,  day:10, type:"birth", name:"Gustave Courbet",       note:"Peintre français. Né en 1819. Il a mené le réalisme, qui montre les choses telles qu'elles sont." },
    { month:12, day:31, type:"death", name:"Gustave Courbet",       note:"Peintre. Mort en 1877. Connu pour « Les Casseurs de pierres »." },
    /* ---- Lot 4 ---- */
    { month:4,  day:22, type:"death", name:"Miguel de Cervantes",   note:"Écrivain espagnol. Mort en 1616. Connu pour « Don Quichotte », considéré comme un père du roman moderne." },
    { month:7,  day:4,  type:"birth", name:"Nathaniel Hawthorne",   note:"Écrivain américain. Né en 1804. Connu pour « La Lettre écarlate »." },
    { month:5,  day:19, type:"death", name:"Nathaniel Hawthorne",   note:"Écrivain. Mort en 1864. Un pilier de la littérature américaine." },
    { month:5,  day:31, type:"birth", name:"Walt Whitman",          note:"Poète américain. Né en 1819. Connu pour « Feuilles d'herbe » — père du vers libre." },
    { month:3,  day:26, type:"death", name:"Walt Whitman",          note:"Poète. Mort en 1892. Il a chanté l'Amérique d'un cœur large." },
    { month:9,  day:14, type:"birth", name:"Alexander von Humboldt", note:"Naturaliste et explorateur allemand. Né en 1769. Il a exploré l'Amérique latine." },
    { month:5,  day:6,  type:"death", name:"Alexander von Humboldt", note:"Naturaliste. Mort en 1859. Il voyait la nature comme un tout relié." },
    { month:10, day:28, type:"birth", name:"Jonas Salk",            note:"Médecin américain. Né en 1914. Il a mis au point le vaccin contre la poliomyélite." },
    { month:6,  day:23, type:"death", name:"Jonas Salk",            note:"Médecin. Mort en 1995. Il a renoncé à un brevet pour diffuser le vaccin dans le monde." },
    { month:5,  day:27, type:"birth", name:"Rachel Carson",         note:"Biologiste américaine. Née en 1907. Avec « Printemps silencieux », elle a alerté sur l'environnement." },
    { month:4,  day:14, type:"death", name:"Rachel Carson",         note:"Biologiste et auteure. Morte en 1964. Elle a lancé le mouvement écologiste." },
    { month:2,  day:15, type:"birth", name:"Ernest Shackleton",     note:"Explorateur britannique. Né en 1874. Lors d'une expédition en Antarctique, il a sauvé tout son équipage." },
    { month:1,  day:5,  type:"death", name:"Ernest Shackleton",     note:"Explorateur. Mort en 1922. On se souvient de lui comme d'un chef indomptable." },
    { month:7,  day:18, type:"birth", name:"Nelson Mandela",        note:"Homme politique sud-africain. Né en 1918. Il a lutté contre l'apartheid et est devenu le premier président noir ; prix Nobel de la paix." },
    { month:12, day:5,  type:"death", name:"Nelson Mandela",        note:"Homme politique. Mort en 2013 à 95 ans. Vénéré dans le monde comme symbole de réconciliation." },
    { month:1,  day:14, type:"birth", name:"Albert Schweitzer",     note:"Médecin et penseur né en Allemagne. Né en 1875. Il a soigné en Afrique et reçu le prix Nobel de la paix." },
    { month:9,  day:4,  type:"death", name:"Albert Schweitzer",     note:"Médecin et penseur. Mort en 1965. Il a enseigné le « respect de la vie »." },
    { month:12, day:2,  type:"birth", name:"Maria Callas",          note:"Cantatrice née aux États-Unis. Née en 1923. L'une des plus grandes sopranos d'opéra du XXe siècle." },
    { month:9,  day:16, type:"death", name:"Maria Callas",          note:"Cantatrice. Morte en 1977. On l'appelait « la Divine »." },
    { month:2,  day:25, type:"birth", name:"Enrico Caruso",         note:"Chanteur italien. Né en 1873. Un ténor majeur du début du XXe siècle." },
    { month:8,  day:2,  type:"death", name:"Enrico Caruso",         note:"Chanteur. Mort en 1921. L'une des premières stars du disque." },
    { month:12, day:19, type:"birth", name:"Édith Piaf",            note:"Chanteuse française. Née en 1915. Icône de la chanson, connue pour « La Vie en rose » et « L'Hymne à l'amour »." },
    { month:10, day:10, type:"death", name:"Édith Piaf",            note:"Chanteuse. Morte en 1963. Elle a mis sa vie mouvementée dans ses chansons." },
    { month:5,  day:3,  type:"birth", name:"Bing Crosby",           note:"Chanteur et acteur américain. Né en 1903. Connu pour « White Christmas »." },
    { month:10, day:14, type:"death", name:"Bing Crosby",           note:"Chanteur. Mort en 1977. Il a aussi réussi à la radio et au cinéma." },
    { month:3,  day:17, type:"birth", name:"Nat King Cole",         note:"Chanteur et pianiste de jazz américain. Né en 1919. Il a charmé le monde de sa voix douce." },
    { month:2,  day:15, type:"death", name:"Nat King Cole",         note:"Chanteur. Mort en 1965. Il a laissé de nombreux succès." },
    { month:4,  day:30, type:"birth", name:"Franz Lehár",           note:"Compositeur austro-hongrois. Né en 1870. Connu pour l'opérette « La Veuve joyeuse »." },
    { month:10, day:24, type:"death", name:"Franz Lehár",           note:"Compositeur. Mort en 1948. Un maître de l'opérette viennoise." },
    { month:8,  day:29, type:"birth", name:"Jean-Auguste-Dominique Ingres", note:"Peintre français. Né en 1780. Connu pour ses lignes pures et ses portraits — maître du néoclassicisme." },
    { month:1,  day:14, type:"death", name:"Jean-Auguste-Dominique Ingres", note:"Peintre. Mort en 1867. Il était aussi un excellent violoniste." },
    { month:8,  day:30, type:"birth", name:"Jacques-Louis David",   note:"Peintre français. Né en 1748. Connu pour « Le Sacre de Napoléon » — chef du néoclassicisme." },
    { month:12, day:29, type:"death", name:"Jacques-Louis David",   note:"Peintre. Mort en 1825. Il a marqué une époque par ses grandes scènes historiques." },
    { month:11, day:21, type:"birth", name:"Voltaire",              note:"Penseur et écrivain français. Né en 1694. Connu pour « Candide » ; il défendait la liberté et la tolérance." },
    { month:5,  day:30, type:"death", name:"Voltaire",              note:"Penseur. Mort en 1778. Une grande figure des Lumières." },
    { month:6,  day:28, type:"birth", name:"Jean-Jacques Rousseau", note:"Penseur né à Genève. Né en 1712. Connu pour « Du contrat social » et « Émile »." },
    { month:7,  day:2,  type:"death", name:"Jean-Jacques Rousseau", note:"Penseur. Mort en 1778. Il a profondément marqué la politique et l'éducation modernes." },
    { month:3,  day:6,  type:"birth", name:"Gabriel García Márquez", note:"Écrivain colombien. Né en 1927. Il a reçu le prix Nobel pour « Cent Ans de solitude »." },
    { month:4,  day:17, type:"death", name:"Gabriel García Márquez", note:"Écrivain. Mort en 2014. Il a séduit le monde par le réalisme magique." },
    { month:7,  day:12, type:"birth", name:"Pablo Neruda",          note:"Poète chilien. Né en 1904. Il a reçu le prix Nobel pour ses poèmes passionnés." },
    { month:9,  day:23, type:"death", name:"Pablo Neruda",          note:"Poète. Mort en 1973. Un grand poète d'Amérique latine." },
    { month:2,  day:15, type:"birth", name:"Galilée",               note:"Savant italien. Né en 1564. Il a observé le ciel à la lunette — « père de la science moderne »." },
    { month:1,  day:8,  type:"death", name:"Galilée",               note:"Savant. Mort en 1642. Connu pour la phrase « Et pourtant elle tourne »." },
    { month:6,  day:19, type:"birth", name:"Blaise Pascal",         note:"Mathématicien et penseur français. Né en 1623. Connu pour la phrase « L'homme est un roseau pensant »." },
    { month:8,  day:19, type:"death", name:"Blaise Pascal",         note:"Mathématicien et penseur. Mort en 1662 à 39 ans. L'unité pascal porte son nom." },
    { month:1,  day:8,  type:"birth", name:"Stephen Hawking",       note:"Physicien britannique. Né en 1942. Malgré une grave maladie, il a étudié l'univers et les trous noirs." },
    { month:3,  day:14, type:"death", name:"Stephen Hawking",       note:"Physicien. Mort en 2018. Connu pour « Une brève histoire du temps »." },
    { month:11, day:9,  type:"birth", name:"Carl Sagan",            note:"Astronome américain. Né en 1934. Dans la série télévisée « Cosmos », il a montré la magie de l'univers." },
    { month:12, day:20, type:"death", name:"Carl Sagan",            note:"Astronome. Mort en 1996. Un pionnier de la vulgarisation scientifique." },
    { month:7,  day:24, type:"birth", name:"Simón Bolívar",         note:"Militaire et homme politique né au Venezuela. Né en 1783. Il a mené l'indépendance de l'Amérique du Sud — « le Libérateur »." },
    { month:12, day:17, type:"death", name:"Simón Bolívar",         note:"Homme politique. Mort en 1830. La Bolivie porte son nom." },
    { month:3,  day:2,  type:"birth", name:"Bedřich Smetana",       note:"Compositeur tchèque. Né en 1824. Connu pour le cycle « Ma Patrie » (La Moldau)." },
    { month:5,  day:12, type:"death", name:"Bedřich Smetana",       note:"Compositeur. Mort en 1884. Surnommé le père de la musique nationale tchèque." },
    { month:7,  day:2,  type:"birth", name:"Christoph Willibald Gluck", note:"Compositeur allemand. Né en 1714. Connu pour l'opéra « Orphée et Eurydice » — un réformateur." },
    { month:11, day:15, type:"death", name:"Christoph Willibald Gluck", note:"Compositeur. Mort en 1787. Il a ouvert la voie à l'opéra moderne." },
    { month:7,  day:10, type:"birth", name:"Carl Orff",             note:"Compositeur allemand. Né en 1895. Connu pour la cantate « Carmina Burana »." },
    { month:3,  day:29, type:"death", name:"Carl Orff",             note:"Compositeur. Mort en 1982. Il a beaucoup œuvré pour l'éducation musicale des enfants." },
    { month:11, day:14, type:"birth", name:"Aaron Copland",         note:"Compositeur américain. Né en 1900. Il a créé une musique typiquement américaine, comme « Appalachian Spring »." },
    { month:12, day:2,  type:"death", name:"Aaron Copland",         note:"Compositeur. Mort en 1990. Surnommé le « père de la musique américaine »." },
    { month:5,  day:30, type:"birth", name:"Benny Goodman",         note:"Musicien de jazz américain. Né en 1909. Virtuose de la clarinette, le « roi du swing »." },
    { month:6,  day:13, type:"death", name:"Benny Goodman",         note:"Musicien de jazz. Mort en 1986. Connu aussi pour ses orchestres mixtes." },
    { month:4,  day:25, type:"birth", name:"Ella Fitzgerald",       note:"Chanteuse de jazz américaine. Née en 1917. Saluée comme la « reine du chant »." },
    { month:6,  day:15, type:"death", name:"Ella Fitzgerald",       note:"Chanteuse de jazz. Morte en 1996. Elle a charmé le monde de sa voix limpide." },
    { month:6,  day:6,  type:"birth", name:"Thomas Mann",           note:"Écrivain allemand. Né en 1875. Il a reçu le prix Nobel pour « La Montagne magique »." },
    { month:8,  day:12, type:"death", name:"Thomas Mann",           note:"Écrivain. Mort en 1955. Une figure majeure de la littérature allemande du XXe siècle." },
    { month:7,  day:2,  type:"birth", name:"Hermann Hesse",         note:"Écrivain né en Allemagne. Né en 1877. Il a reçu le prix Nobel pour « L'Ornière » et « Siddhartha »." },
    { month:8,  day:9,  type:"death", name:"Hermann Hesse",         note:"Écrivain. Mort en 1962. Ses œuvres sur la maturation intérieure sont très lues." },
    { month:7,  day:3,  type:"birth", name:"Franz Kafka",           note:"Écrivain né à Prague. Né en 1883. Connu pour « La Métamorphose » et ses images de l'absurde." },
    { month:6,  day:3,  type:"death", name:"Franz Kafka",           note:"Écrivain. Mort en 1924. Il a fortement marqué la littérature du XXe siècle." },
    { month:7,  day:10, type:"birth", name:"Marcel Proust",         note:"Écrivain français. Né en 1871. Connu pour le grand roman « À la recherche du temps perdu »." },
    { month:11, day:18, type:"death", name:"Marcel Proust",         note:"Écrivain. Mort en 1922. Il a dépeint finement la mémoire et le temps." },
    { month:6,  day:25, type:"birth", name:"George Orwell",         note:"Écrivain britannique. Né en 1903. Connu pour « La Ferme des animaux » et « 1984 »." },
    { month:1,  day:21, type:"death", name:"George Orwell",         note:"Écrivain. Mort en 1950. Il a dénoncé avec acuité les dangers du totalitarisme." },
    { month:12, day:4,  type:"birth", name:"Rainer Maria Rilke",    note:"Poète autrichien. Né en 1875. Connu pour les « Élégies de Duino »." },
    { month:12, day:29, type:"death", name:"Rainer Maria Rilke",    note:"Poète. Mort en 1926. Ses « Lettres à un jeune poète » sont très lues." },
    { month:6,  day:11, type:"birth", name:"John Constable",        note:"Peintre anglais. Né en 1776. Connu pour des paysages de son pays comme « La Charrette de foin »." },
    { month:3,  day:31, type:"death", name:"John Constable",        note:"Peintre. Mort en 1837. Il a insufflé une vie nouvelle au paysage." },
    { month:7,  day:16, type:"birth", name:"Camille Corot",         note:"Peintre français. Né en 1796. Connu pour ses paysages à la lumière douce — un précurseur de l'impressionnisme." },
    { month:2,  day:22, type:"death", name:"Camille Corot",         note:"Peintre. Mort en 1875. Aimé aussi pour sa bonté et sa générosité envers les jeunes." },
    { month:2,  day:22, type:"birth", name:"George Washington",     note:"Militaire et homme politique américain. Né en 1732. Il a mené la guerre d'Indépendance et fut le premier président." },
    { month:12, day:14, type:"death", name:"George Washington",     note:"Homme politique. Mort en 1799. Surnommé le « père de la nation »." },
    { month:1,  day:17, type:"birth", name:"Benjamin Franklin",     note:"Homme politique et savant américain. Né en 1706. Il a montré que la foudre est électrique et participé à la Déclaration d'indépendance." },
    { month:4,  day:17, type:"death", name:"Benjamin Franklin",     note:"Homme politique et savant. Mort en 1790. L'un des pères fondateurs des États-Unis." },
    { month:7,  day:12, type:"birth", name:"George Eastman",        note:"Entrepreneur américain. Né en 1854. Avec la pellicule en rouleau, il a rendu la photo accessible (fondateur de Kodak)." },
    { month:3,  day:14, type:"death", name:"George Eastman",        note:"Entrepreneur. Mort en 1932. Aussi un généreux bienfaiteur." },
    { month:8,  day:19, type:"birth", name:"Coco Chanel",           note:"Créatrice de mode française. Née en 1883. Avec des vêtements confortables et un parfum, elle a changé son époque." },
    { month:1,  day:10, type:"death", name:"Coco Chanel",           note:"Créatrice de mode. Morte en 1971. Une influence majeure du XXe siècle." },
    { month:10, day:26, type:"birth", name:"Domenico Scarlatti",    note:"Compositeur italien. Né en 1685. Connu pour 555 sonates pour clavier." },
    { month:7,  day:23, type:"death", name:"Domenico Scarlatti",    note:"Compositeur. Mort en 1757. Né la même année que Bach et Haendel." },
    { month:6,  day:17, type:"birth", name:"Charles Gounod",        note:"Compositeur français. Né en 1818. Connu pour l'opéra « Faust » et son « Ave Maria »." },
    { month:10, day:18, type:"death", name:"Charles Gounod",        note:"Compositeur. Mort en 1893. Aimé pour ses belles mélodies." },
    { month:4,  day:6,  type:"death", name:"Igor Stravinsky",       note:"Compositeur né en Russie. Mort en 1971. Avec le ballet « Le Sacre du printemps », il a révolutionné la musique." }
  ]
};
